### ISSUE TITLE
[FR] automatic search bar cursor insertion in list view

### ISSUE THREAD

**Issue by greg1075** [alienator88/Pearcleaner#10]
Upon hovering over or at least when clicking on the magnifier icon in list view, it would be nice to have the cursor automatically inserted in the search bar so that the user can start typing right away. Currently, you have to place the cursor left and away from the magnifier, then click to be able to start typing.  

Also, the app list is refreshed when clicking in the search and the cursor is inserted. Could this be avoided, and the app list only refreshed when entering list view (after clicking the list view button or drop area) or after an app is deleted?

**Comment by alienator88** [comment]
Hey, I edited the search bar to auto-focus the cursor when you hover over it. Also enlarged the hidden space in front of the Search Icon so you can hover on the search icon or anywhere to the left of it to show the full search bar. This should make it easier so you don't necessarily have to aim for the search icon every time.
These updates should be out in `v2.0` when I get that out. I want to get a few more fixes and features added before I release that one.

As for the app list refresh, it already refreshes the app list when the app launches and also when an app is deleted, so no need for any changes on that front. 
The reason for the refresh button in the search bar is if you're in the app list view and you install an app for example during this time. The app list won't know to refresh automatically, so just a manual catch there in case a user wants to manually refresh the apps again. I will probably leave that as is.

**Comment by greg1075** [comment]
Oh, yeah that makes sense.

Thanks for adding the cursor placement feature and space tweak!

**Comment by alienator88** [comment]
Something I was thinking, the app already has the option to do CMD+R to refresh the app list via keyboard.

Maybe I add a setting to allow hide/show of the refresh button for users who like to use the keyboard more. As an additional option?

**Comment by greg1075** [comment]
I’m not sure I’m following. I don’t see a refresh button currently. The
only ways I see are either by clicking the search bar, going to the
Pearcleaner menu > Refresh Apps, or the CMD+R shortcut.

On another note, I would consider adding a way to toggle mini mode from the
GUI.

Also, there seems to be an inconsistency with the window size when toggling
mini mode off and back on. If I set the mini mode window to a certain size,
toggle mini mode off and then back on, the window doesn’t go back to the
size I set but what looks like the smallest size possible.

https://www.dropbox.com/s/p133gdxy3yahmen/CleanShot%202023-12-15%20at%2013.35.04.mp4?dl=0

Lastly, it looks like the default mini mode view when toggling it on from
regular mode is list view. I would consider changing that to the drop view
as it is the default view when launching Pearcleaner if set to mini mode.

Happy to enter all this in Github if you’d like.

Cheers,

Greg

**Comment by alienator88** [comment]
That's what I was referring to, the refresh button inside the search bar.

As for the mini mode toggle, I'm trying to weigh the options on how often a user would need to do this. If it's not often, it seems like it should stay in the Settings and not clutter the UI. I guess I'm not understanding the workflow for swapping back and forth between mini and regular mode so much that this would come up as an issue. Maybe a keyboard shortcut of CMD+M or something similar to toggle between each one.

I'll play around with the window sizing to see if that can be fixed, but it might be a limitation of SwiftUI and/or macOS. The issue is that macOS caches the window size of an app in ~/Library/Preferences/*.plist. But it can only record one size for the main window. This app has technically 2 view sizes inside the same app window depending on the mode, so it can't record both. Might not be able to fix this one.

As for the app list view when switching to mini, I can fix that pretty easily.

**Comment by greg1075** [comment]
Actually I think you’re right about the mini mode toggle. Better to leave
out of the UI if use seldom used. Personally I leave it in mini mode.

Regarding he refresh button. So would “hiding” it (even though it’s
technically embedded within the search bar) deactivate the automatic
refreshing of the apps when clicking on the search bar, allowing
keyboard-centric users to just rely on CMD+R? I want to make sure I
understand what the behavior would be...

**Comment by alienator88** [comment]
Yeah, so hiding the toggle if a user prefers it that way would just hide the little refresh icon inside the search bar.
The app list would still refresh on app load, deletion of an app or via the keyboard command.
I don't know if this is even required or not, just spitballing 😂

**Comment by greg1075** [comment]
Oh, I see. I didn’t even realize the double circular arrow thing was the
refresh button (facepalm)

It’s a good idea. But I’d say it’s more of a cherry on top kinda thing.

**Comment by alienator88** [comment]
Yeah I'll leave that alone for now, doesn't seem necessary.
So I have the original request fixed and also toggling to mini mode shows the drop zone initially instead of the app list view now.
I'll get these changes out in the next version.
Thanks for the input as always Greg!

**Comment by greg1075** [comment]
Welcome,


Regarding the window size, I also noted that same behavior either after a
system reboot, or after the app is launched after a while. It opens
normally (i.e. window same size as set by user) if the app is launched
relatively shortly after it was closed, by after a while (not sure how
long, though), the window size is reset to 900x450 (per Pixelsnap).


Greg

**Comment by alienator88** [comment]
Hey Greg,

I think I found the issue with the window sizing. I had the function `applicationShouldTerminateAfterLastWindowClosed` set to true. That means when the X button on the window was being used, it would terminate the application instead of soft quitting like CMD+Q does. Because of this termination, it didn't record the dimensions of the window to the preferences plist file correctly. 
I tested a few times with this function set to false and it has been opening the same window size after multiple reboots.
The only difference going forward is that when clicking the X button on the window, Pearcleaner won't fully quit, but just close the window. So to fully quit in the future CMD+Q would need to be used like other apps. 
I'll have this out in the next version.

**Comment by greg1075** [comment]
Awesome! Thanks for looking into it and fixing it. I never use the x
button myself, but regardless I think the new behavior is more in line with
what most users expect i.e. x just closes the window, and CMD+ to quit the
app.

Cheers,

Greg

**Comment by alienator88** [comment]
No problem. Once `2.1` is out, let me know if you still see the window sizing issue and I'll dig back into it.

**Comment by greg1075** [comment]
Will do.

**Comment by greg1075** [comment]
Latest version seems to have fixed the window size issue.

**Comment by alienator88** [comment]
Awesome! Thanks for confirming :)

**Comment by greg1075** [comment]
Welcome. By the way, still considering changing the dashed drop area for a
gradient fill?

**Comment by alienator88** [comment]
Most likely not at this time. I messed around with swapping that to a gradient a little while back and it just looked really off for some reason. Didn't really flow with the rest of the UI.

**Comment by greg1075** [comment]
Gotcha. Thanks for giving it a whirl!

**Comment by greg1075** [comment]
I spoke too fast about the window size. It appears that after a reboot, it
opens again at that larger size. I’m not sure if the same thing still
happens after opening Pearcleaner a long time after quitting. I think it
did before. It does open at the size it was set when launching the
relatively shortly after it was quit.

**Comment by alienator88** [comment]
I'll keep an eye on it on my end too. I haven't had it happen yet on mine with the newer update.
I think the issue might be a race condition when the app loads. It checks a setting in the preferences of the user to see if they have mini mode selected and based on that, it loads the mini or regular view. If this setting takes longer to read or isn't cached, I think it quickly tries to load the regular window dimensions and then puts the mini view inside it. 
Kinda lame, I'll try messing around with the window management when I have more time.

**Comment by alienator88** [comment]
Out of curiosity, do you use multiple monitors in your setup? I have 2 monitors with laptop in clamshell mode and can repro this issue. 
Wondering if users with no external monitors experience it as well.

**Comment by greg1075** [comment]
No, just a laptop. I know next to nothing about coding, but out of
curiosity ran the issue in ChatGPT. I have zero idea whether this is
helpful or not, but here is the answer I got:


*There could be a few reasons why your app's window size changes when it is
relaunched after being resized by the user. Here are some possible causes
and solutions:*

*1. Window state preservation: SwiftUI automatically preserves the state of
your app's windows, including their size and position. When the app is
relaunched, it restores the previously saved state. To prevent this
behavior, you can disable window state preservation by setting the
`preservesWindowSceneState` property to `false` in your app's
`SceneDelegate` or `AppDelegate` file.*

*2. Window size preferences: SwiftUI provides a ***@***.***` property
wrapper that allows you to save and restore values specific to a scene,
such as the window size. If you are using this property wrapper to store
the window size, it will be restored when the app relaunches. To prevent
this, you can remove or modify the code that uses ***@***.***` to store
the window size.*

*3. Window configuration: If you are explicitly configuring the window size
in your code, it may override the user's resized window when the app
relaunches. Check your code for any window configuration settings and
ensure that they are not overriding the user's preferred window size.*

*By addressing these potential causes, you should be able to prevent your
app's window size from changing when it is relaunched after being resized
by the user.*

**Comment by alienator88** [comment]
Yeah, I've played with all that stuff already for the most part.
From the research I've been doing on this, it sounds like a SwiftUI bug. 
Since this app is 100% SwiftUI, it's not as good with certain OS interoperability like the older AppKit apps are.

I've found a bunch of posts on reddit from others experiencing similar issues with other swift apps as well.

I think I'll just need to write my own window management class so it can save the window dimensions on app exit and then restore them myself on app launch. This way I can bypass the OS preferences plist file that seems borked with Swift.

**Comment by alienator88** [comment]
@greg1075 can I give you a pre-release version of 2.2 so you can test out the window sizing issue?
I wrote my own window management logic to save the window size and coordinates manually and load them on app startup.
This should get around the OS issue where it doesn't remember after reboot or after a while.

One thing to keep in mind, it saves this data to the user preferences file. So when you change the window size, it could take around 5 seconds to save this information, it's just how macOS works with preference files. 
So if you change the window size and close it right away, the OS might've not had enough time to save the new size to the preferences file. 
I would size the window and set position where you want it, give it a few seconds and then close it and test it out again.
You can always look at the file `~/Library/Preferences/com.alienator88.Pearcleaner.plist` to see the updated values inside. The relevant keys I use for this window management flow are:
```
<key>windowHeightKey</key>
<real>328</real>
<key>windowWidthKey</key>
<real>300</real>
<key>windowXKey</key>
<real>3062</real>
<key>windowYKey</key>
<real>633</real>
```

[Pearcleaner.zip](https://github.com/alienator88/Pearcleaner/files/13772880/Pearcleaner.zip)

**Comment by greg1075** [comment]
Hi,

I installed 2.2 and set a window size. I will wait a while and see if it’s
saved on the next start up. I’ll let you know.

Greg

**Comment by alienator88** [comment]
Awesome, thanks!
I tried logging out and rebooting a few times and it kept it saved on my end, so hopefully this is the end of that problem 😂

**Comment by greg1075** [comment]
Sees to be working fine! Shut down my laptop for over an hour, and the
window size was as recorded. That said, the version number says 2.1 in the
version you sent me.



Greg

**Comment by alienator88** [comment]
That's good to hear!
I'm confused on the version number, is it possible you might have another version laying around and launched the older one?
I just downloaded the zip file from the comment above and it's showing v2.2, build 13 in the About tab in Settings.

**Comment by greg1075** [comment]
No, I replaced the old version with the one you sent me in the
Applications folder - but I just noticed a discrepancy between the version
number listed in Get Info (2.2) vs within the app (2.1)

**Comment by alienator88** [comment]
That's so odd, I'm not seeing that at all on my end 😂 
![image](https://github.com/alienator88/Pearcleaner/assets/6263626/ffa60b54-fb45-4a7d-b654-d6e1f23181cb)

**Comment by greg1075** [comment]
If I go to Settings>About, I get the same thing as you i.e. 2.2 (build
13), but from the check for updates window it says 2.1.

**Comment by alienator88** [comment]
Ah yeah, that makes sense. The update window shows the most recent release
on GitHub which is still 2.1.
Like I mentioned, this zip file was a pre-release so it’s not public yet.

**Comment by greg1075** [comment]
Ah, I see.

**Comment by greg1075** [comment]
Just noticed that the window size resets to the default size after clicking
the Force Update button.

I don’t think people are going to use that button much, but still wanted to
let you know.

**Comment by alienator88** [comment]
Yeah, that's expected. Same reason as yesterday. Force update pulled the latest version from Github releases which is 2.1 and that version doesn't have the window management logic. It overwrote the 2.2 pre-release version I gave you yesterday.

**Comment by greg1075** [comment]
Oh, duh. Sorry.

**Comment by alienator88** [comment]
All good. Give me a few minutes and I'll have 2.2 out.
