### ISSUE TITLE
[FR] Ability Hide the and expand the User and System categories.

### ISSUE THREAD

**Issue by seenukarthi** [alienator88/Pearcleaner#103]
It would be helpful to hide and expand the categories like a tree.

**Comment by alienator88** [comment]
Hey there, so clicking User or System headers would collapse and expand those apps, right?

**Comment by seenukarthi** [comment]
> Hey there, so clicking User or System headers would collapse and expand those apps, right?

No, it doesn't
![CleanShot 2024-09-12 at 13 12 44](https://github.com/user-attachments/assets/e48e1d81-066b-473a-9918-1b1bc0f294d7)

**Comment by alienator88** [comment]
FYI, I added this feature to the app. It will be out in the next release when that comes out.
I need to do a few more things before I release it though.
Thanks!
