### ISSUE TITLE
[FR] Select custom terminal app when executing homebrew cleanup

### ISSUE THREAD

**Issue by Lucas04-nhr** [alienator88/Pearcleaner#104]
**Is your feature request related to a problem? Please describe.**

When executing homebrew cleanup, the app uses "Terminal.app" and its default profile as an interacctive shell. However, due to some customization and performance tools such as oh-my-zsh and starship utils, the default terminal application cannot display the prompt properly (see fig.1 below), so I change my system default terminal app to "iTerm.app", which can properly display the shell prompts (fig.2). 

---

<img width="665" alt="Terminal.app interface" src="https://github.com/user-attachments/assets/d5a557ef-1411-4902-b1bd-47c4ad4e3d47">

---

<img width="745" alt="iTerm.app interface" src="https://github.com/user-attachments/assets/55f8f238-b912-47a4-80a2-dddc3fee2333">

---

**Describe the solution you'd like**

I hope the pearcleaner app can add a choice to choose which terminal app should be used when executing `brew cleanup ...`.

**Comment by alienator88** [comment]
That's a good idea, I should be able to add a button in the settings where you can select which Terminal app you want the cleanup to run with

**Comment by alienator88** [comment]
So I looked into this and adding a Terminal app selection menu, but ran into some issues.
Some terminals don't even support AppleScript execution, and the ones that do, like iTerm have different commands that need to be executed to run a script. If the terminal apps don't support the `do script` applescript function, I would need to add exceptions for different commands for all terminal apps out there and this is way out of scope for this app.
Unfortunately I will need to leave it using the default Terminal.app for now. Eventually in the future I want to try and somehow build the brew cleanup inside the Pearcleaner app and not have it open a terminal at all.
