### ISSUE TITLE
[BUG] Using Alfred workflow to quickly launch Pearcleaner will open two windows

### ISSUE THREAD

**Issue by ssfun** [alienator88/Pearcleaner#106]
**Describe the bug:** <br>
Using Alfred workflow to quickly launch Pearcleaner for app uninstallation will open two Pearcleaner windows.
[Alfred-Pearcleaner](https://github.com/andylundqvist/alfred-pearcleaner
)

**Expected behavior** <br>
Normally only one pearcleaner window should be opened. 

**Info:**
 - OS: [e.g. 15.0]
 - Pearcleaner Version: [e.g. 3.8.6]

**Comment by alienator88** [comment]
I'm not sure how alfred workflows work. Looking at that repo, the owner mentioned they only tested on macOS 14.5.
I also haven't tested/built for Sequoia yet, which it seems you are running currently.
Not sure if this is a Pearcleaner issue or the workflow just needs an update maybe?

**Comment by alienator88** [comment]
As a test, can you try enabling One-Shot Mode in the Pearcleaner general settings tab?
Does it still open two windows with that enabled?

**Comment by ssfun** [comment]
Using shell commands will also open two windows.

`/Applications % open -a Pearcleaner Telegram.app`

**Comment by ssfun** [comment]
> As a test, can you try enabling One-Shot Mode in the Pearcleaner general settings tab?
> Does it still open two windows with that enabled?

After enabling, it still open two windows at the same time.

**Comment by alienator88** [comment]
I just updated my OS to Sequoia last night. I tested the current version of Pearcleaner and I see the same issue, two windows.
I then built a new version using the Sequoia xcode tools and it doesn't happen anymore. 
Can you test this build out for me and see if you still have issues? Please note that this build is larger in size and not signed/notarized yet:
[Pearcleaner.zip](https://github.com/user-attachments/files/17062169/Pearcleaner.zip)

**Comment by ssfun** [comment]
it

> I just updated my OS to Sequoia last night. I tested the current version of Pearcleaner and I see the same issue, two windows. I then built a new version using the Sequoia xcode tools and it doesn't happen anymore. Can you test this build out for me and see if you still have issues? Please note that this build is larger in size and not signed/notarized yet: [Pearcleaner.zip](https://github.com/user-attachments/files/17062169/Pearcleaner.zip)

It's work. Thanks.

**Comment by alienator88** [comment]
Awesome. I will have the fix out in the next version. Just need to throw in a couple other bug fixes for Sequoia.
