### ISSUE TITLE
[BUG] Sequoia - Unable to confirm deletion through Touch ID

### ISSUE THREAD

**Issue by alienator88** [alienator88/Pearcleaner#107]
Unable to confirm deletion through Touch ID !
Is this linked to the above reported issue?

<img width="1512" alt="Screenshot 2024-09-19 at 1 53 41 AM" src="https://github.com/user-attachments/assets/62fab13b-86bd-495c-acf7-e145ed3e175d">

_Originally posted by @mh-saeed in https://github.com/alienator88/Pearcleaner/issues/84#issuecomment-2359397338_

**Comment by alienator88** [comment]
Sequoia debug build for testing:
[Pearcleaner.zip](https://github.com/user-attachments/files/17062248/Pearcleaner.zip)

**Comment by alienator88** [comment]
Again wanted to mention that the Finder Extension in the Pearcleaner settings has nothing to do with this alert box:
![image](https://github.com/user-attachments/assets/5dd0a643-6186-405b-b6f2-1cb76dc1a988)

That alert box only comes up when Pearcleaner tells Finder to delete files in a root directory, like `/var/db` in your original screenshot. It won't come up for apps/files that are not in a root directory.

Can you test deleting an app that does have files in a root directory like the Battery Health 2 from before? Sometimes the authentication alert box might not come up if you already authenticated in the last 15 minutes. Depends.

**Comment by alienator88** [comment]
Seems to be an issue with Script Editor not working with Touch ID anymore. Found a few posts like this: https://www.reddit.com/r/MacOS/comments/171mebu/script_editor_no_longer_asks_for_touchid_when/

**Comment by mh-saeed** [comment]
I got your point.
![Screen Recording 2024-09-19 at 10 55 28 PM](https://github.com/user-attachments/assets/f77fe51f-a031-4e2f-b313-a352369302b6)

**Comment by alienator88** [comment]
Unfortunately, unless Apple fixes allowing AppleScript to use TouchID again, it might not ever work. Really depends on them at this point. 
Pearcleaner needs to use AppleScript to execute the delete files action as I have to use Finder for that to allow for undo of deletion.
I'll close this for now, but will keep an eye out for any changes later down the road, maybe they'll fix it.
