### ISSUE TITLE
Support for brew integration when default shell is fish instead of zsh

### ISSUE THREAD

**Issue by RafalSkolasinski** [alienator88/Pearcleaner#108]
**Is your feature request related to a problem? Please describe.**

Removing app installed through homebrew when default shell is not zsh.

**Describe the solution you'd like**

It works when default shell is not zsh, e.g. fish.

**Describe alternatives you've considered**

**Additional context**

N/A

**Comment by alienator88** [comment]
I'll take a look to see if I can just have it use the user's environment shell. I'll keep you updated.

**Comment by KaBankz** [comment]
I think the easiest solution would be to just run the cleanup script with bash.

https://github.com/alienator88/Pearcleaner/blob/3c50edc53ce392e159d7baf611ec0e590305042e/Pearcleaner/Logic/Utilities.swift#L289-L302

Haven't tested it out, but this should work, unless I forgot to escape a character

```swift
let script = """
tell application "Terminal"
    activate
    do script "
    /bin/bash --noprofile --norc -ec \\"\
        found_cask=$(\(cmd) list --cask | grep '\(formattedApp)'); \\
        if [ -n \\"$found_cask\\" ]; then \\
            \(cmd) uninstall --cask \\"$found_cask\\" --force; \\
            \(cmd) cleanup; \\
        else \\
            echo \\"Cask not found for \(formattedApp)\\"; \\
        fi; \\
    \\";
    "
end tell
"""
```

**Comment by alienator88** [comment]
@KaBankz that might make more sense instead of dealing with all the different shells.
I tested it and it seems to work fine.

**Comment by RafalSkolasinski** [comment]
Yeah, could assume that bash (or zsh, we are talking mac after all) is always present and call script with that :).

Sorry for being very brief when posting the issue. Was in the middle of something and wanted to post before I forget about it... I am loving the Pearcleaner so far!

**Comment by alienator88** [comment]
@RafalSkolasinski no worries! I have this added in now so it will be out in the next release.
Thanks for submitting!

**Comment by KaBankz** [comment]
> Yeah, could assume that bash (or zsh, we are talking mac after all) is always present and call script with that :).

Apple won't remove bash, too much of the UNIX ecosystem depends on it. They just froze the bash version to the last GPLv2 release (decades old now) and changed the default shell to zsh.

**Comment by alienator88** [comment]
I made this change for the next release, could someone test this build out and see how it works on your end before I close this issue out?
[Pearcleaner.zip](https://github.com/user-attachments/files/17091565/Pearcleaner.zip)

**Comment by KaBankz** [comment]
Just tested it out, and it works perfectly

**Comment by alienator88** [comment]
Thank you for testing!
I should have the next release out tomorrow hopefully.
