### ISSUE TITLE
[BUG] Two Terminal Windows Open and ‘Cask Not Found’ Error When Deleting an App with Homebrew Cleanup Enabled

### ISSUE THREAD

**Issue by moealkurdi** [alienator88/Pearcleaner#109]
**Describe the bug:** <br>
When homebrew cleanup is enabled in the settings and you delete an app, Two default terminal windows open, one of them is blank and the other has a command that tries to delete the app from homebrew but it returns "Cask not found for selfcontrol"

**Steps to reproduce:**
1. "Turn on 'Homebrew cleanup' in the settings"
2. Delete an app.

**Expected behavior** <br>
After app deletion, two default terminal windows are opened. A blank window and another trying to delete the app from homebrew but fails.

**Info:**
 - OS: [e.g. 15.0]
 - Pearcleaner Version: [e.g. 3.8.7]

**Console Logs (For app crashes):**
 - Open the Console.app on your mac
 - Enter `Pearcleaner` in the search box and hit Enter
 - Click Start to record logs ![image](https://github.com/alienator88/Pearcleaner/assets/6263626/dc706fa1-0800-4eaf-aee6-8516da83fcff)
 - Reproduce the issue you're experiencing in Pearcleaner
 - Click Pause <br> ![image](https://github.com/alienator88/Pearcleaner/assets/6263626/826962a1-4212-4b64-a24a-ea6663defb46)
 - Export the captured logs using the Share button

**Screenshots**
<img width="659" alt="image" src="https://github.com/user-attachments/assets/37bfeb5a-66e4-4490-a7cd-c96969b16670">

**Additional context**

Note: This is my first time reporting a bug so sorry if I didn't do it properly.

**Comment by alienator88** [comment]
This should be fixed by issue #108.
I'll have another release to push today or tomorrow if those fixes aren't in the latest version yet.
