### ISSUE TITLE
[FR] Raycast Extension

### ISSUE THREAD

**Issue by apotenza92** [alienator88/Pearcleaner#111]
[Raycast](https://www.raycast.com/) store extension to uninstall an app using Pearcleaner.

**Comment by alienator88** [comment]
Hi there, unfortunately this is not something I would be interested in to do from my end for a few reasons:
1. It would require me to start/maintain an external dependency outside of Pearcleaner that depends on another app
2. Looks like raycast extensions have to be coded in typescript, I'm only focusing on Swift currently
3. Raycast already has a built-in app uninstaller without the need for an extension. I'd be duplicating a lot of the same work.

If someone wants to build it for Pearcleaner, I'm all for it but it's a bit out of scope for my plans currently.
