### ISSUE TITLE
[BUG] List scroll stutter (Sequoia specific?)

### ISSUE THREAD

**Issue by mightysashiman** [alienator88/Pearcleaner#112]
**Describe the bug:** <br>
Scrolling through apps stutters and give the app an overall perfectible UX. I do not remember it happening in MacOS Sonoma.
However, scrolling through the list (on the right) of removable candidates of a selected app does NOT stutter.

**Steps to reproduce:**
1. Open app
2. Let it refresh apps, check permissions, check for updates until it settles idle
3. try scrolling throught the apps list on the left
4. see scrolling stutters (as if it was low FPS)

**Expected behavior** <br>
Scrolling through apps should be as smooth as anywhere else in MacOS

**Info:**
 - OS: 15.0 (Sequoia)
 - Pearcleaner Version: 3.8.7
 - HW: MBP 14" M3 Max (Power profile: automatic)

**Comment by alienator88** [comment]
I'm on Sequoia and not seeing this behavior. 
How many apps do you have to load on app startup?
Also, does it still stutter if you disable the animations in Settings > Interface?

**Comment by mightysashiman** [comment]
> I'm on Sequoia and not seeing this behavior. How many apps do you have to load on app startup? Also, does it still stutter if you disable the animations in Settings > Interface?

30 apps (it's a brand new set up, I normally have many more)
Disabling animations doesn't change anything.
here is a video if my issue wasn't clear enough: https://drive.proton.me/urls/H0ENS68GH0#Cu3sJuDcHyPc

**Comment by alienator88** [comment]
Ooo..you just caught a bug that's been wracking my brain for a while 😂 
Seeing your video made me think in a different way which helped.
So what happens on app launch is when each app in the list appears, it calculates it's size.
What I forgot to do is add a catch so it only runs once on load. So currently every time you scroll, it recalculates every app size again as it moves within the view.

Thanks for this. I'll work on a fix so it only runs once on app load.

**Comment by alienator88** [comment]
Could you try this test build for me?
Something to keep in mind, the sizes for each item in the app list gets calculated as it comes into view. So sitting and waiting a bit when the app loads won't just automatically calculate all sizes right away. This was done to lazy load the items for users who have hundreds of app.
[Pearcleaner.zip](https://github.com/user-attachments/files/17119319/Pearcleaner.zip)

**Comment by mightysashiman** [comment]
> Ooo..you just caught a bug that's been wracking my brain for a while 😂 Seeing your video made me think in a different way which helped. So what happens on app launch is when each app in the list appears, it calculates it's size. What I forgot to do is add a catch so it only runs once on load. So currently every time you scroll, it recalculates every app size again as it moves within the view.
> 
> Thanks for this. I'll work on a fix so it only runs once on app load.

LOL. It's actually quite surprising the list scroll was still working _at all_ . Just demonstrates the speed of the machine if it was polling all the info from each of the apps at each tiny scrolling increment haha.

As you mentionned in your second message, lazy computing in a separate thread these sizes and not impacting the list scroll smoothness is definitively the right way to go. Mind you, it's so quick for the current list of apps I have to be computed, I didn't actually see them gradually loading and it was damn near instantaneous. I'll have to try again when I install massive apps like Death Stranding or Adobe CS shit.

The test build solves the issue. Don't hesitate to contact me for further testing! Always happy to help a dev keep enhancing an already awesome app.

**Comment by alienator88** [comment]
Awesome, glad to hear it works better now.

And thanks!

**Comment by alienator88** [comment]
Closing issue, fix will be out in next release.
