### ISSUE TITLE
[APP] Directory is missing while uninstalling the Wins app.

### ISSUE THREAD

**Issue by homjay** [alienator88/Pearcleaner#114]
>NOTE: If a specific app is finding unrelated files or not finding expected files, use the new condition builder to either include or exclude files from the search. Push CMD+B when you're on an app's page to show the condition builder.

**Describe the app**

Wins is app

Wins is a window manager app that lets you split your screen by dragging a window to the edge.

**App Details**
1. Wins
2. 2.3
3. Website Download
4. Regular
5. ~Library/PreferencePanes/Wins.prefPane

**Desktop (please complete the following information):**
 - OS: 15.1 beta4
 - Pearcleaner App Mode: Regular
 - Pearcleaner Version: 3.8.6

**Screenshots**

Pearcleaner:

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/6718d044-c6a3-4633-8e6d-d60391a67f3a">

AppCleaner:

<img width="626" alt="image" src="https://github.com/user-attachments/assets/32cbfff9-310b-411a-a0ae-05f4006c93d3">

**Additional context**

The results are presented above. Notably, PearCleaner failed to locate the `Wins.prefPane` directory.

**Comment by alienator88** [comment]
Hey, nice catch!
I just realized I don't have the pane directory in the locations to search for at all: https://github.com/alienator88/Pearcleaner/blob/main/Pearcleaner/Logic/Locations.swift

I'll get this added in tomorrow 😄
