### ISSUE TITLE
[BUG] Automation Permission Not Showed

### ISSUE THREAD

**Issue by laduniestu** [alienator88/Pearcleaner#115]
**Describe the bug:** <br>
Can't find pear cleaner on automation permission setting

**Steps to reproduce:**
1. Fresh installation
2. Click "Check"
4. Click 'Open' on Automation
5. Will open Permission setting for automation
6. Pear Cleaner not showed

**Expected behavior** <br>

**Info:**
 - OS: Sequoia 15.0 (24A335)
 - Pearcleaner Version: 3.8.7

**Screenshots**
![Screenshot 2024-09-26 at 11 54 59](https://github.com/user-attachments/assets/6618b31f-7a29-4a21-95a7-357989951c25)

**Comment by alienator88** [comment]
I'll check on it tomorrow. It might be a Sequoia bug.

**Comment by alienator88** [comment]
As a workaround can you try opening an app in Pearcleaner and delete a file? Pearcleaner uses Finder to delete files so it should prompt for permission at that point.

**Comment by alienator88** [comment]
Hmm..I can't reproduce this issue.
I deleted Pearcleaner and it's gone from the Automation pane in settings.
As soon as I open Pearcleaner again, it pops back in the Automation page by itself after asking for Finder permission.

You can try resetting your Automation page back to defaults using this in Terminal: `tccutil reset AppleEvents`
Then open Pearcleaner and it should ask for Finder permission again. If it doesn't, I'm not sure what the issue is, I haven't seen anybody else report this and I can't reproduce it at all myself.

**Comment by JCKodel** [comment]
Same here. Just downloaded it, dragged into Applications folder, opened it, Automation is red, but no related automation is displayed:

<img width="1347" alt="image" src="https://github.com/user-attachments/assets/198d0caf-4e2a-4064-9026-c4d231cc83f5">

**Comment by alienator88** [comment]
So the Automation permission is what gives the Delete button it's power so to speak.
I suppose it makes sense that without the Automation permission, it won't work.
Let me check some other things on my end, what OS version are you on @JCKodel?

**Comment by JCKodel** [comment]
Sequoia 15.0

**Comment by alienator88** [comment]
So odd..none of this makes sense to me 😂 

I just wiped everything Pearcleaner related on my computer. It disappeared from Automation screen. 
![image](https://github.com/user-attachments/assets/3ce33f09-3b8c-4419-a92b-b2123dcc14d6)

I downloaded the latest version from Github, launched it and it just showed up automatically in there:
![image](https://github.com/user-attachments/assets/2785d27c-cc93-4b72-91cd-eff4ea582790)

One thing I noticed is that the app doesn't show in the list until the Settings window is completely closed and reopened. Going back a pane and then back into Automation doesn't pick up the new app changes.

**Comment by alienator88** [comment]
Does resetting the Automation database not help at all?
`tccutil reset AppleEvents`

**Comment by JCKodel** [comment]
I've deleted the app, then rebooted my computer. Reinstalling... please wait... 

Nop... still not there.

**Comment by JCKodel** [comment]
```
Successfully reset AppleEvents
```

<img width="1349" alt="image" src="https://github.com/user-attachments/assets/9b1b68b0-06a3-4de6-a30a-71587cbfbedd">

Now it fucked up my other apps >.<

**Comment by alienator88** [comment]
The other apps will be fine. When they need that permission again, it will pop back in the list.

**Comment by JCKodel** [comment]
That only set focus to Finder, nothing else. I mean: I'm seeing Terminal
menu bar, then I hit Enter, the menu bar says Finder.
No permission, popup or finder window appears.

**Comment by alienator88** [comment]
That behavior is expected, it was only supposed to focus Finder, not open a Finder window.
Do you have your Terminal listed in the Automation list now?

**Comment by alienator88** [comment]
All Pearcleaner does to request Finder automation permission is this:
https://github.com/alienator88/AlinFoundation/blob/16755c95c931ede5d011a9f05cca5434964c4edd/Sources/AlinFoundation/PermissionManager.swift#L119

Just gets the name of the home folder and that's it. When that is executed on app launch, it "should" be prompting for that Finder permission if it didn't have it granted in the past. I just can't reproduce your issue on my side.

**Comment by JCKodel** [comment]
Nop, only sh. I revoked sh permission and rerun the test, nothing happened.

**Comment by alienator88** [comment]
Do you have another terminal app like iTerm?
I just tried the default macOS Terminal and that one doesn't populate in the list, it might just have permissions by default since it's part of the OS.

**Comment by JCKodel** [comment]
Nop, but I did open VSCode terminal and tried from that, still nothing.

Installing warp terminal to check it...

Same thing. It focus on Finder and nothing else.

My automation list has only Find Any File, Rambox and sh

**Comment by alienator88** [comment]
I'm so out of ideas right now 😂 
So far I have tested on Sequoia, Sonoma and Ventura via some VMs I have setup for testing. 
Every single one of them popped up the permission request right when the app launched the first time.

**Comment by JCKodel** [comment]
I'm pretty sure is some Apple bug.

I was testing the iPhone mirroring (which doesn't work because this stupid bluetooth adapter will connect to literally everything, but my iPhone).

Then I tried to use the camera continuity. On Chrome, it doesn't work and asks me to open settings, but Chrome isn't there.

Trying the same on Safari triggers the permission box and the camera works:

<img width="489" alt="image" src="https://github.com/user-attachments/assets/4d320342-ba05-4d99-bb34-e3004b7d858d">

Sequoia is a mess =\

**Comment by alienator88** [comment]
It really is a mess right now. I had to update to it just so I can build the apps on the newer code, but I'm not liking all the weird glitches.

If you had time and really wanted to narrow it down, you could try downloading VirtualBuddy (free app) and install a Sonoma or Sequoia OS in the VM. Then try Pearcleaner in that VM. If it works there, it probably is some bugs from upgrading your OS, at that point a clean install could probably help 😭

**Comment by alienator88** [comment]
Also curious what results you get by listing the Automation services from the TCC database directly.
Can you run this in Terminal?
`sqlite3 ~/Library/Application\ Support/com.apple.TCC/TCC.db "SELECT client, auth_value, indirect_object_identifier FROM access WHERE service='kTCCServiceAppleEvents';"`

For example I get this output:
```
com.alienator88.FoundationTesting|2|com.apple.finder
com.alienator88.Pearcleaner|2|com.apple.finder
com.googlecode.iterm2|2|com.apple.finder
org.hammerspoon.Hammerspoon|2|com.apple.finder
```

All 4 of those apps have the access granted in the Settings window.
The value of `2` means granted but indirect, the app has access via another app, in this case `com.apple.finder`.

**Comment by JCKodel** [comment]
/bin/sh|2|com.apple.systemevents
com.rambox|2|com.apple.systemevents
org.tempel.findanyfile|2|com.apple.finder

**Comment by laduniestu** [comment]
com.apple.ScriptEditor.id.Untitled|2|com.apple.systemevents
com.microsoft.VSCode|2|com.google.Chrome
com.tinyapp.DBngin|2|com.apple.Terminal
de.beyondco.herd|2|com.googlecode.iterm2

**Comment by laduniestu** [comment]
This case is the same as my case when installing Microsoft Teams and Zoom Meeting. The camera and microphone permissions do not appear. Is there a possibility that my internal system is having problems?

**Comment by JCKodel** [comment]
Update:

I've deleted (formatted, erased) my MacOS disk and reinstalled MacOS from scratch.

Same behaviour: permissions don't appear =\

**Comment by alienator88** [comment]
> This case is the same as my case when installing Microsoft Teams and Zoom Meeting. The camera and microphone permissions do not appear. Is there a possibility that my internal system is having problems?

It's very likely a Sequoia issue at the moment. I've seen a lot of posts regarding sequoia issues all over reddit and apple developer forums. There's a huge megathread with tons of currently reported issues: https://www.reddit.com/r/MacOS/comments/1fihlge/macos_15_sequoia_bugs_and_issues_megathread/

It's pretty odd that I can't reproduce this at all on like 3 different systems.
Out of curiosity, what mac computer do you guys have? I'm running all my tests and VMs on M1 Pro.

**Comment by JCKodel** [comment]
> Out of curiosity, what mac computer do you guys have?

A Hackintosh i7 6700-K, 128Gb RAM.

**Comment by laduniestu** [comment]
M2 Pro 16Gb RAM

**Comment by alienator88** [comment]
We might need to wait until 15.1 release of sequoia to see if Apple get their shit together. The 15.0 release is a bug fest.

**Comment by laduniestu** [comment]
![Screenshot 2024-10-04 at 16 17 58](https://github.com/user-attachments/assets/88253fe3-5480-4bd0-83a6-ab7d973256e3)
I have already reinstall my OS Sequoia and its work right now.
So, the problem is in the OS, but i dont know where 🤣

**Comment by alienator88** [comment]
That's good to hear!
I'm hoping Sequoia 15.1 release will fix all these weird glitches. 🤞

**Comment by alienator88** [comment]
Ahhh, good to know. SIP is something I didn't even think of as affecting this.
I'm curious if others who have experienced this have also disabled SIP.
Thank you for the information @radge!
