### ISSUE TITLE
Provide CLI tools inside the application so I don't have to install them

### ISSUE THREAD

**Issue by alkene0005** [alienator88/Pearcleaner#117]
e.g.
/Applications/Pearcleaner.app/Contents/pearcleaner --list
/Applications/Hammerspoon.app/Contents/Frameworks/hs/hs

**Comment by alienator88** [comment]
Are you asking for me to build a CLI only binary that can run independently from the Pearcleaner app?
Currently the CLI is built into the main app so it has to be executed from:
`/Applications/Pearcleaner.app/Contents/MacOS/Pearcleaner`

**Comment by alkene0005** [comment]
Good!
