### ISSUE TITLE
[FR] Search field above app list

### ISSUE THREAD

**Issue by mightysashiman** [alienator88/Pearcleaner#119]
**Is your feature request related to a problem? Please describe.**
Commonly admitted modern design language in the vast majority of UIs (webpages, native MacOS (and other OS's) apps) is to have the search field above the results content list, especially if that search field acts as a real-time filter for the list. Currently, the app has its search field below the app list.

**Describe the solution you'd like**
Search field above app list

I suppose some users (dev included 😘) prefer having the search below. Therefore, please allow the user to freely choose between search bar being **above**/**below** app list thanks to an additional toggle within the app's settings>interface pane.

**Describe alternatives you've considered**
Keep on using the app as is. Not critical, but it would be definitively a quality of life improvement.

**Additional context**
N/A

Thanks in advance ! Best regards.

**Comment by alienator88** [comment]
So I actually used to have the search bar on top a while back, I can't remember why I moved it down now..I'm pretty sure there was a reason.
Here's what it looks like on top:
![image](https://github.com/user-attachments/assets/1968025a-186b-4f5c-b362-c7a0bfc060c6)

One thing I don't like is the refresh/menu buttons in the search bar. I want to do something about those. Still keep them visible but different layout maybe. Any ideas?

**Comment by alienator88** [comment]
It might have been that and I just didn't like how the window controls at the top left looked right above the search bar. 
I'm trying to see how the badges look at the bottom, what do you think?
![image](https://github.com/user-attachments/assets/497b4957-426d-49bf-a511-314cded72431)

**Comment by mightysashiman** [comment]
> yeah I remember it too. And at some point, I noticed it just dropped to the bottom >_<. Was it because you added these update and permission checks notifications maybe?

Yeah I agree.
Actually I may have a couple of suggestions regarding the controls sitting in the search bar and the search bar as a whole (and actually a small redesign of the the app's UI to make it more logical imho). I'll make a quick mockup to explain and post it here. gimme a couple minutes :)

**Comment by alienator88** [comment]
Sounds good!

**Comment by mightysashiman** [comment]
would you happen to be available for a text chat on discord? it'll be easier to discuss ideas. wouldn't want to pollute your issue tracker here.

**Comment by alienator88** [comment]
How much longer are you free for? (Not sure on your timezone)
I'm currently at work and going to run to lunch for an hour or so. But I can after that.

**Comment by mightysashiman** [comment]
> How much longer are you free for? (Not sure on your timezone) I'm currently at work and going to run to lunch for an hour or so. But I can after that.

it's approaching 22:00 here (Switzerland) but in no rush to go to bed. Ping me when you're back (@mightysashiman)

**Comment by alienator88** [comment]
Changed this in latest release, closing issue.

**Comment by mightysashiman** [comment]
thanks so much!
