### ISSUE TITLE
Uninstalling Outlook

### ISSUE THREAD

**Issue by Svec-Tomas** [alienator88/Pearcleaner#12]
https://dropover.cloud/83a523

I believe PearCleaner is not uninstalling all the files when I try to remove Microsoft Outlook from my Mac. I believe it leaves behind all the data from downloaded emails.

I hope this can be fixed.

Thanks for this app!

**Comment by alienator88** [comment]
Hey there, thanks for the report!

Could you let me know what file paths AppCleaner is finding to total up to 36gb of space?
I don't have Outlook and can't easily test that. 
Maybe do another video or screenshots and scroll down the file list in AppCleaner so I can see them all.

Thank you!

**Comment by Svec-Tomas** [comment]
<img width="550" alt="Snímka obrazovky 2024-01-22 o 20 21 58" src="https://github.com/alienator88/Pearcleaner/assets/138758322/d31d7053-4b11-4348-b473-207fafca7ef9">

**Comment by alienator88** [comment]
Thanks, that helps!
I'll need to add a new function in the search that checks the teamid for group containers. That way it should find everything based on the `UBF8T346G9` id.
I'll get something out for this in the next update.

**Comment by alienator88** [comment]
Pushed out v2.3, hopefully this resolves the issue for you!

**Comment by Svec-Tomas** [comment]
Now it looks good to me! PearCleaner is detecting those files as well. Thanks for the fix!
