### ISSUE TITLE
[FR] Add Automated Cache Cleanup for Development Environments on macOS

### ISSUE THREAD

**Issue by izzalDev** [alienator88/Pearcleaner#121]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when old caches and temporary files take up unnecessary space on my development environment, slowing down my workflow. Manual cache cleanup is tedious, and it's hard to keep track of which caches are safe to delete without causing issues in active projects.

### Describe the solution you'd like

I would like an automated tool that scans and cleans up developer-related caches on macOS. This tool should be able to identify unnecessary or outdated cache files from common development environments such as Xcode, Gradle, npm, Flutter, and others, providing options for selective cleanup based on the development tool in use.

### Describe alternatives you've considered

I’ve considered manually deleting cache files or using general system cleanup tools, but they often miss development-specific files or delete crucial ones by mistake. Another option is using individual commands for each tool (e.g., `flutter clean`, `gradle clean`), but this lacks centralization and convenience.

### Additional context

It would be helpful to have a user-friendly interface or command-line option to specify which development environments to clean up (e.g., Flutter, npm, etc.). Additionally, an optional preview mode that shows the size of caches to be deleted before proceeding would add more control for the developer.

**Comment by alienator88** [comment]
This could fit in with another feature I'm working on. I was going to have a cleaner for Xcode, but could expand on that for other IDEs and languages. 
I would just need to know what folders each needs to clean since I'm not super familiar with the others.

**Comment by alienator88** [comment]
Are you familiar with what folders/files need to be deleted for the example tools you mentioned?

**Comment by izzalDev** [comment]
Yes, I can help with that! Here are some common cache/temporary directories for the tools I mentioned:

- **Gradle cache**: `~/.gradle/caches/`
- **Gradle wrapper**: `~/.gradle/wrapper/`
- **npm cache**: `~/.npm/`
- **Pub (Dart/Flutter)**: `~/.pub-cache/`
- **Conda environments list**: `~/.conda/environments.txt`
- **Poetry cache**: `~/Library/Caches/pypoetry/`

Alternatively, you can make your code modular for developer tools, and I can help guide you through the process.

**Comment by alienator88** [comment]
This is helpful!
I was thinking of adding a new page to the app, maybe call it Development or something like that. Then have a drop down selector where you can choose the dev environment type, say Flutter and list the cache/file directories for that specific environment to clean.

If you have any ideas on what might work better, I'm open to hearing anything you have.
