### ISSUE TITLE
[BUG] Close after uninstall doesn't seem to work

### ISSUE THREAD

**Issue by SuperLeiyan** [alienator88/Pearcleaner#124]
**Describe the bug:** <br>
I use this Alfred workflow to uninstall apps with Pearcleaner: [https://github.com/andylundqvist/alfred-pearcleaner](url) and I have Close after uninstall enabled, but for whatever reason Pearcleaner's window remains open, same with uninstall apps with conventional methods like dragging into the Bin.

**Info:**
 - OS: Sonoma 14.6.1
 - Pearcleaner Version: 3.9.1

**Console Logs (For app crashes):**
[log.txt](https://github.com/user-attachments/files/17359184/log.txt)

**Screenshots**
![image](https://github.com/user-attachments/assets/1dc3107c-3048-4f97-b71c-a2c0a4099ea8)
![image](https://github.com/user-attachments/assets/1a30d5b5-9159-400d-a6fb-12e4c999a930)

**Comment by alienator88** [comment]
Thanks, I'll look into it!

**Comment by alienator88** [comment]
Got this fixed, will be out in the next release.
Thanks for the heads up!

**Comment by SuperLeiyan** [comment]
Thanks looking forward to the next release.
