### ISSUE TITLE
[BUG] App fails to locate hidden folders like ~/.app_name

### ISSUE THREAD

**Issue by alexey-zaharchenko** [alienator88/Pearcleaner#125]
**Describe the bug:**  
I attempted to delete the app https://ollama.com, but the app failed to locate the `~/.ollama` folder. I understand that it may not always be possible to find that type app-related folders, but I hope  might have some ideas to handle cases like this.

**Steps to reproduce:**
1. Search for the app Ollama in Pearcleaner.
2. Attempt to delete the app and its associated files.
3. Notice that the `~/.ollama` folder is not found.

**Expected behavior**  
I expected Pearcleaner to locate and suggest deletion of the `~/.ollama` folder, which might still contain orphaned files related to the app.

**Info:**
- OS: 14.6.1 (23G93)
- Pearcleaner Version: 3.9.1

P.S. Thanks for the "Orphaned file search" mode—it’s a great feature!

**Comment by alienator88** [comment]
Thanks, I'll look into it!

**Comment by alienator88** [comment]
So something strange..I had a ticket for this already it seems 😂 https://github.com/alienator88/Pearcleaner/issues/66
I made a change there to allow searching the home directory, but for some reason in another release after that, it seems I commented it out: https://github.com/alienator88/Pearcleaner/blob/aa31606d766d8d19c428291f83b1e7e72d68df74/Pearcleaner/Logic/Locations.swift#L29

I'll look into why I disabled it, I think it caused some other random issue when it was searching in the home folder. 
I will update you on what I find.

**Comment by imingx** [comment]
Searching the user folder may unintentionally delete user files or folders (these files may have the same name as the application, but the user does not want to delete them). You can search only hidden files in the user’s root directory, but the user should be warned before deletion.

**Comment by alienator88** [comment]
The user should verify all files found for deletion before actually deleting. This could apply to any folder location, not really restricted to user folder only. 
Deleting all found files without confirming what's in the list is not recommended. These type of cleaner apps cannot be 100% foolproof unfortunately.
There's also a setting you can enable in the General tab which will show an alert when you click the delete button to prevent accidental deletions.
