### ISSUE TITLE
[BUG] Permission Accessibility not recognised 

### ISSUE THREAD

**Issue by phhoef** [alienator88/Pearcleaner#127]
**Describe the bug:** <br>
The permission for accessibility seems not to be granted, though in setting it is enabled.
Not sure what functionality is bound to this permission, but it seems that all is working fine.

**Expected behavior** <br>
Permission status in Pearcleaner should be all green.

**Info:**
 - OS: 15.0.1
 - Pearcleaner Version: 3.9.1

<img width="1012" alt="image" src="https://github.com/user-attachments/assets/7adb927b-9086-4728-a1c6-7a99fbff0592">
<img width="556" alt="image" src="https://github.com/user-attachments/assets/538dab7c-e3db-45d4-9741-935a4246a3ae">

**Comment by alienator88** [comment]
There's been a lot of permissions related issues in Sequoia in general, not even just my app.
Can you try fully removing the app from the list and adding it back again?
![Screenshot 2024-10-18 at 10 29 49 AM](https://github.com/user-attachments/assets/91d3a375-b158-425e-bee5-37ad2ac422c3)

**Comment by phhoef** [comment]
thanks 👍 after removing and enabling again, the permission is properly recognised ...
