### ISSUE TITLE
[BUG] Auto-update not working

### ISSUE THREAD

**Issue by Svec-Tomas** [alienator88/Pearcleaner#135]
### Describe the bug:
I have the same issue on my Mac mini M1 and also MacBook Pro 14 M1 Pro, both running Sequoia 15.0.1 and PearCleaner 3.9.1

Before the update process went to 100% and updated succesfully. Now tried on both machines, on both it is stuck at 50%.

Please see attached video.

https://github.com/user-attachments/assets/a8134c2a-5e54-4327-8f63-20a66b25a66b

**Comment by alienator88** [comment]
I should(hopefully) already have a fix in place for this in v3.9.2.
There should be the new version downloaded into your Downloads folder still even though it got stuck at 50%. You can just move that new version to the `/Applications` folder to overwrite the older v3.9.1.
It's a permissions issue with where the file is placed from the looks of it.
