### ISSUE TITLE
[BUG] Sentinal Monitor not working!

### ISSUE THREAD

**Issue by ishaanrathodd** [alienator88/Pearcleaner#14]
**Describe the bug**

Pearcleaner never detects an app when its uninstalled in the background!

**To Reproduce**
Just delete an app from applications folder

**Expected behavior**

It should detect the app being deleted, pop up a mini window with all files attached to the app and should give an option to delete them too like in appcleaner

**Desktop:**
 - OS: 14.3
 - Pearcleaner Version: 2.3

**Comment by alienator88** [comment]
Hi, is this happening even if you enable sentinel monitor in the Pearcleaner settings? It’s not on by default.
If it still doesn’t work with it enabled, I’ll need to look into it and reproduce the bug.
Let me know.

**Comment by ishaanrathodd** [comment]
Yes it is happening with the sentinel monitor on!

**Comment by alienator88** [comment]
Thanks, I’ll take a look at it tomorrow

**Comment by alienator88** [comment]
I attempted to repro this issue and can't seem to be able to. As you can see in the video, I have the sentinel monitor process running in activity monitor, the app is closed, I delete the battery toolkit app and Pearcleaner launches and finds the files. Then clicking uninstall sends everything to the trash as expected.

https://github.com/alienator88/Pearcleaner/assets/6263626/e75ac99e-1e23-4a6e-98ef-1edc632e2861

Just to confirm, you have the Full Disk Access and Accessibility permissions enabled?
Also, if you run this in your Terminal, does it output a process?
`launchctl list | grep com.alienator88.Pearcleaner`

I had another bug from one other user a while back for similar issues as yours but could never reproduce so it seems there was something environmental to the OS. Nobody else is reporting this issue as far as I can tell.

**Comment by alienator88** [comment]
Something else to try is to load the sentinel monitor via launchctl manually from Terminal and see if it spits out any errors. That's all Pearcleaner does behind the scenes. The following assumes you have Pearcleaner installed in your /Applications directory:

Download the attached txt file first and remove the .txt extension so it's a plist file. Github won't allow to attach .plist files.
[com.alienator88.PearcleanerSentinel.plist.txt](https://github.com/alienator88/Pearcleaner/files/14041492/com.alienator88.PearcleanerSentinel.plist.txt)

Once you have that in your Downloads folder named `com.alienator88.PearcleanerSentinel.plist`, run the following in the Terminal to load Sentinel manually:
`/bin/launchctl load -w ~/Downloads/com.alienator88.PearcleanerSentinel.plist
`
See if you get any errors in the terminal from this command.

And this to unload it after testing:
`/bin/launchctl unload -w ~/Downloads/com.alienator88.PearcleanerSentinel.plist
`
