### ISSUE TITLE
[Zen Browser] Unexpected Data Loss in Zen Browser During Orphaned Files Cleanup

### ISSUE THREAD

**Issue by WindWash** [alienator88/Pearcleaner#143]
Hello,

I recently encountered an issue where the process of cleaning up orphaned files unexpectedly resulted in the deletion of Zen Browser's data, causing the browser to reset to its initial state. This incident led to loss of all settings, bookmarks, and saved information within the browser.

[Zen Browser](https://github.com/zen-browser/desktop)

Could you please investigate this issue? Your assistance would be greatly appreciated.

Thank you!

![截屏2024-10-31 11 56 47](https://github.com/user-attachments/assets/3f8dc5c4-e763-4a82-8b8f-bef35616b1d6)

**Comment by alienator88** [comment]
Hi, there's a big warning popup that comes up the very first time you open the Orphan files view that warns against this and kind of explains how it works. Did you happen to see it?
This search is not 100% accurate. It's the users responsibility to mark the items found for deletion and make sure they are not part of a current app. It's not meant to be a select all and delete in one click feature.

This issue has come up a few times before. I'm not sure why nobody reads the big warning that has to be clicked through to proceed 😂 

If the warning popup is broken and never came up for you, let me know and I'll look into it.

**Comment by WindWash** [comment]
Yes, I understand your point, and I'm aware that the information obtained through search isn't always 100% accurate.

However, for those of us who aren't technically inclined, this is not very helpful. We often can't determine which files are important and which aren't.

You've also mentioned that similar incidents have occurred multiple times. I wonder if there are ways to minimize or prevent these occurrences.

For instance:

1. File Organization and Visualization: Could we consider organizing files associated with different software together and displaying them with the software's icon? Icons are generally more intuitive than file names. A UI similar to the uninstallation interface could help users identify which files belong to which software. Furthermore, a confirmation dialog could prompt users to ensure the software is uninstalled or no longer needed before deletion.
2. Recycling Bin Feature: Introducing a recycle bin could allow users to restore individual software/data files or all files after accidental deletion. This bin could automatically clear files after a period, say seven days, for files with no objections.

This approach could help users have a clearer understanding of the files and also provide a fallback in case of accidental deletions.

Finally, I admit that I am not a technical expert, so I don't know the feasibility or complexity of these ideas. These are merely personal thoughts and suggestions. If they inspire any improvements, I'm glad. If anything I've mentioned seems inappropriate, I apologize.

**Comment by alienator88** [comment]
So here's the general issue with some of these apps that get their data caught up in the orphan file search even though they are currently installed apps.
Orphan file search excludes files and folders that match a currently installed app name or bundle identifier. 

Unfortunately, some developers name their cache/config folders differently than the app name so Pearcleaner can't find them to exclude from the search.

Example: Zen Browser is the app name but the cache folders are named "zen" only. My app has no way of knowing these are related. It would require human intervention at this point. 

Only way I could add some type of catch for this is if I search for portions of the app name, like just search "zen". But that could exclude a lot of files that are actually valid. So I made the decision to only search on the full app name.

By the way, Pearcleaner uses Finder to delete the files. So after you delete files, you can open Finder and do CMD+Z and it will undo all those files getting deleted. So I suppose technically there is a recycle bin function.

You can also right click a file in the list and exclude it from the search so it stops showing up.

Side note, this here isn't directed at you specifically, but for any others who come across this issue in the future:

If you are not very familiar with what files match what apps, the safe route is ALWAYS to leave a file alone if you don't know what it belongs to.

**Comment by ezeeyahoo** [comment]
renamed it to Zen and changed in the config too but still showing up

<img width="892" height="80" alt="Image" src="https://github.com/user-attachments/assets/24ecf9f2-e709-4a0d-8275-550923ed9074" />
