### ISSUE TITLE
[BUG] Orphaned select and delete all files not working

### ISSUE THREAD

**Issue by Allmight97** [alienator88/Pearcleaner#146]
### Describe the bug:
When I manually select one or more orphaned files I can delete them all with the red delete button. But when I use the select all tick box at the top of the column, it correctly selects all and the red delete shows the total size being removed, but pressing delete does nothing. No prompt, nothing.

### Steps to reproduce:
See description.
   

### Expected behavior:
All orphaned files selected with the select all tick box should be removed.

### Info:
 - OS: MacOS 15.2 dev beta 2
 - Pearcleaner Version: 3.9.3

### Screenshots:
N/A

### Console Logs (For app crashes or hard to reproduce issues):
N/A

**Comment by alienator88** [comment]
It's likely a file it's trying to delete is maybe locked or in use. 
The logic on the delete button is to stop if it encounters anything funky like that.

Try running this in terminal and try to reproduce the issue. It should hopefully spit out some errors on why it stopped:

`log stream --level debug --style compact --predicate 'subsystem == "com.alienator88.Pearcleaner"'`

**Comment by alienator88** [comment]
While you're at it, can you try this debug version I was working on? It has some fixes for the orphan file logic in there.
[Pearcleaner.zip](https://github.com/user-attachments/files/17685300/Pearcleaner.zip)

**Comment by alienator88** [comment]
Closing this out, fix will be out in next release.
