### ISSUE TITLE
[BUG] Untranslated strings

### ISSUE THREAD

**Issue by Svec-Tomas** [alienator88/Pearcleaner#147]
![CleanShot 2024-11-11 at 23 47 04@2x](https://github.com/user-attachments/assets/acecb12c-fbea-4e13-a523-1298a03f2627)

These 2 strings (Cancel and Okay) seems to be not available for translation.

It happens in this view, when clicking the Remove Red button.

Rest of the app seems to be all translated to Slovak.

**Comment by alienator88** [comment]
Turns out that the custom alert I'm using there didn't have those strings localized.
I pushed the changes to the repo, Cancel and Okay should be available to translate now.
There's also a few more keywords available to translate for some upcoming changes in the app.
Can you add the changes to this xcloc file?
[sk.xcloc.zip](https://github.com/user-attachments/files/17719626/sk.xcloc.zip)

**Comment by alienator88** [comment]
Also for future reference, any translation related questions/issues, you can post in the discussion here: https://github.com/alienator88/Pearcleaner/discussions/137
No need to open new bug issues for each one.

**Comment by Svec-Tomas** [comment]
**FinderOpen** - is this supposed to be translated?
Pearcleaner needs to send **Apple Events** to Finder to delete files - what are "Apple Events" in this string, please?
So I can translate it then correctly. Thanks in advance!

**Comment by alienator88** [comment]
No, you can ignore all those info.plist translations. Just the main pearcleaner strings is good.
When I export the xcloc file, it automatically adds those too.

**Comment by Svec-Tomas** [comment]
> Pearcleaner needs to send **Apple Events** to Finder to delete files - what are "Apple Events" in this string, please?
> So I can translate it then correctly. Thanks in advance!

I would need your help, please.

**Comment by alienator88** [comment]
Help with what?

**Comment by Svec-Tomas** [comment]
I have asked a question, need help to translate correctly this string:

**Pearcleaner needs to send Apple Events to Finder to delete files**

What are "Apple Events" in this string, please?

**Comment by alienator88** [comment]
You don't have to translate that string. It comes from the InfoPlist file.
We only need the translations done on the Localizable.xcstrings file here:
![image](https://github.com/user-attachments/assets/d7004f96-e06c-448d-9bbe-3de88e1bd24a)
The InfoPlist.xcstrings files don't need to be translated.
If you were still curious though, Apple Events refers to the apple events permission here: https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_automation_apple-events

**Comment by Svec-Tomas** [comment]
OK, then please find attached the file with translation.

[sk.xcloc.zip](https://github.com/user-attachments/files/17723132/sk.xcloc.zip)

**Comment by alienator88** [comment]
Looks good, 100% translated now!
Will have these updates out in the next version.
Thank you!
