### ISSUE TITLE
[BUG] Sentinel Monitor not working after reboot the machine

### ISSUE THREAD

**Issue by HuaDeity** [alienator88/Pearcleaner#148]
### Describe the bug:
After a machine reboot, the Sentinel Monitor function fails to work. To restore functionality, I must manually navigate to the settings and reopen the Sentinel Monitor.

### Steps to reproduce:
1. Go to 'General Settings'
2. Open Sentinel Monitor
3. Reboot the machine
4. Delete an app by moving it to the Trash
   

### Expected behavior:
Pearcleaner should display a popup with an app page for deletion.

### Info:
 - OS: 15.2
 - Pearcleaner Version: 3.9.3

**Comment by alienator88** [comment]
I got this fixed. I think Sequoia updates broke the logic I had before so I had to adjust it slightly.
Will be out in the next release, thanks!
