### ISSUE TITLE
[FR] Add support for slimming Universal apps

### ISSUE THREAD

**Issue by iLynxcat** [alienator88/Pearcleaner#149]
**Is your feature request related to a problem? Please describe.**

This would just be a nice-to-have feature. I’d like to be able to maximize my storage space by trimming the other architecture's instructions out of Universal apps.

**Describe the solution you'd like**

I would love to see the ability to remove alternate architectures from Universal binaries (i.e. I’m on an arm64 Mac, trim out the x86_64 instructions).

**Describe alternatives you've considered**

This is doable manually via `lipo`, which wouldn’t be great to include in this app if you’re not a developer (#72), but I’ve seen it in CleanMyMac X — an app I don’t like because it feels like bloatware but seeing it on a friend’s Mac it was a good feature.

An easy implementation of this might be to only display the option if `lipo` is already installed on the system. Not sure if that silent fragmentation is the best idea for the user experience though.

**Additional context**

This absolutely might be out of scope for Pearcleaner but the interface of this app is delightful and promising, and I’ve just switched from AppCleaner since this is much better maintained. Feel free to close this issue if it is out of scope!

**Comment by alienator88** [comment]
Hey there, thank you for the request!

So funny enough, I actually looked into this when that #72 issue was submitted as I was researching what else lipo could do.
I sort of came to the conclusion that I didn't want to deal with having to handle code signing issues of some apps that get slimmed. From what I read online, some apps can run into signing issues after they are altered and unless the user opened the app first to Cache the authorization, it would break.

That and probably does go a bit out of scope for this app. I didn't necessarily want to bloat it up with a ton of utilities, just do one or two things really well.

When I was looking into this though, I did find this app and is also open source: https://github.com/Oct4Pie/archify
