### ISSUE TITLE
[BUG] Need to click uninstall twice for changes to take effect

### ISSUE THREAD

**Issue by ishaanrathodd** [alienator88/Pearcleaner#15]
**Describe the bug**

While uninstalling an app from pearcleaner, you need to press uninstall twice to uninstall that app. For example, while pressing uninstall for the first time, the app disappears from pearcleaner but then reappears and u need to click uninstall again for it to finally delete.

**To Reproduce**
Happens 90% of the time when u uninstall the app from pearcleaner.

**Desktop (please complete the following information):**
 - OS: 14.3
 - Pearcleaner App Mode: Regular/Mini
 - Pearcleaner Version: 2.3

**Comment by alienator88** [comment]
Can I get a video of this?
I can't reproduce this one either. I believe the bulk of the issues you submitted are probably caused by the same problem likely linked to your OS config someplace. I've never had to click Uninstall twice to get rid of an app ever since I put this together.
