### ISSUE TITLE
[BUG] Drag&Drop doesn't work when dropped from Marta file manager

### ISSUE THREAD

**Issue by eugenesvk** [alienator88/Pearcleaner#151]
### Describe the bug:

When drag&droping a folder from the Marta file manager, it doesn't appear in the list

### Steps to reproduce:
1. Go to any path in Marta
2. Drag a folder to Pearcleaner's Folders
3. See error
   

### Expected behavior:
Drag&drop works as with other apps (and it works with other apps I'm drag&dropping from Marta, so not sure it's a Marta bug)

### Info:
 - OS: 13.4
 - Pearcleaner Version: 3.9.3

### Screenshots:
https://github.com/user-attachments/assets/20e218d0-b497-444e-aec8-32dfa5da5151

### Console Logs (For app crashes or hard to reproduce issues):
not a crash

**Comment by alienator88** [comment]
Thanks for this, I found the issue and what was causing it.
Fix will be out in next release of Pearcleaner :)
