### ISSUE TITLE
[FR] Option to auto run brew uninstall <app> in the background upon removing an app using Pearcleaner

### ISSUE THREAD

**Issue by Risinggoblin** [alienator88/Pearcleaner#154]
**Is your feature request related to a problem? Please describe.**

When removing an application installed via Homebrew using Pearcleaner, Homebrew is not updated to reflect this action. This can cause discrepancies where Homebrew continues to list the app as installed, potentially leading to issues during updates or re-installations.

**Describe the solution you’d like**

It would be great if Pearcleaner could detect whether an application was installed via Homebrew and execute the `brew uninstall <app>` command in the background when the app is removed. This would ensure Homebrew’s local package database remains accurate and up-to-date, eliminating the need for manually running `brew uninstall <app>`

**Describe alternatives you’ve considered**
	•	Manually running `brew uninstall <app>` after using Pearcleaner to remove an application.

**Additional context**

Pearcleaner could include a pre-check to confirm whether the app is listed in Homebrew before executing the command. Additionally, this can be an optional setting which can be toggled on or off based on user preference

**Comment by alienator88** [comment]
Out of curiosity, does the brew cleanup function not work for you?

![Screenshot 2024-11-19 at 11 58 52 AM](https://github.com/user-attachments/assets/00b4a5b6-0e34-423e-8084-f776c35bc8e5)

**Comment by Risinggoblin** [comment]
This was my bad, apologies. I had missed the "allow terminal acess" MacOS pop-up. Once I allow, this works well. Apologies again

**Comment by alienator88** [comment]
No worries, glad it works now :)

**Comment by L1cardo** [comment]
There is not "allow terminal acess" MacOS pop-up on my Mac, and I can not find any option to turn it on.

**Comment by alienator88** [comment]
There shouldn't be a terminal access permission under Automation settings page. It should only have Finder and System Events. The app uses apple script to tell terminal to launch indirectly.
![image](https://github.com/user-attachments/assets/25698e11-1e72-43ab-844c-c9c8fea6c6a8)

**Comment by L1cardo** [comment]
![image](https://github.com/user-attachments/assets/500fa67f-f837-413b-ab81-74fba875c129)
Somehow it shows terminal access now, but it does not run terminal automatically to do the brew uninstall

**Comment by alienator88** [comment]
Can you run this in a separate Terminal window:
```
log stream --level debug --style compact --predicate 'subsystem == "com.alienator88.Pearcleaner"'
```

Then attempt to uninstall an app that is also installed via homebrew. See if it spits out any errors in the terminal window.

**Comment by L1cardo** [comment]
![image](https://github.com/user-attachments/assets/5f5ee1fb-4133-4e57-8120-aec0644a7dfd)
Nothing special.
That Matlab app is not what I was trying to uninstall

**Comment by alienator88** [comment]
That's odd..what app are you trying to remove?
Can you show me a screenshot of it and the files it finds for it?

**Comment by L1cardo** [comment]
> That's odd..what app are you trying to remove? Can you show me a screenshot of it and the files it finds for it?

https://github.com/mangerlahn/Latest

![image](https://github.com/user-attachments/assets/4dac9ac5-2eda-4d9b-b06f-937c9bbde310)

**Comment by alienator88** [comment]
Hmm..I can't reproduce the issue.
I installed Latest from homebrew, opened it and clicked around a bit to generate some cache files.
Then I uninstalled from Pearcleaner and the Terminal popped up and ran through the cleanup process..
I ran it in debug mode in Xcode and got absolutely zero errors, so it might be something environmental to your OS regarding permissions. I'm also on 15.1.1 Sequoia so not exactly sure what's going on.

**Comment by L1cardo** [comment]
> Hmm..I can't reproduce the issue. I installed Latest from homebrew, opened it and clicked around a bit to generate some cache files. Then I uninstalled from Pearcleaner and the Terminal popped up and ran through the cleanup process.. I ran it in debug mode in Xcode and got absolutely zero errors, so it might be something environmental to your OS regarding permissions. I'm also on 15.1.1 Sequoia so not exactly sure what's going on.

Can you trigger some command to let it access `System Events` ?

**Comment by alienator88** [comment]
So Pearcleaner checks permissions on launch. It executes an apple script command to request system events.

This other user had a similar issue and theirs was resolved after reinstalling the OS. I think just strange Sequoia problems: 
https://github.com/alienator88/Pearcleaner/issues/115#issuecomment-2393120444

**Comment by L1cardo** [comment]
Below is the app that I developed, it also uses AppleScript, it can successfully trigger `System Events`, I may have to take a look when I get some time.
https://github.com/Bigwig-Club/Account-Switcher

**Comment by alienator88** [comment]
I looked more into this and I don't think the System Events permission is an issue here.

I use System Events for the Cmd+Z function when you delete files to undo the deletion via Finder. Maybe you haven't used it yet to have it ask for that permission:
https://github.com/alienator88/Pearcleaner/blob/8ed2de96be381a76e68f1f7f60083b2b153521d7/Pearcleaner/Logic/Logic.swift#L275

This is where I use Terminal to run the cleanup task:
https://github.com/alienator88/Pearcleaner/blob/8ed2de96be381a76e68f1f7f60083b2b153521d7/Pearcleaner/Logic/Logic.swift#L539

**Comment by L1cardo** [comment]
Yeah, it now has system events permissions after I pressed CMD + Z, but still no terminal pops up to do brew uninstall command

**Comment by alienator88** [comment]
I'll make a custom build for you tomorrow with a button to trigger a simple Terminal command via AppleScript. I'll have it print logs with debugging to see if it's an issue with the command or something else.

**Comment by L1cardo** [comment]
> I'll make a custom build for you tomorrow with a button to trigger a simple Terminal command via AppleScript. I'll have it print logs with debugging to see if it's an issue with the command or something else.
> 

No hurry, take your time and big thanks!

**Comment by alienator88** [comment]
Something I'm curious about to see if it's an issue with Pearcleaner or something else, let's try automating terminal outside of my app.
Open Script Editor on your Mac and run this:

```
tell application "Terminal"
    activate
    do script "echo 'Test'"
end tell
```

Does the Terminal window open?

**Comment by alienator88** [comment]
Cool, I'll follow up tomorrow

**Comment by L1cardo** [comment]
OK, I now fully understand what is causing the issue, and it is nothing to do with your test build.

If the `close after uninstall` option is on, the auto brew uninstall command won't execute.
![image](https://github.com/user-attachments/assets/2dfd202e-cf3e-4ec5-affe-945dcf2b03ac)

Also I have found some other bugs:
1. `CLI support` can't be enabled, and here is the error log
![image](https://github.com/user-attachments/assets/062acc3c-f174-45b6-bcf2-e21e81e78233)
![image](https://github.com/user-attachments/assets/9ea69860-7ed0-4c2c-80f4-8f98f1b6ee29)
2. `close after uninstall` says it will only affect when Pearcleaner is opened via Finder extension, but if I open the app normally , it will also close itself after uninstall.
![image](https://github.com/user-attachments/assets/0dc52f65-e429-47b7-9dd7-c50c1591250f)

**Comment by alienator88** [comment]
Nice find!
Would you be able to add these as a new issue so I can track them better?
I think I know why at least 2 of those happen.
