### ISSUE TITLE
[BUG] Accessibility permissions set but Pearlcleaner doesn't seem to know it

### ISSUE THREAD

**Issue by gitatmax** [alienator88/Pearcleaner#159]
### Describe the bug:
Accessibility permissions don't seem to take or stick

### Steps to reproduce:
1. Open the app
2. See notice about disabled accessibility permissions
3. Go to Accessibility preferences & confirm it's set (I've also unset & reset this + restarted the app)
4. Reopening the app, it still says it's disabled
   

### Expected behavior:
Should display that the accessibility options are enabled

### Info:
 - OS: [e.g. 13.0]
 - Pearcleaner Version: [e.g. 3.x.x]

### Screenshots:

<img width="1101" alt="SCR-20241120-iksc" src="https://github.com/user-attachments/assets/c0e7973b-e112-4222-aebc-0c301fefb03a">

### Console Logs (For app crashes or hard to reproduce issues):
 1. Open the Terminal app and run the following command
```
log stream --level debug --style compact --predicate 'subsystem == "com.alienator88.Pearcleaner"'
```
 5. Reproduce the issue to capture logs
 6. Copy the logs here

**Comment by alienator88** [comment]
Did you remove the permission completely or just toggle it off and on?
Try the steps I mentioned here for another person who had the same issue: https://github.com/alienator88/Pearcleaner/issues/127

**Comment by gitatmax** [comment]
That did the trick. Thanks!
