### ISSUE TITLE
[BUG]  Some apps wont just delete through pearcleaner

### ISSUE THREAD

**Issue by ishaanrathodd** [alienator88/Pearcleaner#16]
**Describe the bug**

Try uninstalling OmniDiskSweeper (shown as system app) from pearcleaner, it may not uninstall no matter how many times you click uninstall

**Desktop (please complete the following information):**
 - OS: 14.3
 - Pearcleaner App Mode: Both
 - Pearcleaner Version: 2.3

**Comment by ishaanrathodd** [comment]
Had to delete it through appcleaner later and it worked.

**Comment by ishaanrathodd** [comment]
https://github.com/alienator88/Pearcleaner/assets/90642857/4a3bd92a-b109-413b-a494-00f17c9c2826

As you can see in the video, the app rectangle pro just doesn't get deleted!

**Comment by alienator88** [comment]
I can repro this one, I'll look into it and see what's up

**Comment by alienator88** [comment]
Got this one resolved.
Fix will be out in v2.4

Thanks for reporting it!
