### ISSUE TITLE
[BUG] Brew uninstall command won't execute after uninstall

### ISSUE THREAD

**Issue by L1cardo** [alienator88/Pearcleaner#165]
If the `close after uninstall` option is on, the auto brew uninstall command won't execute.
![image](https://github.com/user-attachments/assets/2dfd202e-cf3e-4ec5-affe-945dcf2b03ac)

Also I have found some other bugs:
1. `CLI support` can't be enabled, and here is the error log
![image](https://github.com/user-attachments/assets/062acc3c-f174-45b6-bcf2-e21e81e78233)
![image](https://github.com/user-attachments/assets/9ea69860-7ed0-4c2c-80f4-8f98f1b6ee29)
2. `close after uninstall` says it will only affect when Pearcleaner is opened via Finder extension, but if I open the app normally , it will also close itself after uninstall.
![image](https://github.com/user-attachments/assets/0dc52f65-e429-47b7-9dd7-c50c1591250f)

**Comment by alienator88** [comment]
I'm guessing you don't have a pearcleaner binary at /usr/local/bin/pearcleaner at the moment?

The error in the screenshot seems to point out that it tried to remove the symlink but it didn't exist:
![image](https://github.com/user-attachments/assets/6f3cb3e7-9b33-492a-83aa-e7b884761346)

Which it shouldn't do because it runs a check to see if the symlink exists first and only executes it if it exists:
https://github.com/alienator88/Pearcleaner/blob/8ed2de96be381a76e68f1f7f60083b2b153521d7/Pearcleaner/Logic/Utilities.swift#L71

**Comment by L1cardo** [comment]
I don't even have this directory `/usr/local/bin/`, I only have `/usr/local/`

And here is the video

https://github.com/user-attachments/assets/53523cb1-4fbc-476a-823e-a1e327792e8b

**Comment by alienator88** [comment]
That's kind of wild, I haven't seen anyone without that bin folder before. I thought it was default on macOS.
I bet if you run this in terminal and then try Pearcleaner CLI toggle again, it should work:
`sudo mkdir /usr/local/bin`

I might need to add a catch and check that the folder exists before running the symlink commands.

**Comment by L1cardo** [comment]
> That's kind of wild, I haven't seen anyone without that bin folder before. I thought it was default on macOS. I bet if you run this in terminal and then try Pearcleaner CLI toggle again, it should work: `sudo mkdir /usr/local/bin`
> 
> I might need to add a catch and check that the folder exists before running the symlink commands.

Yeah, it worded after `sudo mkdir /usr/local/bin`

**Comment by alienator88** [comment]
Awesome, thanks for confirming!
I added a check to make sure the folder exists first before trying to symlink it there. That should avoid this issue in the future.
Can you try this test build and see if your other issues are resolved as well?
[Pearcleaner.zip](https://github.com/user-attachments/files/17938195/Pearcleaner.zip)

**Comment by L1cardo** [comment]
Tried your test build and the latest release build, if I uninstall an app from Finder extension, the brew uninstall command won't trigger.

**Comment by alienator88** [comment]
Ughh..hmm..I just tested it now and it came right up with terminal and brew cleaned the app once I clicked uninstall.
You have brew cleanup setting enabled still?

Maybe record it and show me what you get.

**Comment by L1cardo** [comment]
Log shows nothing special


https://github.com/user-attachments/assets/281a76cf-9517-4a7e-962c-f929f1dc6113


![image](https://github.com/user-attachments/assets/f1688560-b345-4a85-b3ef-3213eb72d956)

**Comment by alienator88** [comment]
Ahh, it's the close after uninstall setting preventing it still.
It seems there's a race condition, I'll figure it out and push out another update after the holidays.
I want to refactor the uninstall logic and make it cleaner anyways.

**Comment by alienator88** [comment]
Actually, can you try this when you have a moment? I was able to work on it a bit.
[Pearcleaner.zip](https://github.com/user-attachments/files/17941387/Pearcleaner.zip)

**Comment by L1cardo** [comment]
Yeah, now it works

**Comment by alienator88** [comment]
I'll have this out in the next patch release.
