### ISSUE TITLE
[BUG] Android Studio cache is not listed in development view

### ISSUE THREAD

**Issue by seanmckenzie428** [alienator88/Pearcleaner#166]
### Describe the bug:
When in development view, the cache path for Android Studio is not listed with the folders to delete.
   

### Expected behavior:
Add `~/Library/Caches/Google/AndroidStudio*` to the list of directories for Android Studio.

### Info:
 - OS: [15.1.1]
 - Pearcleaner Version: [4.0.0]

### Screenshots:

![Screenshot 2024-11-27 at 7 56 31 AM](https://github.com/user-attachments/assets/5bf4b37c-db5c-4fa3-b665-31ddfaeeab19)

**Comment by alienator88** [comment]
Thanks!
It's hard to know all the folders for so many dev environments, I appreciate it when people chime in with missing ones.
I just added that path, will have it out in the next release.

**Comment by seanmckenzie428** [comment]
Yeah I can't imagine trying to keep track of all that. Also, thanks for such an awesome program!
