### ISSUE TITLE
[FR] Hit area size for the category selector is too small

### ISSUE THREAD

**Issue by strash** [alienator88/Pearcleaner#167]
Here's a small demonstration of what I mean:

https://github.com/user-attachments/assets/975daa26-a876-49a7-bc26-9135db1a32a2

The problem is that you need to be extremely precise when clicking on the menu item to activate it. To address this issue, you could increase the clickable area, as shown in the image.

<img width="1123" alt="Screenshot 2024-11-27 at 18 53 27" src="https://github.com/user-attachments/assets/74bea1da-9880-4e27-b630-d2f99aa70bb4">

**Comment by alienator88** [comment]
Hey there, I just checked the bounds on the buttons and you are correct, they are tiny! 😂 
![image](https://github.com/user-attachments/assets/16430e2e-11d1-4203-b001-cad892a94b49)

I just increased it to this, so hopefully it should be easier:
![image](https://github.com/user-attachments/assets/1737abce-0c03-4476-ba31-c81c331fa24a)

I'll have this out in the next release.
