### ISSUE TITLE
[FR] Scroll bar for the list of apps

### ISSUE THREAD

**Issue by KeyboardChampion** [alienator88/Pearcleaner#168]
**Is your feature request related to a problem? Please describe.**

My scroll wheel on my mouse doesnt work, so its annoying that i cant scroll through the apps

**Describe the solution you'd like**
A scroll bar so i can scroll the apps

**Describe alternatives you've considered**

getting a new mouse but it would be more efficient for a scroll bar

**Additional context**

N/A

**Comment by alienator88** [comment]
I've never even thought of that scenario, you're right!
I just changed the scroll indicators to .automatic, so it should follow indicator visibility based on what you set in your macOS settings.
I'll have this out in the next version.

**Comment by alienator88** [comment]
No problem at all :)

**Comment by alienator88** [comment]
FYI, I added a setting toggle in the Interface settings of the app to control this.
By default it's off, but you can toggle it on yourself.
Will be out in the next release.
