### ISSUE TITLE
[FR]  Option to change color palette of the app

### ISSUE THREAD

**Issue by ishaanrathodd** [alienator88/Pearcleaner#17]
The current color palette of orangish red is imo okayish and not something minimalist. Please do consider the plain theme of appcleaner. Looks great.

**Comment by alienator88** [comment]
My issue with this is I'm not trying to completely clone AppCleaner and it's look. I would like to keep some individuality with this app. 
There's not a lot of apps out there that provide settings to change the branding colors, maybe theme colors, but not branding. And the orange/pink palette for the Pearcleaner logo I'd like to keep as I like it personally.

Thank you for the input though, much appreciated!
