### ISSUE TITLE
[BUG] Pearcleaner selects uncorrect files

### ISSUE THREAD

**Issue by L1cardo** [alienator88/Pearcleaner#170]
### Describe the bug:
Pearcleaner selects uncorrect files that is not related to the app

### Steps to reproduce:
1. Uninstall app that is in a folder from finder extension

### Info:
 - OS: [macOS 15.1.1]
 - Pearcleaner Version: [v4.0.1]

### Screenshots:
![image](https://github.com/user-attachments/assets/df1e4d28-7097-4c74-a0d9-7bbbaae941ad)
https://github.com/user-attachments/assets/3afee042-ff2c-48ff-8d4b-69411512da48

### Console Logs (For app crashes or hard to reproduce issues):
 1. Open the Terminal app and run the following command
```
log stream --level debug --style compact --predicate 'subsystem == "com.alienator88.Pearcleaner"'
```
![image](https://github.com/user-attachments/assets/16903785-77d4-49ac-88fd-6ab9f0ed4193)

**Comment by alienator88** [comment]
I think the issue here is the bundle id under the app's name FinalShell is just "st".
Is that the valid bundle id of that app if you look at the Info.plist file?
It's doing a search on the bundle id and "st" matches a lot of those files in the list
Pa`st`epal
SpeedTe`st`
etc..

**Comment by alienator88** [comment]
I just found it and installed it from brew, yeah the bundle id really is that short. 
Not sure what the dev was doing there 😂 
I can probably add a catch that if the bundle id is less than 2 components long, to fallback to app name search only.

**Comment by alienator88** [comment]
Okay, just got this fixed.
I decided to go with checking if the bundle id is one component only, like FinalShell, then check to make sure the length of the bundle id is at least 5 characters long to prevent these scenarios where very short ids find unrelated files.
Now it only finds 2 files as expected.
Thanks for finding this!
