### ISSUE TITLE
[FR] DeepLinks

### ISSUE THREAD

**Issue by johnmokos** [alienator88/Pearcleaner#171]
Hi, it would be a nice addition, in my opinion, if you could implement deeplinks into the app.

An implementation example bellow from Shottr screenshot App:

![SCR-20241128-tefu](https://github.com/user-attachments/assets/8502781f-1e79-4eba-8177-5aaaf3f0b3be)

This makes possible to create more robust and powerful Alfred and Raycast workflows, especially navigation inside the app and also ads more functionality to them.
By navigation I mean all settings - orphaned files - development - applications panes, etc .
By functionality I mean, the App's capabilities and features like updating - changing a specific setting - uninstalling other apps - finding leftovers, etc.
(maybe there are also other benefits in general by implement deeplinks , idk..)

One other alternative to this is to put them maybe under the "Tools" menu-item in the menubar.
This can achieve the same result maybe, but its not so intuitive and practical in my opinion.
 
<img width="406" alt="SCR-20241128-srxb" src="https://github.com/user-attachments/assets/d1328571-b8c3-4010-bc80-79bd6b3c192c">

I think its a nice addition to the App and hope it does not get in the way of your development schedule!

**Comment by alienator88** [comment]
So I currently already have a deep link manager in the app, but it's only used for launching pearcleaner from external means like Sentinel Monitor or Finder extension with an app bundle to search files for. Someone made an alfred extension before it looks like: https://github.com/andylundqvist/alfred-pearcleaner

I could probably expand this to support other regular app functions though:
https://github.com/alienator88/Pearcleaner/blob/main/Pearcleaner/Logic/DeepLink.swift

**Comment by johnmokos** [comment]
Yes, i use the same extension but its so very basic.
Oh yes you do have one! I've looked at your code in the past (I'm not familiar with swift), but it seems I might have missed it!! 
So If you do decide to expand it then it wont be from scratch!
I hope it's an easy feature to do so, cause it offers a lot more flexibility.

**Comment by alienator88** [comment]
Yeah it doesn't seem to be too difficult to add on to it.
It would be super helpful if you could give me a list of actions that should be possible from the deeplinks. I don't want to just start adding all sorts of things if nobody will use them 😂 so having a list would be nice.

**Comment by johnmokos** [comment]
Great! 
Sure! I'll come back with a list asap!

**Comment by johnmokos** [comment]
List of Actions for deeplinks:

Navigation
- open/show/navigate (i think maybe it is the same function) the 3 main views (Applications - Orphaned files - Development) 
- open/show/navigate settings views (general - interface - folders - update - about)
- open/show/navigate permissions view

Functional
- uninstall a given app (checkmark for uninstallation) [user gives the name of the app]
- check for orphaned files
- check for dev environments [user gives the name of the environment]
- check for updates
- add/remove folder to search for applications [user gives the name/path of the folder]
- add/remove folder to exclude for orphaned file search [user gives the name/path of the folder]
- refresh installed apps list
- reset settings

I think thats it. Hope its not a lot ! 😅

**Comment by alienator88** [comment]
Thanks for this, I will take a look soon and see how I can expand the existing deep link manager.

**Comment by alienator88** [comment]
Can you take a look at this custom build?
[Pearcleaner.zip](https://github.com/user-attachments/files/18158411/Pearcleaner.zip)

I think I have everything added, except for the add/remove folder stuff. Still noodling over that one for a bit longer.

I setup a deep link guide here: https://github.com/alienator88/Pearcleaner/wiki/Deep-Link-Guide

Note, this feature/build is not live yet, so nobody else has it until I release the next version.

**Comment by alienator88** [comment]
Just added the 2 other actions for adding/removing apps paths and orphaned file paths. The wiki guide is updated and here is the build that includes all the requested deep link actions for testing: 
[Pearcleaner.zip](https://github.com/user-attachments/files/18169943/Pearcleaner.zip)
