### ISSUE TITLE
[APP] Steam game files show up as "Orphaned Files" after installing.

### ISSUE THREAD

**Issue by comfybonfire48** [alienator88/Pearcleaner#173]
After downloading and installing games from Steam, the game files immediately show up in the "Orphaned Files" section of Pearcleaner. I have to always manually add each individual folder to the ignore list after installing a game. Was hoping there was a way to add support for Steam in someway as I love this application apart from this issue. Thanks

 - OS: 14.6
 - Pearcleaner App Mode: Regular
 - Pearcleaner Version: 4.0.2

**Comment by alienator88** [comment]
Can you give me some examples of where these files get stored?
If the game files get stored in a common place, I could exclude that folder from being searched.

**Comment by alienator88** [comment]
Just checking back in here to see if you had some examples of where the games get installed to.
I don't use Steam so I'm unsure what paths need to be whitelisted.

**Comment by comfybonfire48** [comment]
Hey sorry for the late reply. I've attached a couple screenshots showing examples of Steam games showing up. They seem to mostly be showing up from the Application Support folder in Library while some from the Preferences folder, also located in the library. Please let me know if I can send any more info to help. Thanks
<img width="897" alt="Screenshot 2024-12-09 at 7 49 57 PM" src="https://github.com/user-attachments/assets/40e4ab96-5d38-4678-9aa0-da14f8926ddd">
<img width="897" alt="Screenshot 2024-12-09 at 7 50 35 PM" src="https://github.com/user-attachments/assets/7feb561a-39f2-4c59-bf08-a6e4fc4a7d30">
<img width="897" alt="Screenshot 2024-12-09 at 7 53 12 PM" src="https://github.com/user-attachments/assets/d1160767-5522-4f61-9f98-799788d34c33">

**Comment by alienator88** [comment]
So all those game files have nothing in common with the steam app it seems. I was hoping they were all under like a steam folder that I could whitelist. 

Have you tried doing this by chance?
Open steam settings > downloads and change the steam library location to somewhere like a folder called steam. Then you can just exclude that one folder from Pearcleaner orphan files search. And all future games would get installed there as well and you wouldn't need to exclude files individually.

**Comment by comfybonfire48** [comment]
Hey that is a great idea, thank you for the suggestion. That probably will fix the issue, I'll create that folder right now. Thanks again!

**Comment by alienator88** [comment]
No problem!
