### ISSUE TITLE
[FR] Detect uninstalls from Launchpad

### ISSUE THREAD

**Issue by Pogimon3** [alienator88/Pearcleaner#174]
**Is your feature request related to a problem? Please describe.**

Currently, Pearcleaner detects when applications are removed directly from the Applications folder, but it does not track uninstalls performed through Launchpad. 

**Describe the solution you'd like**

Pearcleaner should detect when an application is uninstalled via Launchpad and automatically initiate its cleanup process, just as it does for apps deleted from the Applications folder.

**Describe alternatives you've considered**

Manually running Pearcleaner after uninstalling apps via Launchpad. This works but requires additional steps

**Additional context**

N/a

**Comment by alienator88** [comment]
I'm not sure there's an API or database that we have access to for launchpad anymore.
There used to be a Dock database file in `~/Library/Application Support/Dock` back in the day, but it doesn't exist anymore.
So without knowing where this data is stored, I don't think I could make this happen.

**Comment by Pogimon3** [comment]
Got it. I am sure that you have already thought about this but I am curious to know why can't we simply monitor the Applications folder for deletions with launchd? Won't this approach work similarly to monitoring trash? 

The only edge case I can think of is someone storing and launching some apps from outside the Applications folder. But if we monitor both the Applications folder and the Trash, even this edge case can be covered.

The only remaining issue I see is if someone moves an app from the Applications folder to another location (without intending to delete the app), which could unintentionally trigger PearCleaner. That said, this could easily be handled with a prompt and ince PearCleaner already prompts users when apps are detected in the Trash, it could show a similar prompt when an app is removed from the Applications folder?

**Comment by alienator88** [comment]
Ah okay, I see!
So there's one issue that would prevent this from working I think.
With the trash monitor, Pearcleaner uses the app bundle that was sent to the trash to extract information from it and find the related files. 
With launchpad since it doesn't get sent to trash, I wouldn't have the app bundle available to extract information from it and try to find related files.

**Comment by Pogimon3** [comment]
Oh, go it! Guess ww can’t do much about this then? I am guessing this will take a lot of rework if you decide to implement this. It's guess I’ll just avoid deleting from launchpad henceforth then!

On 2 Dec 2024, at 11:58 PM, Alin Lupascu ***@***.***> wrote:



Ah okay, I see!
So there's one issue that would prevent this from working I think.
With the trash monitor, Pearcleaner uses the app bundle that was sent to the trash to extract information from it and find the related files.
With launchpad since it doesn't get sent to trash, I wouldn't have the app bundle available to extract information from it and try to find related files.

**Comment by alienator88** [comment]
Yeah for the time being, I can't think of an easy way around it. 
Not sure why Apple has to make everything so difficult either though 😂 they could've just sent the app to the trash and this wouldn't be an issue.
