### ISSUE TITLE
[FR] Make App Icons Clickable to Open the App’s Homepage in the Web Browser

### ISSUE THREAD

**Issue by rafo** [alienator88/Pearcleaner#178]
Currently, when I select an app within Pearcleaner, there are URLs displayed under the app name. While I understand these aren’t active hyperlinks (and sometimes not URLs), it would be incredibly helpful if clicking on the app icon (or the displayed URL) would open the application’s homepage in the default web browser.

### Why?
- Quick Identification: Sometimes, I’m unsure about the purpose of certain apps. Direct access to the app’s homepage would allow me to quickly understand what the app does.
- Improved Navigation: This feature would eliminate the need to manually search for the app online, saving time and effort.
- Enhanced User Experience: Making the app icons or URLs clickable adds an intuitive layer to the interface, aligning with common user expectations.

### Proposed Implementation:
- Clickable App Icons/URLs: Enable the app icons or the displayed URLs to function as hyperlinks that open the associated homepage in the system’s default web browser.

**Comment by alienator88** [comment]
This would be a good idea, but macOS apps don't normally store their homepage URL somewhere within the application bundle. Some have a URL for their sparkle updater like the SUFeedURL property, but those don't always use the app's homepage either, and not all apps have this.
Without having some sort of built-in database to store every website for every application, this wouldn't really be feasible unfortunately. 
Unless I just build in a function to open the browser to google with a search of the app's name and then you can click the first link that pops up to see the homepage..probably closest I could get to the feature request.

**Comment by alienator88** [comment]
Since there's no way to really do this without building and hosting my own database of apps and their homepage URLs, I'll skip this one and close it out for now.
