### ISSUE TITLE
[BUG] PearCleaner crashing when I drag logitech g hub.

### ISSUE THREAD

**Issue by y-u-s-u-f** [alienator88/Pearcleaner#18]
First of all, thanks for all the open source work you do. I want to let you know that I use your app every day and it is the best uninstalling app I have tried out.

**Describe the bug**

When I drag logitech g hub to the window, it crashes.

**To Reproduce**
1. Go to the home window
2. Drag logitech g hub

**Expected behavior**

It opens the uninstalling window

**Desktop (please complete the following information):**
 - OS: 14.3
 - Pearcleaner App Mode: Regular
 - Pearcleaner Version: 2.4

**Screenshots**

If applicable, add screenshot

https://github.com/alienator88/Pearcleaner/assets/67281394/2dbe3cc9-45b8-4b87-a4be-e1599314eef7

s to help explain your problem.

**Additional context**

Crash report:

[crashreport.txt](https://github.com/alienator88/Pearcleaner/files/14149986/crashreport.txt)

**Comment by alienator88** [comment]
Hey, thank you!
I will take a look at it on Monday.
Can you confirm if the app crashes if it’s selected from the list compared to dragging and dropping?
Or does it not show up in the list of apps at all?

**Comment by yufus-md** [comment]
Hey!

It doesn't show up on the list of apps

**Comment by alienator88** [comment]
That makes sense then why it’s crashing. It probably has a weird folder structure inside the .app file or the info.plist file maybe. I’ll get it fixed in the next version, thanks for bringing it up.
I’ll message you again if I have any trouble reproducing the problem on my end.

**Comment by alienator88** [comment]
Fixed in v2.5

**Comment by y-u-s-u-f** [comment]
❤️
