### ISSUE TITLE
[FR] Junk Scanner

### ISSUE THREAD

**Issue by barats** [alienator88/Pearcleaner#181]
I hope this message finds you well. 

I would like to suggest a new feature for the app: the ability to scan and identify junk files.

This functionality could help users:

1. Quickly locate unnecessary or temporary files that take up valuable storage space.
2. Provide an easy way to delete these files safely to optimize device performance.
3. Offer suggestions or categorize junk files (e.g., cache, unused downloads, duplicates) for better file management.

Such a feature would greatly enhance the app’s utility and convenience, especially for users with limited storage capacity or those seeking to maintain their device's health efficiently.

**Comment by alienator88** [comment]
Is this something different from the Orphaned File search it already has currently? I know I don't have option 3 for categories at the moment, but the Orphaned File search should hit those same folders.
![Screenshot 2024-12-16 at 9 36 25 AM](https://github.com/user-attachments/assets/5b0a31b6-ac25-4125-9d83-ee2d16a8a845)

**Comment by barats** [comment]
> Is this something different from the Orphaned File search it already has currently? I know I don't have option 3 for categories at the moment, but the Orphaned File search should hit those same folders.

Haven't tried this feature before, just find out what it mean. 

Thanks for ur reply.

**Comment by alienator88** [comment]
No problem!
