### ISSUE TITLE
[APP] BlueStacks

### ISSUE THREAD

**Issue by JiNiTaiMei2023** [alienator88/Pearcleaner#182]
**App Details**
1. BlueStacks
2. 5.21.650.7550
3. Source https://www.bluestacks.com/mac
4. Type Regular
5. If file/folder deletion issue, enter PATH/S to the files/folders not being deleted
'/Users/Shared/Library/Application Support/BlueStacks'
'~/Documents/bst_boost_interprocess'

**Desktop:**
 - OS: 15.2
 - Pearcleaner App Mode: Regular
 - Pearcleaner Version: 4.0.2

**Comment by alienator88** [comment]
Thank you, I got this fixed. 
Will have this out in the next release.
