### ISSUE TITLE
[FR] Menu item and/or keyboard shortcuts to switch main window

### ISSUE THREAD

**Issue by sharik14** [alienator88/Pearcleaner#183]
**Is your feature request related to a problem? Please describe.**

Whenever I delete an app I always switch from Applications to Orphaned Files and often, by searching for the app name or its developer's name, I find additional files to clean. This means many window clicks to switch back and forth when deleting a couple things.

**Describe the solution you'd like**

A keyboard shortcut to switch between Applications, Development and Orphaned Files. (e.g.: cmd-1/2/3, or cmd-A/D/O, or the like.)

**Describe alternatives you've considered**

Alternatively I'd be happy with a "Mode" or "Window" menu that would let me select -- ideally with keyboard shortcuts for the menu items. But even without keyboard shortcuts, I could use keyboard maestro or applescript or something to switch easily enough. Just right now it's a mouse click on a dropdown, and that's hard to automate or select between.

**Additional context**

That's it!  Very simple. Thank you for considering.

**Comment by alienator88** [comment]
Hey there!
So I'm currently working on deep links within the app which allows you to automate certain app functions. I think I got a pretty good base down at the moment.
Would you want to test this build out?
[Pearcleaner.zip](https://github.com/user-attachments/files/18172352/Pearcleaner.zip)
Note, that it's not signed/notarized as I haven't released this yet.
Take a look at the wiki guide here which has examples on how to open the app to the Applications, Development and Orphaned Files pages, among other things: https://github.com/alienator88/Pearcleaner/wiki/Deep-Link-Guide

You would just need to setup keyboard maestro or your apple script to open one of those deep link URLs and it will do all the work within the app.

**Comment by sharik14** [comment]
Sure thing - works perfectly and does the job for me. Thank you!!

I would still suggest considering adding a Page or Mode menu with options (Applications cmd-1, Developer cmd-2, Orphaned cmd-3). A lot of people might benefit and not think to implement something based on deep linking, and seems like an easy win. But this defn helps me, so thank you!

**Comment by alienator88** [comment]
No problem!
Yeah it shouldn't be too difficult to add keyboard shortcuts to that menu, I'll look into it.

**Comment by sharik14** [comment]
@alienator88 That works like a charm!  Thank you so much for the quick response.

Also – just a quick 'thank you' for the app. This is wonderful. I was so sad when AppDelete stopped working with Sequouia ... and you have done really a superb job making an even better option. So: *thanks*.

**Comment by alienator88** [comment]
I'm glad it works as expected :) 
And you're very welcome, I love working on this project and interacting with everyone here!
