### ISSUE TITLE
[FR] Reducing the prominence of the "hover trail"

### ISSUE THREAD

**Issue by ultratiem** [alienator88/Pearcleaner#184]
I appreciate you are using this app to solve UX problems. The impact of the hover trail in the sidebar is quite prominent and ends up being more jarring as they float in a lot of empty space.

You have considered moving them to the left, which would reduce their impact and settle into a more subtle effect.

Cheers (excuse the dirty mockup)

![screen](https://github.com/user-attachments/assets/23a4278f-97b7-4aef-9649-295356587467)

**Comment by alienator88** [comment]
I'll take a look after the holidays. Out of curiosity, does the issue stop if you turn off the animation toggle in Settings > Interface tab?

**Comment by alienator88** [comment]
Sorry, I quickly read over this request and didn't fully understand the ask initially.
Is this kind of what you meant?

https://github.com/user-attachments/assets/a2503f64-a08f-48b7-8c7b-5c968ce8bb1f

**Comment by alienator88** [comment]
I think it's more jarring in the mode you are currently using, which doesn't show the size/version info on the right side.
Looks like you have minimalist app list rows disabled in your screenshot.

**Comment by alienator88** [comment]
Okay, I changed the behavior as follows:
1. In minimal app list rows like I have in the video I posted previously, the hover indicator will stay on the right
2. In the non-minimal mode you have in your screenshot, I moved it to the left side

I'll have this change out in the next release.
