### ISSUE TITLE
SpaceLauncher uninstall leaves behind folder

### ISSUE THREAD

**Issue by apotenza92** [alienator88/Pearcleaner#19]
**Describe the app**
Uninstalling [SpaceLauncher](https://spacelauncherapp.com/) app leaves behind a "com.bugsnag.Bugsnag" folder in Application Support. This folder only contains "name.guoc.SpaceLauncher" indicating to me that it only exists because of SpaceLauncher.

**App Details**
1. Name Spacelauncher
2. Version 2
3. Source Website Download
4. Type Regular

**Desktop (please complete the following information):**
 - OS: 14.3
 - Pearcleaner App Mode: Regular
 - Pearcleaner Version: 2.5

**Screenshots**
Pearcleaner view for uninstall:
<img width="750" alt="image" src="https://github.com/alienator88/Pearcleaner/assets/53612685/328f54ed-5789-4c62-b5cb-466cf29dd4e3">

Extra leftover folder not part of uninstall:
<img width="736" alt="image" src="https://github.com/alienator88/Pearcleaner/assets/53612685/e2ad193f-29ba-436e-9e2c-4593e36b7c23">

**Comment by alienator88** [comment]
Fixed in v2.6.
`com.bugsnag.Bugsnag` is a framework folder that all apps can put files in if they use that framework, so there was no link to SpaceLauncher by name or id.
I added a recursive search on the Application Support folder to check in each of those folders as well, not just root level.
