### ISSUE TITLE
App not showing in Full Disk pane on first launch

### ISSUE THREAD

**Issue by alienator88** [alienator88/Pearcleaner#2]
Dragging/dropping the app into the pane manually still works

**Comment by MadMacMad** [comment]
yes did the same... just drag the app or use the + sign ....
well love your work... well done and you learned quick...
Using McBrew too... love that... easy to use...
shame there is no other way to get in contact... no mail in the app's..
keep up the great work and get a Apple dev account ... it's worth the 80$ in a year...
hope you keep it up! Swift is great!
S.

**Comment by alienator88** [comment]
Hey, thanks!
I'll be updating the app and the repo soon with this email: dev@itsalin.com

**Comment by alienator88** [comment]
Have read up a lot on this issue and it seems there's no API to check for FDA currently and to force the app to show in the FDA pane. Sometimes it will show when trying to access certain files, but not others. 
Added a Permissions window on startup to walk user through adding the correct permissions manually if app is missing from the pane.
