### ISSUE TITLE
[BUG] Stuck on finding application files screen

### ISSUE THREAD

**Issue by strash** [alienator88/Pearcleaner#20]
**Describe the bug**

It's stuck on "Finding application files..".

**To Reproduce**
1. Click to any app
2. See infinite searching

**Expected behavior**

It shouldn't take that much time to find app files.

**Desktop (please complete the following information):**
 - OS: 14.3.1
 - Pearcleaner App Mode: both
 - Pearcleaner Version: [e.g. 2.6]

**Screenshots**

<img width="812" alt="Screenshot 2024-02-14 at 02 26 23" src="https://github.com/alienator88/Pearcleaner/assets/14233263/d1a8634b-2652-41fb-ae69-4eeb087c491b">
<img width="1055" alt="Screenshot 2024-02-14 at 02 26 44" src="https://github.com/alienator88/Pearcleaner/assets/14233263/d43fbcc6-8191-4d60-a758-e0cbf6ed6616">

**Additional context**

**Comment by alienator88** [comment]
Hi, 
So I'm not able to reproduce this at all..hmm..have you tried fully uninstalling Pearcleaner from the Pearcleaner menu?
Then reboot?

![Screenshot 2024-02-13 at 5 25 53 PM](https://github.com/alienator88/Pearcleaner/assets/6263626/2b6578c5-5eb9-4d66-a298-de574b1c9b37)
![Screenshot 2024-02-13 at 5 26 02 PM](https://github.com/alienator88/Pearcleaner/assets/6263626/eb90e001-e061-43b0-9f2f-e8d7e83cff7e)

**Comment by alienator88** [comment]
There's been almost 300 downloads of this version so far and haven't seen other reports of this so far.

**Comment by y-u-s-u-f** [comment]
@alienator88 I'm getting this too.

**Comment by alienator88** [comment]
Let me remove the progress bar and post the build here for you guys to test.
Can you also try opening Console.app, start streaming and reproduce the issue. Then stop the stream and share the log here.
Thanks.

**Comment by y-u-s-u-f** [comment]
Hey @alienator88!

The only thing I get on Console from PearCleaner is this:
```
default	21:06:56.790776-0800	Pearcleaner	TrustSettingsUseXPC is enabled (via feature flags)
```

**Comment by alienator88** [comment]
Could you try these 2 for me?

[Pearcleaner_DEBUG_1.zip](https://github.com/alienator88/Pearcleaner/files/14275439/Pearcleaner_DEBUG_1.zip)
[Pearcleaner_DEBUG_2_NoProgress.zip](https://github.com/alienator88/Pearcleaner/files/14275437/Pearcleaner_DEBUG_2_NoProgress.zip)

**Comment by alienator88** [comment]
This one too.

[Pearcleaner_DEBUG_3.zip](https://github.com/alienator88/Pearcleaner/files/14275529/Pearcleaner_DEBUG_3.zip)

**Comment by strash** [comment]
I did tried to reinstall fresh build from the release page and then all three debug builds you've provided. And the issue is still there.

**Comment by y-u-s-u-f** [comment]
Can confirm what @strash said.

**Comment by alienator88** [comment]
I'll keep playing around with it, really odd that I can't reproduce this problem. I'm curious what your computers might have in common. 
What architecture are you guys running on, intel or arm?

For now, I moved the 2.6 release to a pre-release status, I'd say uninstall the current version and download 2.5 again until I get this sorted.

Thanks!

**Comment by strash** [comment]
> I'll keep playing around with it, really odd that I can't reproduce this problem. I'm curious what your computers might have in common. What architecture are you guys running on, intel or arm?

I have M1 Mac mini if it helps.

**Comment by alienator88** [comment]
I'm slowly reversing some of the changes I made between 2.5 and 2.6.
Can you let me know how this one behaves? If still broken, I'll need to add some extra debug logging in there.

I tested 2.6 on my M1 Pro and an Intel Sonoma VM. None of them get stuck for me, it's so confusing 😂 

[Pearcleaner_DEBUG_4.zip](https://github.com/alienator88/Pearcleaner/files/14283839/Pearcleaner_DEBUG_4.zip)

**Comment by y-u-s-u-f** [comment]
Hey

The 4th debug works. I'm on an M1 iMac BTW.

Yusuf.

Sent via Superhuman ( ***@***.*** )

**Comment by alienator88** [comment]
Okay, so I'm narrowing this down between 2 possible changes, if you could test these two out for me. I really appreciate it!

[Pearcleaner_DEBUG_ProgressNoRecursiveSearch.zip](https://github.com/alienator88/Pearcleaner/files/14284426/Pearcleaner_DEBUG_ProgressNoRecursiveSearch.zip)

I'm thinking the issue might be in this 2nd build here. I also added some debug logs that will be output to your Downloads directory, just called log.txt. If you could grab that for me for this build.
[Pearcleaner_DEBUG_NoProgressWithRecursiveSearch.zip](https://github.com/alienator88/Pearcleaner/files/14284453/Pearcleaner_DEBUG_NoProgressWithRecursiveSearch.zip)

**Comment by y-u-s-u-f** [comment]
Hey Alin,

Thanks for reaching out! I tested both builds and here's what I found:

The first one worked perfectly fine for me. However, with the second build, I noticed that it shows 0 files/folders/items for every app.
Let me know if you need me to help you with anything else!

Yusuf.

Sent via Superhuman ( ***@***.*** )

**Comment by y-u-s-u-f** [comment]
Oh also, here's the log:
[log.txt](https://github.com/alienator88/Pearcleaner/files/14284500/log.txt)

**Comment by alienator88** [comment]
Thanks for that. So it looks like the recursive search I added in the last update is causing it. Just not sure why it's only affecting some users. It might be a folder/file name causing it to crash.
Can you take a look at your log.txt file and see if it matches exactly with all the folders in `~/Library/Application Support/ `folder? If there are any folders/files that you see in Finder that wasn't listed in the log, let me know what they are.

I added a few more debug logs to this build if you could try again and give me the new log:
[Pearcleaner.zip](https://github.com/alienator88/Pearcleaner/files/14284658/Pearcleaner.zip)

**Comment by y-u-s-u-f** [comment]
Hey!

I tested the file, but unfortunately I got the same bug.

I don't really get what you mean to do with the log.txt file, but I [attached it above](https://github.com/alienator88/Pearcleaner/issues/20#issuecomment-1944323469).

**Comment by alienator88** [comment]
So I know the build I just attached will not work. I'm trying to debug it and figure out why the recursive folder search is failing on your computer. 

Can you delete the log.txt file from your Downloads, reproduce the issue again with the build from [this comment](https://github.com/alienator88/Pearcleaner/issues/20#issuecomment-1944350218) and then give me the new log file it creates?
Thanks.

**Comment by alienator88** [comment]
Ahhh that was so helpful. The issue is the recursive search is not ignoring regular/hidden files. It should only be looking at directories.
I was able to reproduce it by creating some empty files in my App Support folder. That's why I didn't see the issue, my App Support folder only contained folders and that's it.

Can you try this "hopefully" fixed version?
[Pearcleaner_FIXED.zip](https://github.com/alienator88/Pearcleaner/files/14285118/Pearcleaner_FIXED.zip)

Thank you so much for your time!

**Comment by y-u-s-u-f** [comment]
Hey! It finally worked. I tried the new zip you provided and it worked perfectly.

Thanks again for your time and help!

**Comment by alienator88** [comment]
Couldn’t have done it without your help!
Hard to troubleshoot bugs when I can’t reproduce them 😂 
I’ll have v2.7 out later with this fix.
Take care.
