### ISSUE TITLE
Please Support From Catalina

### ISSUE THREAD

**Issue by alsyundawy** [alienator88/Pearcleaner#21]
Please Support From Catalina

**Comment by alienator88** [comment]
Hey, sorry about that. I've looked into lowering the OS requirements before, but I use too many new SwiftUI features that are not supported on OS lower than 13.0 (Ventura).

Mentioned here as well: https://github.com/alienator88/Pearcleaner?tab=readme-ov-file#requirements

**Comment by alsyundawy** [comment]
ok thx

bye old mac
