### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by sagunmdr** [alienator88/Pearcleaner#22]
Doesn't Delete the Adobe Folders from Application Folder, (App cleaner does it)

Since this is supposed to be AppCleaner, with a great UI, (which it is tbh)
One big bug is when i uninstall the adobe apps from pearcleaner, it leaves the corresponding folder in application folder, when i do it from appcleaner app, it uninstalls everything.

 - M1 Air, Sonoma 14.3.1
 - Pearcleaner App Mode: Regular
 - Pearcleaner Version: 2.7

Sorry i don't have a screenshot right now, but when i go to application folder, there is a folder leftover with contents inside it.
Folder of adobe app that i uninstalled too, for eg folders of photoshop, illustrator have their folder when uninstalled.

**Comment by alienator88** [comment]
Could I get the path to the folder that is not being deleted for these adobe apps?
I don't have any of these installed.

**Comment by sagunmdr** [comment]
The path to the leftover folder is.
Macintosh HD > Users > 'username' > Application > Adobe Illustrator 2023,
Photoshop.

Note: Currently I have Illustrator & Photoshop installed in this machine.

But The 2 adobe folder along with these files inside are the one that
remains even after uninstalling

I don't remember correctly but I think only the ‘Adobe Illustrator 2023.app’
is the one Pearcleaner removes.
[image: image.png]

**Comment by alienator88** [comment]
Oh I see..it's because they put the apps inside directories inside the Applications folder.
Currently Pearcleaner only checks in the root Applications folder and not inside other folders.
I'll work on this to get it resolved in next version, thanks for reporting!

**Comment by MadMacMad** [comment]
> Ah I see..no, there's no AppCleaner code inside Pearcleaner since AppCleaner is closed-source. I have no idea how they do their logic. Which was one of the reasons I started this app, to learn and to have something open and privacy focused where you can see exactly what it's doing behind the scenes. It's still new right now, just a few months old compared to AppCleaner being over 10 years old. There will be some bugs for a bit there until I get the logic fully ironed out.
> 
> Thanks again for checking it out though!

YES
many thx for this... 
love Pearcleaner ... becoming better and better
much respect
M.

**Comment by alienator88** [comment]
Fixed in v3.0.0
