### ISSUE TITLE
Services files not deleted

### ISSUE THREAD

**Issue by greg1075** [alienator88/Pearcleaner#24]
Files in Services folder not removed after app uninstall.

1. App Name: Araxis Merge
2. Version: 2023.5976
3. Source: https://www.araxis.com/merge/?gad_source=1
4. Type: Regular
5. Path: /Users/homefolder/Library/Services

Desktop info
 - OS: 14.3.1
 - Pearcleaner App Mode: Mini.
 - Pearcleaner Version: 2.7

**Screenshots**

![Screenshot 2024-03-02 at 8 25 31 AM](https://github.com/alienator88/Pearcleaner/assets/28992145/b48078be-b580-4943-a02e-360ef7d81a5b)

![Screenshot 2024-03-02 at 8 29 37 AM](https://github.com/alienator88/Pearcleaner/assets/28992145/091107af-024a-4c85-a624-66861348dd49)

**Additional context**

**Comment by alienator88** [comment]
Hey, thanks for that. I don’t think I have the Services directory added to the search locations. I’ll get that added in next version!

**Comment by alienator88** [comment]
Fixed in next version.
