### ISSUE TITLE
[FR] ENTER ISSUE TITLE HERE

### ISSUE THREAD

**Issue by greg1075** [alienator88/Pearcleaner#25]
Just a suggestion to maybe make the drop zone area larger and thinner kinda like this? :)

<img width="616" alt="Screenshot 2024-03-02 at 1 22 14 PM" src="https://github.com/alienator88/Pearcleaner/assets/28992145/9123b892-c4ac-4975-b542-442ed45f82ed">

vs this

![Screenshot 2024-03-02 at 1 22 14 PM](https://github.com/alienator88/Pearcleaner/assets/28992145/21c3bc27-f4ce-4a84-8fc1-7257fdfaf678)

**Comment by alienator88** [comment]
I was actually going for that same look, but the built in SF Symbols Mac offers didn’t have a thin option. I was trying to stay away from bundling custom images like that to keep app size small. I can probably make that out of a custom shape though. I’ll look into it, the fat border isn’t very good looking to me either 😂

**Comment by alienator88** [comment]
I totally forgot you can set a fontWeight to the symbols 😵‍💫 
Added ultraLight size to it and it looks much better.
Will have this out in next version.
