### ISSUE TITLE
[BUG] 5 sections for web apps

### ISSUE THREAD

**Issue by y-u-s-u-f** [alienator88/Pearcleaner#26]
**Describe the bug**

Basically it's showing 5 "user" sections (I have 5 web apps), instead of one.

**To Reproduce**
1. Have 1+ webapps installed
2. Open the app
3. Scroll to top
4. See many user sections.

**Expected behavior**

It should only show one webapp section

**Desktop (please complete the following information):**
 - OS: 14.3.1
 - Pearcleaner App Mode: Regular
 - Pearcleaner Version: 3.0.1

**Screenshots**

![CleanShot 2024-03-03 at 08 04 26@2x](https://github.com/alienator88/Pearcleaner/assets/67281394/b9b6f981-bf1c-4314-a817-7e43ea14bf84)

**Additional context**

**Comment by alienator88** [comment]
It’s only happening to the user section for you and only with web apps?

**Comment by y-u-s-u-f** [comment]
> It’s only happening to the user section for you and only with web apps?

Yup.

**Comment by alienator88** [comment]
Thanks, I’ll play around with it a bit later today

**Comment by alienator88** [comment]
This is fixed in next version.
