### ISSUE TITLE
[BUG] UI buggy when scrolling

### ISSUE THREAD

**Issue by y-u-s-u-f** [alienator88/Pearcleaner#28]
**Describe the bug**

Basically the system/user section is on top of the apps, the screenshot explains it.
**To Reproduce**
1. Open the app
2. Scroll down a bit.
3. See error

**Expected behavior**

It is not on top of the apps.
**Desktop (please complete the following information):**
 - OS: 14.3.1
 - Pearcleaner App Mode: Regular
 - Pearcleaner Version: 3.0.1

**Screenshots**

![CleanShot 2024-03-03 at 08 15 44@2x](https://github.com/alienator88/Pearcleaner/assets/67281394/a3877774-4e3b-4b9b-a717-60330988c814)

**Additional context**

**Comment by alienator88** [comment]
The background on the section header seems to be invisible for some reason. I’m not seeing that on my end. I wonder if it’s a certain configuration that causes it to show like that.
Do you have transparency enabled or disabled in pearcleaner settings?
Also, do you have transparency enabled system wide for your Mac in accessibility / display settings?

**Comment by y-u-s-u-f** [comment]
- Yes, I do have "transparent material" enabled in Pearcleaner.

- No, I do not have "reduce transparency" enabled in system settings → accessibility → display settings.

**Comment by alienator88** [comment]
I wasn't able to reproduce this one, but I disabled the sticky headers for now in next version.
