### ISSUE TITLE
[BUG] White cursor in search bar hard to see

### ISSUE THREAD

**Issue by greg1075** [alienator88/Pearcleaner#30]
**Cursor in search box of list view is white, which makes it hard to see**

**To Reproduce**
1. Toggle to list view

**Expected behavior**

The cursor was previously red and easier to see. Given the recent redesign and new color palette, maybe change the cursor color to the shade of green used for the drop target gradient, or maybe just to black.

**Desktop (please complete the following information):**
 - OS: 14.3.1
 - Pearcleaner App Mode: Mini mode
 - Pearcleaner Version: 3.0.1

**Screenshots**

![Screenshot 2024-03-03 at 4 07 07 PM](https://github.com/alienator88/Pearcleaner/assets/28992145/c1dc45c8-674d-4990-b5e0-9136c9fdbc8c)

**Comment by alienator88** [comment]
What do you have your OS accent and highlight color set to? Mine is set to blue and the textfield is showing blue as well.
![image](https://github.com/alienator88/Pearcleaner/assets/6263626/eae572d6-bcae-41f4-9c72-f8632f27e060)

I didn't set a color for the blinking cursor in the app, it pulls automatically from the OS from my understanding.
![image](https://github.com/alienator88/Pearcleaner/assets/6263626/f1dc3bcf-b587-4780-88d9-def5d9aa944b)

**Comment by greg1075** [comment]
I had the accent Color set to multicolor, same as before. Not sure why it used red before and white since 3.0. but yes, yes the cursor changes color with that setting. Either way, hardcoding it fixes the issue. Thanks!

**Comment by alienator88** [comment]
I figured out why, before I was using a color set called AccentColor which is the default and it links to the OS setting. 
When I changed it to the pear green, I created a new color set and stopped using the system accent color. I swapped them and everything is fine now :)
