### ISSUE TITLE
[APP] Pearcleaner cant be opened

### ISSUE THREAD

**Issue by martinholovsky** [alienator88/Pearcleaner#31]
**Describe the app**

Unable to start app

**Desktop (please complete the following information):**
 - OS: [14.3.1]
 - Pearcleaner App Mode: [Regular]
 - Pearcleaner Version: [3.0.1]

**Screenshots**
<img width="275" alt="Screenshot 2024-03-04 at 7 20 34" src="https://github.com/alienator88/Pearcleaner/assets/2320048/c34b681f-f407-40d0-88ad-a590bdfea87a">

**Additional context**
For the first time on this system I tried to run Pearcleaner, but Im unable to due to an error.

**Comment by alienator88** [comment]
This is a gatekeeper issue. I don’t sign Pearcleaner with a dev account since I don’t pay for one.

Bypass the error with these steps: 
https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

**Comment by svenjacobs** [comment]
Unfortunately the solution with Ctrl+Open isn't working for me. I still see the same error message. Might have to do with some restrictions applied by the mobile device management.

**Comment by svenjacobs** [comment]
> `xattr -d com.apple.quarantine /PATH/TO/PEARCLEANER.APP`

This worked! Thanks!

**Comment by alienator88** [comment]
Awesome, glad to hear it! 😄
