### ISSUE TITLE
[BUG] Trying to delete 'too many' leftover files

### ISSUE THREAD

**Issue by MurasakiBunny** [alienator88/Pearcleaner#34]
The Leftover Files feature to delete said leftover files of old programs recommends the deletion of many... MANY system files of currently installed Apps.  Running on a test with system data backed up, deleting all recommended files created a massive loss of functionality in many currently running programs such as:

Setting Firefox settings and setup to defualts while removing all extensions, cookies and bookmarks.
Removed Adobe Cloud services rendering Adobe Photoshop and associated programs un-executable as well as Photoshop preference, setting, etc, files.
Delete Discord preference files, etc etc
Actually recommended the deletion of App Packages (like Minesweeper)
Deletion of Automator Scripts.
... and many MANY installed Application's folders within Application Support

After the cleanup, many apps all opened up (that would open, some were broken) started up as if being run for the first time such as iTunes.

In total over 379 files/folders were 'found' to be deletable yet most of them were servicing still installed Apps, including some actually running at the time.

It even tried to delete PearCleaner's own application support and library files

Also tries to delete MacOS startup daemon lists.

To be honest, I think it advised the deletion of setup files from every single Application I have installed.

Pearcleaner Version: 3.1.0 
Running on MacOS 14.4 (23E214)

**Comment by alienator88** [comment]
Wait, you actually just checked everything in the leftover files list and deleted them all without reading what they were? There's an info button on the leftover files page that mentions it's very difficult to find files in a reverse type search without knowing any of the apps you had installed beforehand. There's no app name or bundle id to check against so it casts a very wide net in folders where apps normally store their files. The point of this feature is not to just check all the files shown in the list and wipe them all out without looking at them. You'd need to check the ones that are related to old apps you've removed in the past. There's no way an app could ever know what you had installed in the past so it makes it difficult to implement this type of feature perfectly. If it didn't exclude currently installed apps, that's another issue as the logic does check against installed apps and ignores those files. At least on my end it does, tested on a couple OS versions.
