### ISSUE TITLE
[FR] Menu Bar Icon

### ISSUE THREAD

**Issue by Hidlsh** [alienator88/Pearcleaner#35]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Menu Bar icon for PearCleaner

**A clear and concise description of what you want to happen.**

When the menu bar icon is clicked, it opens a small drop down menu from it which allows you to uninstall apps from it, with a searchbar at the top/bottom as well. Also, an option in the settings that allows the app to be hidden from the dock after it is open already launched and on menu bar - which I think would also make sense to have a "Open on Login/Startup" feature as well to go with this.

Here's a full size screenshot of the size of an app with a dropdown feature (WARP). I'm on a MacBook Air M1, with a 13.3 inch screen, running at 1600x1000 Resolution btw
![CleanShot 2024-03-15 at 09 28 41@2x](https://github.com/alienator88/Pearcleaner/assets/67646781/f60945dd-51ee-4ea1-9a96-0b33aceb5a48)

**Comment by alienator88** [comment]
Hey, that's a good idea. I've been thinking about doing a menu bar option but wasn't sure there would be anybody wanting that. I could convert the mini mode view to display in the menu bar since it's already tailored for a small footprint. I'll start working on this.
Thanks again!

**Comment by Hidlsh** [comment]
no problem! Thank you for this amazing app!

**Comment by alienator88** [comment]
Added in v3.2.0
