### ISSUE TITLE
v.3.2.0 - Can't uninstall from Menu Bar

### ISSUE THREAD

**Issue by Hidlsh** [alienator88/Pearcleaner#36]
**Describe the bug**

I am having trouble finding the uninstall button for apps within the menu bar icon in v3.2.0? 

**Issue production video**

https://github.com/alienator88/Pearcleaner/assets/67646781/9dfe3f95-65af-410e-98d0-c1ae40aa15bb

So basically, upon clicking on an app within the menu bar icon for Pearcleaner, nothing happens - except that it gets selected, as indicated with the green sidebar next to it. 

**A clear and concise description of what you expected to happen.**
In the video I click on the app I want to uninstall to select it, then I thought something would appear like a uninstall button to the right of the app. something like this maybe?

App should prompt some way to uninstall it after being pressed.
![CleanShot 2024-03-19 at 09 50 03@2x](https://github.com/alienator88/Pearcleaner/assets/67646781/c02be900-da4c-4111-b739-8203c477e5fb)
(I edited the trash bin icon from the regular Pearcleaner menu and put it into the menu bar version.)

Let me know if there's anything else I should explain better.

**Desktop (please complete the following information):**
 - OS: [Sonoma 14.4]
 - Pearcleaner App Mode: Mini Mode
 - Pearcleaner Version: 3.2.0

**Comment by Hidlsh** [comment]
Also another thing I just thought of: After the uninstall button is pressed, it should maybe bring up a pop-up menu to the right of the app/ over the app? A window showing what's to be uninstalled 

like how the fullsize Pearcleaner does. That way, since the uninstall trash icon button is already at the bottom, double clicking on the app within the menu bar could just open up this sort of pop-up window, instead of also having the trash icon I edited in - while continuing to show the app's version like usual.
![CleanShot 2024-03-19 at 09 58 17@2x](https://github.com/alienator88/Pearcleaner/assets/67646781/301152b6-0fb9-4000-b6ab-feeef0326962)

**Comment by alienator88** [comment]
So that's really odd, it does popup a window to the side with all the files. At least on my end. Only difference I see is that I'm not updated to Sonoma 14.4 yet, I'm still on 14.3.1
I'm curious if the update to that version is what's breaking the popover from triggering. Let me test on my Ventura VM as well and see if it happens there.

![Screenshot 2024-03-19 at 9 01 54 AM](https://github.com/alienator88/Pearcleaner/assets/6263626/5aa55dfb-35e3-4efa-884b-acb22d004f9a)

**Comment by Hidlsh** [comment]
I've just reinstalled the app, and the issue still persists. Also, on your end, does it take a little bit before the side bar goes green when you select an app? like a small delay? maybe for me that's probably happening because the uninstall pop-up won't open 🤷🏾‍♂️

**Comment by alienator88** [comment]
Yeah, my Ventura VM also works fine.
I'll need to update to 14.4 and test it out there. 

![Screenshot 2024-03-19 at 9 11 00 AM](https://github.com/alienator88/Pearcleaner/assets/6263626/04d04b3a-eec7-430a-9dd1-6b45a211e53f)

And no, it's pretty instant when I click the app and the popover shows to the side.

Can you open up Console.app and from the Action menu in the menubar, make sure "Include Debug Messages" is enabled.  Then start a recording and reproduce the issue. Stop it when done and set the subsystem category to my app's bundle id. It should filter debug logs just for my app.
![Screenshot 2024-03-19 at 9 14 20 AM](https://github.com/alienator88/Pearcleaner/assets/6263626/ee26449f-893e-4c4b-ba04-cf4a0c07481f)

Also, are you seeing the popover not work when you have the menubar option off and just using Mini Mode? Mini mode uses the same view as the menubar option, so I'm curious if that popover is broken as well.

**Comment by alienator88** [comment]
I can't update my mac for a couple hours or so, I'm working at the moment. I'll test out 14.4 when I'm done.

**Comment by Hidlsh** [comment]
no worries, time is all yours

**Comment by Hidlsh** [comment]
**Go to the bottom of this comment btw**

> Can you open up Console.app and from the Action menu in the menubar, make sure "Include Debug Messages" is enabled. Then start a recording and reproduce the issue. Stop it when done and set the subsystem category to my app's bundle id. It should filter debug logs just for my app. 

I pressed the pressed the start button to record the issue in the console app, then began to reproduce the issue. It was filling up with information as I selected apps through the mini menu, but nothing is shown after I filter with your app's bundleID within the subsystem category: 
![CleanShot 2024-03-19 at 10 47 14@2x](https://github.com/alienator88/Pearcleaner/assets/67646781/e1a3a985-e838-41fb-9eb6-20067d456b9f)

Although nothing is showing under the subsystem category filter for your bundleID, there are results under the 'ANY' category: 
![CleanShot 2024-03-19 at 10 51 24@2x](https://github.com/alienator88/Pearcleaner/assets/67646781/2a0efe7a-3950-423d-baa2-073bcc0cca5a)
Here's the file: 
[console 03-19-2024.txt](https://github.com/alienator88/Pearcleaner/files/14653611/console.03-19-2024.txt)


> Also, are you seeing the popover not work when you have the menubar option off and just using Mini Mode? Mini mode uses the same view as the menubar option, so I'm curious if that popover is broken as well. 

figured it out as I was typing this loll

'Mini Window Mode' needs to be enabled for the sidebar popup to show within the Menu Bar version 😅 
![CleanShot 2024-03-19 at 11 38 14@2x](https://github.com/alienator88/Pearcleaner/assets/67646781/2775f511-f776-4cd0-8fc9-379fe770c5e7)

**Comment by alienator88** [comment]
Oh my gosh LOL, you're so right.
I almost never use regular mode, always in mini so I completely missed that.
Let me take a look at it and I'll push out a quick fix 😂

**Comment by alienator88** [comment]
Pushed out v3.2.1, thinking that should do it.
Thanks for the issue report!
