### ISSUE TITLE
Homebrew version wrong tagged 

### ISSUE THREAD

**Issue by Fischmuetze** [alienator88/Pearcleaner#4]
The Homebrew pearcleaner version is wrong tagged  with latest.
As result some install scripts are not able to distinguish if there is a update available or not and install the app again and again. See brew-cask-upgrade
https://github.com/buo/homebrew-cask-upgrade/blob/master/README.md

<img width="1086" alt="pearcleaner" src="https://github.com/alienator88/Pearcleaner/assets/19834496/d95de2c2-13e2-4522-953b-1d1990e21b02">

**Comment by alienator88** [comment]
Might need to untap and tap the repo again
