### ISSUE TITLE
[BUG] Can't Open Folder Settings

### ISSUE THREAD

**Issue by y-u-s-u-f** [alienator88/Pearcleaner#41]
**Describe the bug**

I can't open the folders setting section. It just takes me to interface.

**To Reproduce**
1. Go to settings
2. Click on folders
3. See error

**Expected behavior**

It should have went to the folder settings

**Desktop (please complete the following information):**
 - OS: Sonoma 14.4.1
 - Pearcleaner App Mode: Regular
 - Pearcleaner Version: 3.4.0

**Screenshots**

https://github.com/alienator88/Pearcleaner/assets/67281394/43a475b5-064a-4bcc-a6db-4ccd2d6494b9

**Comment by alienator88** [comment]
Nice catch, was fixing a bug in settings and forgot to change that back. 
Fixed in 3.4.1
