### ISSUE TITLE
[FR] Scan in ~/Library/Logs too

### ISSUE THREAD

**Issue by theramzay** [alienator88/Pearcleaner#43]
**Is your feature request related to a problem? Please describe.**

`Pearcleaner` is awesome software and I’ve found that `Pearcleaner` is not search in `~/Library/Logs` for clean up.

**Describe the solution you'd like**

It will be cool, to add this location too, thanks.

**Additional context**

I’ve made test between [App Cleaner](https://nektony.com/mac-app-cleaner) and `Pearcleaner` and results are really good, but as I can see — `Pearcleaner` miss this one folder to clean up(and maybe you can find something more on my screens, that I’ve not found by myself). I’ve added screenshots of my tests:

<img width="300" alt="image" src="https://github.com/alienator88/Pearcleaner/assets/5748239/d7e87fd9-a735-49be-a610-5215a3a78577">
<img width="300" alt="image" src="https://github.com/alienator88/Pearcleaner/assets/5748239/e10bfaf2-b885-4947-a393-80e67eac63b0">
<img width="300" alt="image" src="https://github.com/alienator88/Pearcleaner/assets/5748239/e875cdb6-5b27-4e5f-9688-1072f9d4e100">
<img width="300" alt="image" src="https://github.com/alienator88/Pearcleaner/assets/5748239/d4eaaf8e-f08e-4f65-8def-4588152de707">

**Comment by alienator88** [comment]
Closing as fixed in next version: 3.5.1
