### ISSUE TITLE
[FR] Scan in ~/Library/Containers too

### ISSUE THREAD

**Issue by theramzay** [alienator88/Pearcleaner#44]
**Is your feature request related to a problem? Please describe.**

`Pearcleaner` is awesome software and I’ve found that `Pearcleaner` is not search in `~/Library/Containers ` for clean up.

**Describe the solution you'd like**

It will be cool, to add this location too, thanks.

**Additional context**

I’ve made test between [App Cleaner](https://nektony.com/mac-app-cleaner) and `Pearcleaner` and results are really good, but as I can see — `Pearcleaner` miss this one folder to clean up. I’ve added screenshots of my tests:

<img width="400" alt="image" src="https://github.com/alienator88/Pearcleaner/assets/5748239/2ab0b71f-6f49-40cc-9543-0e2f33b67ce4">
<img width="400" alt="image" src="https://github.com/alienator88/Pearcleaner/assets/5748239/0a53b5cd-78c1-4db7-bbf6-c8ea8ac5a6cf">

**Comment by alienator88** [comment]
Hey there!
I'll throw a comment in here for both of the issues you opened. 
Pearcleaner does have the Logs and Containers locations in the search, but I think something else might be filtering those files out:

https://github.com/alienator88/Pearcleaner/blob/main/Pearcleaner/Logic/Locations.swift

I'll take a look when I get a chance to see if I can reproduce and hopefully get a fix out for these 🙂

**Comment by theramzay** [comment]
> Hey there! I'll throw a comment in here for both of the issues you opened. Pearcleaner does have the Logs and Containers locations in the search, but I think something else might be filtering those files out:
> 
> https://github.com/alienator88/Pearcleaner/blob/main/Pearcleaner/Logic/Locations.swift
> 
> I'll take a look when I get a chance to see if I can reproduce and hopefully get a fix out for these 🙂

Big Thanks! Your app is really awesome! )

**Comment by alienator88** [comment]
So it looks like Revolut killed the mac desktop app. It's not available to download anymore from the AppStore, only available for iPhone, iPad, and Apple Watch.

I'm not sure I can reproduce this problem now, and probably doesn't make sense to work on a bug for an app that can't be downloaded anymore 😂 let me know what you think.

**Comment by theramzay** [comment]
> So it looks like Revolut killed the mac desktop app. It's not available to download anymore from the AppStore, only available for iPhone, iPad, and Apple Watch.
> 
> I'm not sure I can reproduce this problem now, and probably doesn't make sense to work on a bug for an app that can't be downloaded anymore 😂 let me know what you think.

Ah, yep, that’s why I want to delete it :) But, I’ll use your app & app cleaner together, and then report if found something :D
What do you think about another issue with Jetbrains Rider IDE ?
