### ISSUE TITLE
[FR] It's actually a cry for help

### ISSUE THREAD

**Issue by rainlycoris** [alienator88/Pearcleaner#49]
How do I uninstall Pearcleaner completely?
I messed up a few things, and now I can't open Pearcleaner at all. I want to reinstall it.
Can you help me? Thank you very much!!!

**Comment by alienator88** [comment]
Hey there. Pearcleaner doesn't leave a lot behind, but if you want to do a full uninstall, I suggest downloading the app again and going to the Pearcleaner menu and clicking Uninstall there.
![Screenshot 2024-04-29 at 9 07 47 AM](https://github.com/alienator88/Pearcleaner/assets/6263626/dd1a0d4d-18e7-46ce-854a-cacc0e58297a)

**Comment by rainlycoris** [comment]
But now I can't open Pearcleaner（
Because I foolishly added the root directory to the scanned folder.
I downloaded it again, but I still can't open it.  Could you tell me where to store the settings file?

**Comment by alienator88** [comment]
Ohhh I see. Try this:
- Open Terminal
- Run command `defaults delete com.alienator88.Pearcleaner`
- This should wipe all stored custom settings for the app, including the root directory added for app searching

**Comment by rainlycoris** [comment]
I gave it a try, and when I run `sudo defaults delete com.alienator88.Pearcleaner` output 
```
2024-04-30 16:01:52.621 defaults[4589:315287] 
Domain (com.alienator88.Pearcleaner) not found.
Defaults have not been changed.
```

**Comment by rainlycoris** [comment]
emm, I also try no sudo version, but also no effect.

**Comment by rainlycoris** [comment]
No sudo version It's working fine, but Pearcleaner still won't open.

**Comment by alienator88** [comment]
What is actually happening? Can you add some screenshots or errors you’re
seeing?
Using that command wipes all the custom settings you might’ve added.

**Comment by rainlycoris** [comment]
<img width="682" alt="截屏2024-05-01 11 55 02" src="https://github.com/alienator88/Pearcleaner/assets/125644853/6e4953b7-1b6a-4a6d-b2c8-729ad4f211c7">
<img width="702" alt="截屏2024-05-01 11 53 41" src="https://github.com/alienator88/Pearcleaner/assets/125644853/e2253f8b-54c2-45c8-b445-70b3ae5a0213">

**Comment by alienator88** [comment]
I guess I don’t understand how Pearcleaner is almost 1 gb in size..the app
is only ~3mb. What happens if you delete the Pearcleaner app and just
download it again now that the settings are cleared?

Or if you right click the app and Show Contents, what inside the app is
taking up so much room?

**Comment by rainlycoris** [comment]
That's the task manager interface, RAM is 1GB.
Don't forget I added the root directory to the scan folder (
I downloaded it again, and run `defaults delete com.alienator88.Pearcleaner`. It's all the same. Can't open it.

**Comment by rainlycoris** [comment]
It's seem like `defaults delete` no effect, because I run `defaults read com.alienator88.Pearcleaner` show
```
 displayMode = 2;
    "settings.folders.apps" =     (
        "/Applications",
        "/Users/ldl/Applications",
        "/"
    );
    "settings.general.brew" = 1;
```

**Comment by rainlycoris** [comment]
I run `defaults delete com.alienator88.Pearcleaner "settings.folders.apps` Solved the problem, now can open, thank you very much!!!

**Comment by alienator88** [comment]
Hey, that's great to hear! 
Really odd that the original defaults command didn't wipe out the settings. I tested it on my end and it worked. Oh well, glad you got it figured out :)
