### ISSUE TITLE
[BUG]  Silicon M3 ... can't delete any app...

### ISSUE THREAD

**Issue by MadMacMad** [alienator88/Pearcleaner#5]
last 2 versions didn't work for me here...
booth same problem... 
can select a app to delete... but it never get's deleted...
just did second test on another Silicon... same there...

**Comment by alienator88** [comment]
Does a version previous to the last 2 work for you still?
That's very odd, I'm not able to reproduce this currently.
I'm on M1 Pro with Sonoma 14.1.1
Does it happen with every app or certain apps only?
Does the app show enabled with permissions in the Accessibility pane and the Full Disk pane?
When the app moves files to trash, it requires the Accessibility permission so Finder can trash the files itself.

**Comment by MadMacMad** [comment]
hello,
did u use the overlay Variable Manager to add those
<img width="1493" alt="Bildschirmfoto 2023-11-29 um 06 51 25" src="https://github.com/alienator88/Pearcleaner/assets/10008614/0fa1cc5a-4758-45b4-8fb8-e5d4f3909546">
? 
if not it doesn't work...

**Comment by MadMacMad** [comment]
hi,
had for example the DAZ app... it got installed via an Installer that loads the content from the web...could not delete the app with your tool... had to do manually ...
but other can be deleted that got installed manually or via App Store...
but there is still a issue... it list those monitor app's and when you click on them the app crashes...
<img width="1012" alt="Bildschirmfoto 2023-11-29 um 06 54 59" src="https://github.com/alienator88/Pearcleaner/assets/10008614/9f5201e7-c4fd-4920-b238-1d9c6f7a0ae4">

**Comment by alienator88** [comment]
Can you give me steps on how I can reproduce your issue? How can I get an app installed like that so it shows monitor?
Do you still have these monitor apps in your /Applications or ~/Applications directory, because that's where my app looks for the apps to generate that list.

**Comment by alienator88** [comment]
No response
