### ISSUE TITLE
Excluded Files Option

### ISSUE THREAD

**Issue by Vulazgo** [alienator88/Pearcleaner#51]
Hello, I would like to report a bug/suggestion. I have to remember to uncheck my ".minecraft" files in the leftovers because I use an external launcher. I think Pearcleaner thinks I don't have the official Minecraft app. It would be cool to be able to automatically select excluded folders in Pearcleaner Settings, maybe just below the Folder Setting Pane. Many thanks for your app :)

**Comment by alienator88** [comment]
Hey, that's a great idea!
I will work on separating that Folder view into two and add  picker for excluding from leftover search. I think I will allow files and folders in that section if the user wants to ignore individual files as well.
Thanks!

**Comment by alienator88** [comment]
Added in v3.6.1
