### ISSUE TITLE
[FR] Automation Permission Check

### ISSUE THREAD

**Issue by Retold3202** [alienator88/Pearcleaner#53]
**Is your feature request related to a problem? Please describe.**

I was having issues with Pearcleaner not properly deleting my files, and I couldn't figure out why. I went through my app permissions, and finally figured out that Pearcleaner was not granted the `Automation` problem, which is what was causing the issue. Once granted that permission, it worked like a charm.

**Describe the solution you'd like**

Under Pearcleaner's settings, in General, it already checks if the `Full Disk Access` and `Accessibility` permissions are granted. I think it'd be very beneficial and helpful to users if the `Automation` permission was also checked in this way, to prevent issues like the one I was having.

**Comment by alienator88** [comment]
Good idea.
There's a few smaller permissions that get requested automatically while the app is executing functions via an alert popup. If that gets missed or accidentally set to deny permission, you'd run into the issue you saw.

I'll redo the whole permission request process to check for all of them at once.

Thanks!

**Comment by alienator88** [comment]
Got this added in to the next version when that's released.
Thanks again.
