### ISSUE TITLE
Leftover Files Feature Deletes Firefox Nightly Folders

### ISSUE THREAD

**Issue by danrungg** [alienator88/Pearcleaner#56]
**Describe the bug:** <br>
Hi, the Leftover Files Feature removes the following folders, even if Firefox Nightly is still installed:
/Users/.../Library/Application Support/Firefox
/Users/..../Library/Caches/Firefox

I have a newly set up MacBook.

**Steps to reproduce:**
1. Install Firefox Nightly 127.0a1
2. Run leftover files scan
3. See paths

**Info:**
 - OS: Macos 14
 - Pearcleaner Version: 3.6.2

Thank you

**Comment by alienator88** [comment]
Close Pearcleaner and reopen it. I updated the remote conditions file and it should ignore those now.
Let me know if it worked.

**Comment by danrungg** [comment]
It worked!

Thank you so much.

**Comment by MuenYu** [comment]
Hello, same for Firefox developer edition.

**Comment by alienator88** [comment]
Hi, so I've moved to an exclusion model since I can't keep up with all the different apps and folders they create.
You should be able to right click > Exclude the firefox folder or file from the Orphaned Files view and it won't show up anymore.
