### ISSUE TITLE
Poor contrast in the "Update Available" window

### ISSUE THREAD

**Issue by Anitoxx** [alienator88/Pearcleaner#57]
I noticed that the contrast between the green (#71C254) and the background color (#B4B4B2) is very poor.

Here is a screenshot of the "Update Available" window and a contrast checker test (from [coolors.com](https://coolors.co/), here is the link of the test : [https://coolors.co/contrast-checker/71c254-b4b4b2](https://coolors.co/contrast-checker/71c254-b4b4b2)

<img width="499" alt="image" src="https://github.com/alienator88/Pearcleaner/assets/84633029/b7f58a55-1bd2-420a-91a0-ffa2b65d4082">

This unfortunately makes the text hard to read.

<img width="1202" alt="image" src="https://github.com/alienator88/Pearcleaner/assets/84633029/8fc307d5-5b10-453a-9511-b41ffa9273a7">

**Comment by alienator88** [comment]
Hey, thanks for catching that!
I almost never use light mode so these slip through sometimes 😂 
I made the edits to not use the accentColor for that text and the buttons as well for all popup windows.
Will have the fix out in next release.
