### ISSUE TITLE
Refresh Button for Menu Bar Icon + UI misalignment 

### ISSUE THREAD

**Issue by Hidlsh** [alienator88/Pearcleaner#59]
**Is your feature request related to a problem? Please describe.**
I know that there is a refresh feature, but I'd like the button to be visible at all times instead of having to hover over the top to see it (and maybe replace the text with a refresh icon instead? ). 

**Describe the solution you'd like**
A always visible refresh button/text somewhere in the menu bar version of the app

![CleanShot 2024-05-23 at 10 04 09@2x](https://github.com/alienator88/Pearcleaner/assets/67646781/94df6737-6c10-438b-a4f0-2077f8e391a0)

Refreshes the app list.
Maybe a setting for automatic refreshing or checking? (idk how much strain it'll have on the device, just a suggestion though.)

Also UI misalignment: 
![CleanShot 2024-05-23 at 10 07 04@2x](https://github.com/alienator88/Pearcleaner/assets/67646781/5d25b73b-c058-4f5f-8f3a-08967a56c6e7)

Vertically or horizontally stretching the app doesn't change the spacing, the issue still persists.

**Comment by alienator88** [comment]
Hi. The app used to have a refresh icon a while back but I moved away from it because it made the UI look too busy on the right side for a function that really shouldn't be needed very often. You can also `CMD+R` to refresh via keyboard.

As for the misalignment, can you let me know how to reproduce that? I don't see the same thing in mini mode:
![image](https://github.com/alienator88/Pearcleaner/assets/6263626/b9844dbb-9657-446e-9ce8-63a417daa687)

Maybe post a screenshot of your Interface tab in the Settings window to see if I can match mine up the same. Otherwise, it might just be an environmental issue on your end.

**Comment by Hidlsh** [comment]
> Hi. The app used to have a refresh icon a while back but I moved away from it because it made the UI look too busy on the right side for a function that really shouldn't be needed very often. You can also `CMD+R` to refresh via keyboard.

Okay, I honestly think it doesn't make the app look too busy; maybe have option in settings (appearance tab maybe) for either preference?

> As for the misalignment, can you let me know how to reproduce that? I don't see the same thing in mini mode. Maybe post a screenshot of your Interface tab in the Settings window to see if I can match mine up the same. Otherwise, it might just be an environmental issue on your end.

I am not using mini mode. My issue only persists in the regular look of the app when "Menubar Icon Enabled" is toggled 'ON':
![CleanShot 2024-05-25 at 05 41 27@2x](https://github.com/alienator88/Pearcleaner/assets/67646781/29fc450a-314f-40e6-93d1-3e208267cae3)

I tried reinstalling the latest version to see if my app was bugged, but that wasn't the case. The app's settings also persist upon reinstall but that didn't affect anything - the issue only happens with menubar mode on, when you open the full sized version of the app from your taskbar/launchpad/applications folder/finder (yk what I mean)

**Comment by alienator88** [comment]
I'm pretty sure I know why the misalignment is happening, so I'll look into that and will also play around with the refresh button when I get a chance.

**Comment by alienator88** [comment]
Fixed both of these in 3.6.4
Thanks!
