### ISSUE TITLE
Option to clean uninstall the app by itself ?

### ISSUE THREAD

**Issue by Anitoxx** [alienator88/Pearcleaner#6]
Or maybe, if it's a portable app, specify that to uninstall it, we simply need to move it to the trash, as we normally do with other apps.

**Comment by Anitoxx** [comment]
If you already tried Onyx, you'll see that they have an uninstall script in the "Help" tab. Incorporate a uninstall script in a software that uninstall cleanly other software seems pretty coherent to me.

By uninstall script, I mean a script that uninstalls completely (= clean) a software (like your software does). I prefer to write my definition of a uninstall script in case I'm wrong with what exactly a "uninstall script" is, but I like to call it like that.

Concerning the placement of this script, it would be a better UX design decision to put it in one of the tab as people would see this more as a "research conflict" (don't know how to call that too, like the uninstall script), rather than a real uninstallation script program to cleanly uninstall the app itself.

Maybe inside the "Help" tab, like Onyx, would be a good idea ?

**Comment by alienator88** [comment]
I added "Uninstall Pearcleaner" option to the main Pearcleaner menu item.
The function unloads Sentinel Monitor if it's running, then it searches for all the Pearcleaner files, kills the app and trashes the files. 

Will be out in v1.8 after I get a few more things fixed/added in.
