### ISSUE TITLE
[FR] One-Shot Mode

### ISSUE THREAD

**Issue by welcome-linja** [alienator88/Pearcleaner#61]
**Is your feature request related to a problem? Please describe.**

I really like the Finder extension, and that's how I see myself using the app most of the time. It's annoying that once I do that, the app keeps running, and I have to quit manually. I just don't like things running that aren't doing anything.

**Describe the solution you'd like**

An option to quit once cleaning is finished. For functionality, I guess you'd also need an option to check for updates on clean?

**Describe alternatives you've considered**

I don't think there are any conceivable alternatives.

**Additional context**

**Comment by alienator88** [comment]
I'll look into this, I think it's a good idea for the Finder extension. 
Could even do something like quick/single click of the Uninstall button removes the files and leaves the app running.
But long click of the Uninstall button removes the files and closes the app after.
Could even have a little checkbox next to the Uninstall button which could be marked to close the app after Uninstall is pushed.

I'll play around with different workflows and see what makes more sense.

**Comment by alienator88** [comment]
Added this setting under Settings > General tab in v3.6.5, out now.
Thanks!
