### ISSUE TITLE
[FR] Auto Update Improvement

### ISSUE THREAD

**Issue by hisikbay** [alienator88/Pearcleaner#64]
This is not a problem, but an optional improvement.

The current version's settings allow users to adjust the interval for checking updates but do not offer an option to disable this feature entirely. Providing an option to turn off automatic update checks would give users more control and comfort knowing they can disable it if they wish.

In the version's settings, there are arrows to increase or decrease the interval for checking updates. One potential solution could be to allow the interval to be set to 0 days OR extend the range to 8 days (since the current maximum is 7 days) to disable the automatic update checks. This small change would offer more flexibility to users.

Thank you for reading this and taking the time!

**Comment by alienator88** [comment]
Hey, that's a good idea. I'll probably just add a toggle to enable/disable the updater.
Something I noticed when looking at the updater code is that the update check doesn't even really work at all how it's supposed to 😂 when the app is closed, it looks like it doesn't save the next update timestamp in the settings so the timer just starts again next time its opened.
I'll fix this bug and add a toggle as well for the next release.
Thanks!
