### ISSUE TITLE
[BUG] Automatic switching between dark and light modes does not work.

### ISSUE THREAD

**Issue by threay** [alienator88/Pearcleaner#65]
**Describe the bug:** <br>
I set the  color mode to auto, but it doesn't seem to switch according to my system's color mode. I'm not sure if I have configured something incorrectly.

**Steps to reproduce:**
1. Every time I reopen the software in the evening or morning, as described earlier, the color mode doesn't seem to follow the system. Instead, it displays the color mode from the last time it was opened.
2. However, if I switch the software to dark mode (or light mode)，and then back to auto, the application's color mode will match my system.
3. Do I need to keep the software running in the background for the color mode to follow the system? I usually exit the software completely and do not let it run in the background.

**Expected behavior** <br>
I hope the software's color mode can correctly match my system. Perhaps it should check the system color mode when I open the software as well? Anyway, thank you for making this application, I really like it!

**Info:**
 - OS: [14.5]
 - Pearcleaner Version: [3.7.1]

**Comment by alienator88** [comment]
Hey, thanks for sending this in.
I just played around with the color settings and I was able to reproduce the issue.
It was a tiny bug, I was only running the color mode check on app launch if the themeColor was empty. 
I changed it so it runs on every launch and it works good now.

The fix will be out in the next version, later today I think.

**Comment by alienator88** [comment]
v3.7.2 with fix is released.

**Comment by alienator88** [comment]
Hey, just took a look now and I believe it should be fixed.
Can you try this build for me?
[Pearcleaner.zip](https://github.com/user-attachments/files/16091672/Pearcleaner.zip)

**Comment by alienator88** [comment]
No problem at all, thanks for testing it out!
