### ISSUE TITLE
[FR] Printout or copy of discovered app list

### ISSUE THREAD

**Issue by entasis54** [alienator88/Pearcleaner#69]
Upon finding the associated app files for an individual app, it would be very convenient to be able to print or copy the found, including locations, list to be submitted to a Developer for troubleshooting purposes. I have been consistently deep into MAC ownership since 1984. Many of my apps were downloaded when first released, so over the years of updating these apps, several different files are installed in various folders of the Mac's operating system. Upon going through several revisions and updates of apps, sometimes for several years, it would be helpful when troubleshooting an app to be able to copy or print a list to be submitted to the app's Developer to aid in troubleshooting. Thank you.

**Comment by alienator88** [comment]
Hey, that's a nice idea. 
I'll add it to the list, shouldn't take much work for this one.
Will let you know when it's done.

**Comment by entasis54** [comment]
Thank you for your consideration, and I hope matters work out, as I just used screenshots of Pearcleaner's findings to resolve a software issue with another Developer.

**Comment by alienator88** [comment]
Any preferences on how to trigger this list? Maybe an option in the menu bar? I didn't want to clutter the UI with a bunch of utility buttons.
Also, what format would be most helpful, json, csv, plain text?

**Comment by alienator88** [comment]
Just released first version of this in v3.7.4
Search for an app's files and hit CMD+E to export.
