### ISSUE TITLE
[BUG] Can't delete applications from the App Store

### ISSUE THREAD

**Issue by Anitoxx** [alienator88/Pearcleaner#7]
Every applications in the App Store can't be deleted (for example Mindnote, or Proton Pass).

If this is normal, it should perhaps be specified in the "Help" section (I'm thinking about a link to a F.A.Q. page in the github project for example).

**Comment by alienator88** [comment]
Speaking of..I just tried deleting one of my apps downloaded from the App Store and it was able to get deleted without issue.
It popped up and asked me to input my admin password. 
When you try to delete an App Store app, do you get a popup asking to input your computer password?
And does this happen with all App Store apps or just some?
Another thing to check is if you have the Accessibility permission enabled okay as it uses that to trash the files and ask for the admin password.

**Comment by Anitoxx** [comment]
It seems to happen on all of the apps from the App Store,

Indeed, I noticed iMovie, which comes from the App Store but it's a native application, so it's probably different.

I did a test, I tried to install Capcut from their dmg file, it of course appears on Pearcleaner (by the way, I found one leftover of Capcut in the library file (in Finder, "Go > Press Option > Find "Library") it's the UserData, and there is a lot of subfolders inside), and when I install it from the App Store, it still appears in Pearcleaner.

However, "Proton Pass" application in the App Store doesn't get detected in Pearcleaner, even when updated.

**Comment by alienator88** [comment]
It actually seems to be an iOS app wrapped to run on Mac, so that might be the distinction here.

**Comment by alienator88** [comment]
Just pushed out v1.8 which should be able to handle wrapped iOS apps.
I tested other App Store apps on my end that are regular mac apps and it uninstalls them fine.

**Comment by Anitoxx** [comment]
Hey, just to say it works fine, thank you.

I love the "ios" logo aside of the app's name, nice detail.
Thank you to make this app exist.

**Comment by alienator88** [comment]
Glad to hear it's working! 
Thanks for finding this bug :)
