### ISSUE TITLE
"Pearcleaner.app" can't be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by benjaminoram** [alienator88/Pearcleaner#71]
After downloading the latest version (3.7.4, released 18th June) and opening on my MacBook Air M1 (Updated to Sonoma 14.5), I get the error:

'"Pearcleaner.app" can't be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.'

**Comment by alienator88** [comment]
Do the instructions here not work anymore?
https://github.com/alienator88/Pearcleaner?tab=readme-ov-file#requirements

I don't have a developer account so it's not signed with a certificate.

**Comment by benjaminoram** [comment]
> Do the instructions here not work anymore?
> 
> https://github.com/alienator88/Pearcleaner?tab=readme-ov-file#requirements
> 
> 
> 
> I don't have a developer account so it's not signed with a certificate.

Ah sorry, I missed that. The text in the macOS warning message stating that the app needs to be updated is misleading!

I'm sure the warning for unsigned apps used to say something helpful like 'this app is not signed'.

**Comment by alienator88** [comment]
I also do feel like it had different messaging before 😂
They're really trying to force hobby devs to purchase those developer accounts.

**Comment by cspence001** [comment]
When installing via homebrew the --no-quarantine flag can be added to disable this check for the specific app:
`brew install alienator88/homebrew-cask/pearcleaner --no-quarantine`

**Comment by alienator88** [comment]
Good tip @cspence001 
I'll add that on to the brew instructions.
Thanks!
