### ISSUE TITLE
"lipo" command requires command line developer tools prompt on latest update (3.75)

### ISSUE THREAD

**Issue by mjoshea148** [alienator88/Pearcleaner#72]
Starting Pearcleaner results in prompt to install command line tools to execute the lido command.

Appears to be new behavior.  Don't otherwise need command line tools.

**Steps to reproduce:**
1. Start Pearcleaner 3.75
2. Observe dialog to install command line tools
3. App appears to function normally otherwise

Unsure if this is a new requirement or bug.

**Comment by alienator88** [comment]
Good catch, was actually not aware that the lipo command didn't come installed by default. Obviously I have xcode installed so didn't get this popup 😂 
I'll work on this and get something out for next update.

**Comment by alienator88** [comment]
So I'm running into some confusion here. 
I checked 3 fresh macOS installs on different OS versions and they all come with the `lipo` command installed by default even when xcode command line tools is not installed.
```
> which lipo
/usr/bin/lipo
```

Either way, I'll switch to using the `/usr/bin/file` command which I'm 100% sure it's there by default just in case.

**Comment by alienator88** [comment]
If you run `which file` on your system in Terminal, do you get the path I mentioned above?

**Comment by mjoshea148** [comment]
Confirmed - same path.

**Comment by alienator88** [comment]
Cool, I'll release the update shortly using file instead of lipo.

**Comment by alienator88** [comment]
v3.7.6 out now

**Comment by mjoshea148** [comment]
Confirmed fix works :). Thank you.  Please consider a career at any major software company.  Not used to this kind of support!
