### ISSUE TITLE
[BUG] v3.7.8 does not recognize/honor the accessibility setting

### ISSUE THREAD

**Issue by fpuhan** [alienator88/Pearcleaner#74]
**Describe the bug:** <br>
When launching Pearcleaner, a dialog is presented requesting/requiring accessibility access via the Security and Privacy setting. But it does not detect the change.  Even with repeated off/on changes, Pearcleaner does not update itself and continues to show the padlock/check button in the UI.

**Steps to reproduce:**
1. Launch Pearcleaner v3.7.8.  A dialog is immediately present asking for permission and offering to open Settings (it doesn't).
2. Click on Settings->Privacy & Security->Accessibility and move the slider switch to the right to turn the setting on. 
3. Quit System Settings.  Quit and restart Pearcleaner.
4. Error dialog persists.  

**Expected behavior** <br>
Upon re-launch, the red padlock "Check" button is replaced with a green button with the current version (3.7.8) displayed.

**Info:** The same behavior on two different Macs:

 - OS: 14.5 Sonoma
 - Pearcleaner Version: 3.7.8

- OS:  13.4.1 Ventura
- -Pearcleaner 3.7.8

**Screenshots**

![Launch](https://github.com/alienator88/Pearcleaner/assets/99229315/58e1d986-d53f-4513-bda5-ca089d2040bf)
![MissingPermissions](https://github.com/alienator88/Pearcleaner/assets/99229315/87fd1bab-d2bc-4908-99a5-6ef942c77d04)
![Settings](https://github.com/alienator88/Pearcleaner/assets/99229315/86eaf4f9-c26d-4320-8bf0-d027bf6b33c5)

**Additional context**

I might uninstall and re-install because I haven't made major configuration changes.  But that shouldn't be necessary.

**Comment by alienator88** [comment]
Hi, this was mentioned in the release notes here: https://github.com/alienator88/Pearcleaner/releases/tag/3.7.7

It happened because I’m building the app with a signed/notarized certificate now.
