### ISSUE TITLE
[APP] Pearcleaner.app will damage your computer

### ISSUE THREAD

**Issue by Laicure** [alienator88/Pearcleaner#75]
>NOTE: If a specific app is finding unrelated files or not finding expected files, use the new condition builder to either include or exclude files from the search. Push CMD+B when you're on an app's page to show the condition builder.

**Describe the app**

A clear and concise description of what the affected app issue is.

**App Details**
1. Pearcleaner
2. v3.7.8
3. downloaded here via Chrome

**Desktop (please complete the following information):**
 - OS: Ventura 13.6.7
 - Pearcleaner App Mode: Regular
 - Pearcleaner Version: 3.7.8

**Screenshots**

![ss 2024-07-07 at 01 16 07 AM](https://github.com/alienator88/Pearcleaner/assets/8619566/82d9feaf-2cac-47a7-a653-c26e86b4cce0)

**Additional context**
Booted my Mac Mini 16/512 just now and that prompt popped.
When opening the app from Launchpad or via Application folder, it still shows that prompt.

**Comment by alienator88** [comment]
Hmm..that's odd.
I just tested downloading v3.7.8 from the releases page and opened it up on my computer(Sonoma), a Sonoma VM and Ventura VM. I just see this expected popup and then it launches fine on both.

![Screenshot 2024-07-06 at 4 37 14 PM](https://github.com/alienator88/Pearcleaner/assets/6263626/c3fec54f-02bb-4a41-a3a8-35576590dd4a)

How did you get the download, from the release page here?
https://github.com/alienator88/Pearcleaner/releases/tag/3.7.8

Or homebrew?

**Comment by Laicure** [comment]
Hello!

I've downloaded it directly here in this repo. I'll try reinstalling it today and update here. Just really weird that it just suddenly popped out (I didn't install or download anything past few days.

**Comment by waterydan** [comment]
Hi, I'm having the same issue... Redownloaded 3.7.8 and it is working now. But the UI looks completely broken. I'm on Sonoma 14.5.

![CleanShot 2024-07-07 at 17 41 28](https://github.com/alienator88/Pearcleaner/assets/25826361/cfdd715b-ee8c-44c6-8509-6dcc4e7722ed)

**Comment by alienator88** [comment]
On 3.7.8 it's a theme issue. You can probably go in the settings and manually change the appearance mode toggle between light and dark mode. It's the text color that's the issue there. I have a new build I'm working on to address these things, hoping to have it out later today or tomorrow.

**Comment by andrsschultz** [comment]
Same happens to me.

**Comment by alienator88** [comment]
Can someone test the attached v3.8.0 build?
I had to add a custom theme toggle on the appearance tab. Off by default. 
When off it should follow the OS appearance mode now. When on, it should be based on the custom theme color set by the user.
Before, the theming system was getting confused because there was no differentiation between themes on and off. 
I'm hoping this is the nail in the coffin for these theme problems, it's been super annoying 😂 please give me some good news!

[Pearcleaner.zip](https://github.com/user-attachments/files/16120814/Pearcleaner.zip)

**Comment by Laicure** [comment]
I've updated to Sonoma 14.5 just today too and reinstalled this app. Seems good now. I'll test again but will not close this issue for now as it's still appearing on some users.

**Comment by waterydan** [comment]
> Can someone test the attached v3.8.0 build? I had to add a custom theme toggle on the appearance tab. Off by default. When off it should follow the OS appearance mode now. When on, it should be based on the custom theme color set by the user. Before, the theming system was getting confused because there was no differentiation between themes on and off. I'm hoping this is the nail in the coffin for these theme problems, it's been super annoying 😂 please give me some good news!
> 
> [Pearcleaner.zip](https://github.com/user-attachments/files/16120814/Pearcleaner.zip)

Yeah the new version is working for me. But its always dark theme though even though the color mode is set to 'Auto'.

**Comment by alienator88** [comment]
Could you let me know what your OS appearance mode is set to? Light, Dark, Auto?

Also show a screenshot of the Pearcleaner interface tab in settings.

I want to see if I can reproduce what you're seeing. In my testing today, I wasn't getting this behavior at all with the new build.

**Comment by IoannisTM** [comment]
Hello,
Just to add my input
I had pearclaner install via home-brew and got the same error message "..will damage your Mac".
I updated to 3.8.0 via home-brew but this did not fix it.
The zip file you provided seems to be working fine
Hope that helps

**Comment by alienator88** [comment]
Hi all, 

So I'm not 100% sure yet why the damaged error occurs but I'm leaning towards this.
Any app on version v3.7.6 or below that used the old unsigned certificate had its authorization revoked when I switched to signing/notarizing the app with a valid apple cert. With this in mind, the auto-updater built-in to the app and homebrew updating will likely not work, if you can even open the old versions of the app anymore.

The quickest way around this is to just manually trash the app on those old versions and just re-download one of the latest builds.

**Comment by alienator88** [comment]
> Yeah the new version is working for me. But its always dark theme though even though the color mode is set to 'Auto'.

Reposting this here so it doesn't get lost:

Could you let me know what your OS appearance mode is set to? Light, Dark, Auto?
Also show a screenshot of the Pearcleaner interface tab in settings.

I just tested the following scenarios on the 3.8.0 build I linked above:
1. OS set to Auto, Pearcleaner set to Auto, Light, Dark (all 3 worked)
2. OS set to Light, Pearcleaner set to Auto (worked-launched in Light mode)
3. OS set to Dark, Pearcleaner set to Auto (worked-launched in Dark mode)
4. Pearcleaner set to Light or Dark mode (worked, ignores system setting as expected)

I'd love to know the combination on your end that makes it start up in Dark mode only on version 3.8.0. Anything below that version let's ignore as I made a lot of changes in this new build for the appearance modes.
