### ISSUE TITLE
[APP] PearCleaner not finding all components

### ISSUE THREAD

**Issue by Svec-Tomas** [alienator88/Pearcleaner#78]
**Describe the app**

Looks like PearCleaner is not finding all the app components as it can be seen on the attached screens.

**App Details**
Trying to remove this app:
[Ad Blocker for Safari - Bolt](https://apps.apple.com/sk/app/ad-blocker-for-safari-bolt/id1041834536?l=sk)
with PearCleaner 3.8.0 & AppCleaner 3.6.8
MacOS Sonoma 14.5
MacBook Pro 14 M1 Pro

**Desktop (please complete the following information):**
 - OS: [e.g. 13.0]
 - Pearcleaner App Mode: [e.g. Regular / Mini Mode]
 - Pearcleaner Version: [e.g. 2.0]

**Screenshots**

![AppCleaner](https://github.com/user-attachments/assets/79887855-bc28-47d1-83dc-72de1c04c6a3)
![Bolt](https://github.com/user-attachments/assets/2bf0103f-9a15-4320-acaf-60854a23321c)

**Comment by alienator88** [comment]
Are all of those files in the trash folder? Looking at the AppCleaner
paths, the majority of those are located in ‘~/.Trash’.
If you empty your trash, are the files found still different if you reopen
AppCleaner after emptying the trash?

**Comment by alienator88** [comment]
Side note, looks like your permissions for Pearcleaner are also not fully granted. The permissions notification at the top left of the window above the app list. If you updated recently, you might have to go into the permissions and fully remove and re-add Pearcleaner. Instructions here: https://github.com/alienator88/Pearcleaner?tab=readme-ov-file#permissions-alert-on-the-signednotarized-version
