### ISSUE TITLE
[BUG] Overreach when deleting the app: Text Case app

### ISSUE THREAD

**Issue by strauhmanis** [alienator88/Pearcleaner#8]
**Describe the bug**
Pearcleaner finds and selects files/folders not associated with the app to be uninstalled.

**To Reproduce**
No special steps required.

**Expected behavior**
I expected Pearcleaner to find the artefacts associated only with the Text Case app, leaving out artefacts associated with other apps.

**Screenshots**
Screenshot is attached.

![Screenshot](https://github.com/alienator88/Pearcleaner/assets/17160191/ada27638-81a3-4186-9658-c7ecc669b265)

**Desktop (please complete the following information):**
 - OS: 14.1.2
 - Chip: Apple M1
 - Pearcleaner App Mode: Regular

**Additional context**
The app in question is downloadable from the link below:
https://apps.apple.com/us/app/text-case/id1492174677

**Comment by alienator88** [comment]
Hey, thanks for the report! I'll take a look at this specific app when I get a chance.
Not super active at the moment with the holidays around the corner. A bit busy in my free time.

**Comment by alienator88** [comment]
Solved by v1.9, closing issue
