### ISSUE TITLE
Pear Cleaner Crashes, when having in Menubar-Mode

### ISSUE THREAD

**Issue by sagittarius-codebase** [alienator88/Pearcleaner#80]
**Describe the bug:** <br>
I played around with the settings. I enabled Menubar-Mode
A little Trashbin Icon appeared in the Menubar.
But whenever I click it, the whole App crashes. So I also have no option to get to the settings other than by reinstalling the app.

**Steps to reproduce:**
1. Open Settings
2. Enable "Menubar-Mode"
3. Click on the icon in the Menubar

**Expected behavior** <br>
App crashes without Feedback, also when right-click on the icon

**Info:**
 - OS: macOS 14.5
 - Pearcleaner Version: 3.8.1

**Console Logs (For app crashes):**
 - Open the Console.app on your mac
 - Enter  in the search box and set filter to subsystem ![image](https://github.com/alienator88/Pearcleaner/assets/6263626/c2f646a9-feec-4e04-a13d-ccacff2329fb)
 - Click Start to record logs ![image](https://github.com/alienator88/Pearcleaner/assets/6263626/dc706fa1-0800-4eaf-aee6-8516da83fcff)
 - Reproduce the issue you're experiencing in Pearcleaner
 - Click Pause <br> ![image](https://github.com/alienator88/Pearcleaner/assets/6263626/826962a1-4212-4b64-a24a-ea6663defb46)
 - Export the captured logs using the Share button
`[Untitled.txt](https://github.com/user-attachments/files/16321181/Untitled.txt)`

Nothing appeared with the filter: subsystem, so inlcuded everything.
Hope the upload worked.

**Screenshots**

**Additional context**

**Comment by alienator88** [comment]
Fixed in 3.8.2!

**Comment by sagittarius-codebase** [comment]
Thanks man! :)
