### ISSUE TITLE
App Crashes, when enabling "Mini-Window-Mode"

### ISSUE THREAD

**Issue by sagittarius-codebase** [alienator88/Pearcleaner#81]
**Describe the bug:** <br>
When I enabled the Mini-Window-Mode the App crashes. The same goes for when I disabled it.

**Steps to reproduce:**
1. Open the Pear-Cleaner-Settings
2. Enable/disable Mini-Window-Mode

**Expected behavior** <br>
App Crashes with Notification Window from macOS

**Info:**
 - OS: 14.5
 - Pearcleaner Version: 3.8.1

**Console Logs (For app crashes):**
 - Open the Console.app on your mac
 - Enter `com.alienator88.Pearcleaner` in the search box and set filter to subsystem ![image](https://github.com/alienator88/Pearcleaner/assets/6263626/c2f646a9-feec-4e04-a13d-ccacff2329fb)
 - Click Start to record logs ![image](https://github.com/alienator88/Pearcleaner/assets/6263626/dc706fa1-0800-4eaf-aee6-8516da83fcff)
 - Reproduce the issue you're experiencing in Pearcleaner
 - Click Pause <br> ![image](https://github.com/alienator88/Pearcleaner/assets/6263626/826962a1-4212-4b64-a24a-ea6663defb46)
 - Export the captured logs using the Share button

Again with the filter: subsystem, nothing got found, so I included everything that has to do with the "com.alienator88.Pearcleaner"

[mini-window-crash.txt](https://github.com/user-attachments/files/16321206/mini-window-crash.txt)

**Screenshots**

**Additional context**

**Comment by alienator88** [comment]
Fixed in 3.8.2!
