### ISSUE TITLE
[FR] Are there any plans to add multi-language function?

### ISSUE THREAD

**Issue by wendaleruan** [alienator88/Pearcleaner#83]
Are there any plans to add multi-language function?

**Comment by alienator88** [comment]
Likely in the near future once I have the app running really stable and some of the new features I'm working on added in.
Will probably need some external help on this though to contextualize all the strings to different languages.

**Comment by megabitsenmzq** [comment]
I can help you translate it into Chinese. Let me know when you need it and send me the Xliff files. 😊

**Comment by alienator88** [comment]
That would be super helpful @megabitsenmzq! I'll tag you here when it's ready.

**Comment by Svec-Tomas** [comment]
Count with me also when you will be ready to translate Pearcleaner to other languages.

**Comment by alienator88** [comment]
I added the base translation now, it uses the newer XCode 15+ Strings catalog. 
Best way to do this is fork the repo, open the project in XCode and add your language and translations to the Resources > Localizable.xcstrings catalog file.
Ignore strings marked with "Don't Translate", although it should prevent you from editing those anyways. Then create a pull request and I'll approve the changes.

![Screenshot 2024-10-15 at 2 40 54 PM](https://github.com/user-attachments/assets/ff0a132c-532d-4d4c-ac42-5762558777cf)

**Comment by Svec-Tomas** [comment]
I haven't downloaded Xcode and I've never used it for translation. It seems like an unnecessarily complicated application for someone who doesn't develop apps, especially since it requires around 4GB of space.

I'm using an app called [Strings - Translate & Localize](https://apps.apple.com/us/app/strings-translate-localize/id6480307343?mt=12), which is perfect for this purpose. It's free for manual translation (AI has a limit of 20 free translations).

Can I ask you to add SK (Slovak) as a language to [Localizable.xcstrings](https://github.com/alienator88/Pearcleaner/blob/main/Pearcleaner/Resources/Localizable.xcstrings), so I can choose it for translation in the app?

Thank you in advance!

**Comment by alienator88** [comment]
Just pushed an update to the file, I had to make an edit on one of the keys to make it show up.
I tried the app you mentioned above and it doesn't seem to account for the "Don't Translate" state that XCode shows, so I'm putting a screenshot here of what doesn't need to be translated:
![image](https://github.com/user-attachments/assets/7cdd9df3-3414-4eb0-b468-84a4420cca59)

Thank you!

For anyone else wanting to contribute, let me know what language you would like added to the file.

**Comment by megabitsenmzq** [comment]
I usually export XCLOC files and give them to my user. And let them use something like "Loca Studio" to input the strings. I'll then import the file back to Xcode to review it.

**Comment by alienator88** [comment]
That's nice, I didn't see the export/import function before. This is my first time doing localization on a mac app.
I can export Chinese XCLOC file for you, which version, Traditional, Simplified, etc.?

**Comment by megabitsenmzq** [comment]
> That's nice, I didn't see the export/import function before. This is my first time doing localization on a mac app. I can export Chinese XCLOC file for you, which version, Traditional, Simplified, etc.?

I can do both zh_Hans and zh_Hant. But I can also create a pull request for that later, so you don't need to export them for me.

**Comment by alienator88** [comment]
Awesome, thank you!

**Comment by megabitsenmzq** [comment]
I found that many "Don't Translate"s are unnecessary. Adding "verbatim" to the Text can exclude these Texts from translation. I will first create a PR for this.

<img width="270" alt="image" src="https://github.com/user-attachments/assets/0f135f5e-660f-4ba3-a84a-92e10e1f7d92">

**Comment by alienator88** [comment]
@megabitsenmzq tested and merged ✅ 
Thank you, I wasn't aware of the "verbatim" property before today.

**Comment by florentinf** [comment]
Hi :) I could translate the app into German.

**Comment by alienator88** [comment]
@florentinf go for it! Any help is appreciated :)

**Comment by florentinf** [comment]
@alienator88  In German, "duzen" means to address someone informally using "du," while "siezen" refers to the formal address using "Sie." The choice depends on the relationship and context.
Should I use "du" or "Sie" in the German translation?

**Comment by alienator88** [comment]
For which text in the code? So I know the context.

**Comment by florentinf** [comment]
@alienator88 For example here: Add files or folders that will be ignored when searching for orphaned files. Click a path to remove it from the list.
Now the question is whether you should use the “Du” form or the “Sie” form in German

**Comment by florentinf** [comment]
@alienator88 Also, should I translate sentences literally, or is it better to adapt them stylistically for the best flow?

**Comment by alienator88** [comment]
I think it would be fine for you to decide what sounds best in the context of a Mac app. 
Me not being familiar with the language/s, I wouldn't really know either way 😂.

**Comment by florentinf** [comment]
@alienator88 Hello :)
I have finished translating the app into German.
How exactly should I send it to you?

**Comment by alienator88** [comment]
Hey!
I have a couple things to add to the translation that I missed. See the recent updates in this PR: https://github.com/alienator88/Pearcleaner/pull/131

Once I add those in, could you translate those as well?
Also, how did you do the translations? In xcode on the repo locally or via the XCLOC files?

**Comment by alienator88** [comment]
Once I have those added in and you translate the new changes, can you submit them as a new PR? If you're familiar with it that is, I know not everyone does PRs.

**Comment by alienator88** [comment]
Looks like there may be some overlap with the currently open PRs for Chinese.
@changanmoon has a PR for traditional.
@megabitsenmzq has a PR for simplified.
@funsiyuan who is not part of this issue discussion also has a PR for simplified. 

Any preferences on which PRs to go with?
Might need to create some way to manage translation assignments going forward so work doesn't get duplicated between people.

**Comment by megabitsenmzq** [comment]
I'm not native to Traditional. If someone native can do Traditional, it’s better than me.

**Comment by megabitsenmzq** [comment]
Maybe we should use some tools like Crowdin to manage translations in the future. Then everyone can edit a single version of the translation.

**Comment by alienator88** [comment]
FYI, I have started tracking of progress in this discussion: https://github.com/alienator88/Pearcleaner/discussions/137
If you'd like to help or be removed from assignments, let me know and I can add/remove you from the table.
We can still use this issue for dev talk, mainly wanted to track who is helping on what in a centralized place.

**Comment by florentinf** [comment]
@alienator88 Hello!
I have translated the whole old localizable document, unfortunately you have adapted it now, do I have to start all over again?

**Comment by alienator88** [comment]
I don't believe you need to do the whole thing over.
Did you clone the repo or are you only editing the strings catalog file directly?

**Comment by florentinf** [comment]
@alienator88 I cloned it in Xcode from Github. the whole repo.

**Comment by alienator88** [comment]
You should be able to stash/commit your changes and then do a pull to get the new strings catalog file, merge the changes and commit.

**Comment by florentinf** [comment]
@alienator88 Okay, thanks. How can I merge the changes?

**Comment by alienator88** [comment]
Might try Chatgpt if you aren't familiar with the process.
Sorry, not trying to be unhelpful but I'm at work right now and a bit busy.

**Comment by florentinf** [comment]
@alienator88 Okay, no problem. I'll manage somehow :)

**Comment by alienator88** [comment]
If you're not using the GitHub Desktop app, I'd suggest that one as it can walk you through things easier

**Comment by alienator88** [comment]
To clear things up a bit regarding the Chinese translations.
A PR has already been merged which added `zh-HK`.
So we still need `zh-Hans` and `zh-Hant` from my understanding? Correct me if I'm wrong.
If anyone wants to or is working on either of those.
Looks like PR https://github.com/alienator88/Pearcleaner/pull/136 is for zh-Hans.
@megabitsenmzq if we can get those removed strings back in that were manual extractionState I think we can merge your zh-Hans PR. And then zh-Hant if you submit a new PR for that later.

**Comment by funsiyuan** [comment]
Hello @megabitsenmzq, I apologize for only now noticing the discussion here. I also really appreciate your generous willingness to abandon your own PR.

I wanted to include some of your translations in my PR, but I saw it’s already been merged.
If possible, please review the latest Localizable.xcstrings file and feel free to adjust any parts of the Simplified Chinese translations that you think could be improved.

I believe that with more people contributing to the open-source community, this project will keep getting better.

**Comment by megabitsenmzq** [comment]
@funsiyuan, I will rebase on yours and check if there is anything I can improve. 👍

**Comment by alienator88** [comment]
Closing this issue, we can discuss translations here going forward: https://github.com/alienator88/Pearcleaner/discussions/137
