### ISSUE TITLE
[FR] Consider adding the app to Homebrew cask

### ISSUE THREAD

**Issue by tomy0000000** [alienator88/Pearcleaner#85]
I noticed you already have the cask formula ready [here](https://github.com/alienator88/homebrew-cask/blob/main/Casks/pearcleaner.rb). Would you consider contributing it to the main [homebrew-cask](https://github.com/Homebrew/homebrew-cask) repo?

**Comment by alienator88** [comment]
Submitted, just waiting on review: https://github.com/Homebrew/homebrew-cask/pull/181460

**Comment by alienator88** [comment]
It has been merged: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/p/pearcleaner.rb
Might take a little while until it's available, I don't currently see it yet after a brew update.
Will update the readme and website homebrew commands once I see it live.
