### ISSUE TITLE
The iPhone and iPad app seems to have not been handled properly.

### ISSUE THREAD

**Issue by WindWash** [alienator88/Pearcleaner#86]
The new leftover file search algorithm is quite impressive—it's uncovered many残留 files that I had uninstalled long ago.

But I'm facing a problem now. I have an app from the App Store called "timestripe," **which is a special app for both iPhone and iPad**. I haven't uninstalled it, but it is listed among the leftover files. If I were to accidentally delete these files, I'd have to log back in, and the widgets added by the app have turned blank and cannot be recovered.(After restarting the computer, the widgets are back to normal.)

I understand that leftover file searches aren't foolproof, but if you can investigate this, I'd be grateful.

Update: I just tested and installed another iPad app, which is also appearing in the leftover files.

Moreover, I have two feature requests I'd like to propose. I hope the developers can consider them:

1. It might help reduce accidental deletions if there could be a double confirmation option when deleting files.
2. I had installed MacCleaner Pro a while ago, but after I uninstalled it, an option to retain it in the background persists, and I'm unable to remove it. It would be beneficial if pearcleaner could search for and delete such files.
 
<img width="469" alt="Screenshot 2024-08-03 at 21 47 24" src="https://github.com/user-attachments/assets/8eba2422-715f-4eeb-a53e-fc6f0dcbb517">

I apologize if there's any confusion—my English isn't my strong suit, so please feel free to clarify if something isn't quite clear, and I'd be happy to explain further.

**Comment by alienator88** [comment]
Hey!
Could you let me know what the 2nd iPad app is as well? I'll test both of those out, it might be an issue with the web app wrapper if it's happening for iOS apps.

I like the confirmation alert idea, I can add that in fairly easily.
As for MacCleaner Pro, it should be finding those launch agent files, unless the name of the plist file doesn't contain MacCleaner Pro or it's bundle id. I can check on it and see where they install it and how they name it.

**Comment by alienator88** [comment]
Do you see any files related to MacCleaner Pro in these 3 locations?
```
/Users/YOUR_USERNAME/Library/LaunchAgents
/Library/LaunchAgents
/Library/LaunchDaemons
```

You can also run this in terminal to get a list of services:
`launchctl list`
Could grep that and see if there's anything for MacCleaner: 
`launchctl list | grep cleaner`

**Comment by WindWash** [comment]
> Hey! Could you let me know what the 2nd iPad app is as well? I'll test both of those out, it might be an issue with the web app wrapper if it's happening for iOS apps.
> 
> I like the confirmation alert idea, I can add that in fairly easily. As for MacCleaner Pro, it should be finding those launch agent files, unless the name of the plist file doesn't contain MacCleaner Pro or it's bundle id. I can check on it and see where they install it and how they name it.

Thank you for your response. I tested the second app, and its name is "Condution." The other one is called "Freenotes" (though I'm not sure if it's been listed for sale in other regions). It seems that this issue is affecting all iPhone apps, as they appear in the remaining files after running just once.

**Comment by WindWash** [comment]
> Do you see any files related to MacCleaner Pro in these 3 locations?
> 
> ```
> /Users/YOUR_USERNAME/Library/LaunchAgents
> /Library/LaunchAgents
> /Library/LaunchDaemons
> ```
> 
> You can also run this in terminal to get a list of services: `launchctl list` Could grep that and see if there's anything for MacCleaner: `launchctl list | grep cleaner`

I tried checking these locations, but I didn't find any relevant files.

**Comment by alienator88** [comment]
I figured out why the iOS apps are showing in the list, the container paths use a UUID number instead of a folder name. I added a function to translate those UUIDs into names and now it's ignoring those files as it should. Will have the fix out in the next release.

As for MacCleaner, try enabling it again from the settings and then run that launchctl list command again. I think that only shows active background services.

**Comment by WindWash** [comment]
> I figured out why the iOS apps are showing in the list, the container paths use a UUID number instead of a folder name. I added a function to translate those UUIDs into names and now it's ignoring those files as it should. Will have the fix out in the next release.
> 
> As for MacCleaner, try enabling it again from the settings and then run that launchctl list command again. I think that only shows active background services.

Thank you very much; the problem has been resolved.
