### ISSUE TITLE
[BUG] Password is required when doing brew upgrade of the app

### ISSUE THREAD

**Issue by misiektoja** [alienator88/Pearcleaner#87]
**Describe the bug:** <br>
Not sure if it is a bug or not, but I have never experienced anything like that with any other app managed by Homebrew.

Every time Pearcleaner is upgraded it asks for admin password, clearly because it needs to remove and add the launchctl service for Sentinel monitor, but I have it disabled in the settings (I think it is default?), so why this launchctl service is created ?

```
==> Upgrading 1 outdated package:
alienator88/cask/pearcleaner 3.8.2 -> 3.8.3
==> Upgrading pearcleaner
==> Downloading https://github.com/alienator88/Pearcleaner/releases/download/3.8.3/Pearcleaner.zip
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/717960955/24bacd55-df92-41e9-ae41-2511b6020
###################################################################################################################################### 100.0%
==> Removing launchctl service com.alienator88.PearcleanerSentinel
Password:
```

**Steps to reproduce:**
1. brew update && brew upgrade
2. upgrade Pearcleaner
3. it will ask for admin password

**Expected behavior:**

App should not remove & create new launchctl service during upgrade if Sentinel Monitor is disabled in the settings

**Info:**
 - OS: macOS 14.6 Sonoma
 - Pearcleaner Version: 3.8.2

**Comment by alienator88** [comment]
I just got the app merged into the main hombrew repo, so `brew install pearcleaner` should work now without tapping my cask repo.
Spoke with one of the brew maintainers who suggested a change to the launchctl parameters: https://github.com/Homebrew/homebrew-cask/pull/181460#issuecomment-2267133904

Hopefully that change only triggers the launch service removal if it's actually found/active. If it doesn't and still behaves the same, I'm not sure I can do anything about that, it's more of a homebrew limitation at that point. So crossing my fingers that it helps, we'll see when I get the next release pushed.
