### ISSUE TITLE
[FR] Accessibility Settings

### ISSUE THREAD

**Issue by khipp** [alienator88/Pearcleaner#88]
As someone who uses the accessibility setting for reduced motion, I would appreciate it if the app offered an option to disable animations. This could be implemented in a new section of the interface settings, with a toggle or selectable options to either follow the system setting or enable/disable animations, similar to the theme mode.

Specifically, the app list contains too many transition animations for hovered elements, which can become excessive when scrolling through the list.

**Further suggestions:**

- Having bold text and a vertical bar for the hovered list entry seems redundant. It might be better to remove the bold text altogether.
- Replacing the file size with the version information on hover is not intuitive. A possible improvement could be to append the version information to the app name, making it slightly smaller and lighter in color and keeping it visible by default.

**Comment by alienator88** [comment]
Those are good ideas :)
I'll definitely add an animation toggle and will look into the suggestions as well.

**Comment by alienator88** [comment]
I added the animation toggle on the Interface tab and removed the bold text on hover. I like it.
On the app version/app size suggestion, do you think this look too busy having all that info by the app name? I was trying to keep it more minimalistic. Apps with either long names or long version numbers cause a lot of truncation..
![image](https://github.com/user-attachments/assets/2bc81e42-ce04-4455-9a30-ee27e28814b8)

**Comment by khipp** [comment]
True, it might be a bit too long now that I'm seeing the example from `Brave Browser`. Another idea could be to use two lines per list item and place both the size and version information below the app name. This approach would also further reduce truncation.

If you decide to keep the original layout, I suggest removing the hover effect from the selected item, as it is no longer clickable and the version is already displayed in the second window.

<img width="1160" alt="Screenshot 2024-08-03 at 23 53 10" src="https://github.com/user-attachments/assets/5e2b9a1b-8061-49ad-bae1-f492585f7029">

**Comment by alienator88** [comment]
I'll see how two lines looks, if it's too busy I'll probably keep it the same for now.
As for the selected item, it's still clickable when the file view shows. Clicking it again just closes that view. 
Probably redundant since the view has a close button too but I just wanted a small notifier in the list to show where my spot was in case I scroll through the list and want to find my place again easily without having to read the app name again.

**Comment by alienator88** [comment]
How is this?
![image](https://github.com/user-attachments/assets/ec100eef-e8f7-43ed-b3c4-651639efd9bf)

**Comment by khipp** [comment]
That looks fine to me. I'll leave it up to you to decide how minimal you want to keep it.

Thanks again for making me aware of this app. Its ability to clean up leftover files is exactly what I've been missing in AppCleaner.

**Comment by alienator88** [comment]
I'll do a minimalist toggle setting for those type of users out there :)
These changes will be out in the next release, thanks so much for the input and assistance with brew earlier.
