### ISSUE TITLE
How to turn off the dynamic effect of the list

### ISSUE THREAD

**Issue by zhheo** [alienator88/Pearcleaner#89]
**Is your feature request related to a problem? Please describe.**

While scrolling through the list of apps, my machine felt a noticeable lag in dropping frames, which should be due to animations, even though I have the M1pro model.

**Describe the solution you'd like**

In fact, while these animated effects are cool, they may not be necessary for efficiency tools and can cause lagging

**Describe alternatives you've considered**

Add an animation switch or remove an animation

**Additional context**

none

**Comment by alienator88** [comment]
This is already completed from this FR: https://github.com/alienator88/Pearcleaner/issues/88#issuecomment-2267149806
Will be out in the upcoming release, probably today.
Thanks!

**Comment by zhheo** [comment]
The good news is that text animations have been deactivated to make the operation more intuitive and easier to use.
The bad news is that it proves that the performance issues with scrolling lists are not due to the animations, and that even when I turn off the animations, scrolling lists is still very laggy.
I think this performance issue is obvious, and you should also be able to feel the difference in performance between scrolling in the app list and scrolling anywhere else you go.
Looking forward to getting better and better, thanks!

**Comment by alienator88** [comment]
Can I ask how many apps you have installed?
I just worked with another user who had 250+ and I made some changes to lazy load the app list.
https://github.com/alienator88/Pearcleaner/issues/82
