### ISSUE TITLE
[FR] Drop area/list view and search bar feature suggestions

### ISSUE THREAD

**Issue by greg1075** [alienator88/Pearcleaner#9]
- Accessing list view by clicking the drop area would be a nice addition or replacement to the current button. 

- Another nice addition would be the automatic deletion of any typed search term in the search bar after the searched app has been deleted. That way, the user wouldn't have to delete what they typed before doing another search.

**Comment by alienator88** [comment]
Hey man, thanks for sending this over. I actually just got both of these implemented just now, so should be out in next update.

**Comment by greg1075** [comment]
Awesome! Thanks!

**Comment by alienator88** [comment]
Fixed by v1.9, closing issue
