### ISSUE TITLE
[FR] Find and (optionally) Remove Orphaned Files

### ISSUE THREAD

**Issue by fpuhan** [alienator88/Pearcleaner#90]
**Is your feature request related to a problem? Please describe.**

I've been trying to locate where Apple now stores some information under Sonoma (14.6) and much to my surprise have found leftover files from applications that have not existed on my Mac in years!  For example Live365, a streaming audio service, no longer exists on my Mac, and hasn't for quite some time.  Yet, I found remnants of it in .plist files and user and System libraries.  No app I've used, including MacCleaner have found and offered to remove them.  

**Describe the solution you'd like**

I suspect app removers like Pearcleaner work by identifying the app and then locating associated preference and plist files, license keys, etc.  Perhaps a reverse search on libraries for unlinked or removed apps might do the trick?  I confess, this would likely be a lengthy process, and one that need not be run often, but it could clear up a lot of cruft. 

**Describe alternatives you've considered**

MacCleaner and CCleaner (free and commercial) both attempt to do this, but since I've found files still on my disk, they don't seem to work 100% of the time.

I can write a simple shell script to traverse my ~/Library folder and iteratively ask me if I wish to remove files, but that's tedious and prone to error (missing files, deleting the wrong files, etc.).  For example, find . -name "*.log" -exec /bin/rm -i {} \;

**Additional context**
![Screenshot 2024-08-05 at 11 13 49 AM](https://github.com/user-attachments/assets/24179d21-84ce-425e-b88d-b93b0b5305fa)
![Screenshot 2024-08-05 at 11 19 39 AM](https://github.com/user-attachments/assets/7da2c90d-db88-488b-b15e-bf849f9efbcc)

**Comment by alienator88** [comment]
Does the Leftover File search I already have in the app not find these for you? It's set to look in that Preferences folder already, plus more: https://github.com/alienator88/Pearcleaner/blob/91f4ddd1a4447727221f3e88077929ed21e50020/Pearcleaner/Logic/Locations.swift#L90

As a test I added a dummy file with the same name for that plist and it found it, when I filter the results down.

Launch from the menu button:
![image](https://github.com/user-attachments/assets/4d693f3a-f032-4075-9789-2ac3b9167a20)

**Comment by fpuhan** [comment]
Wow, color me embarrassed!  I’ve focused on the settings to the exclusion of other items on the menu!  🫢

A scan just revealed 33.39 GB of “leftover” files.  I’ll have to investigate before I delete them, but this is very cool.  Looks like the fastest turnaround on a feature request I’ve ever seen!

Thanks!

Fred

**Comment by alienator88** [comment]
haha no worries!
I know it's a little hidden in that menu. I'm working on making some UI changes to expose it as a main button in the UI later on.
Currently it's only really mentioned in the Tips tab in the Settings of the app.

**Comment by fpuhan** [comment]
Geez, I’m amazed.  I have stuff dating back to 2008.  This machine wasn’t even built until 2020!

What happens when you migrate, then update, then migrate, then update…  Whew.

**Comment by alienator88** [comment]
Yeah, you're bound to have a ton of legacy stuff on there 😂

**Comment by fpuhan** [comment]
In these days of terabyte-size disks, 33.39 GB isn’t much.  But it’s useless, so I might as well get rid of it.  Thank you!

**Comment by fpuhan** [comment]
Can I ask you a question not Pearcleaner related, but as someone who obviously knows his way around a Mac, do you know under Sonoma where Mac stores the desktop image file names?

I use five spaces, each with photos from user-added folders (I take a lot of photographs).  They are set to randomly change once an hour.  I put together a little process under Ventura that worked when I called it.  

The photo image names under Ventura were kept in a sqlite database at ~/Library/Application Support/Dock/desktoppicture.db.  I would simply run a query, tail the result for the last five entries from the ‘data’ table and then pipe that to a nifty little program called Plash that would render the names as an overlay.  This is now broken under Sonoma, and even trying to find files in /Library or ~/Library by name or change time hasn’t revealed them.  There is a .plist that points to the folder, but not to the actual file name.  Does this sound familiar to you?

Thanks for your consideration.  If you don’t want to be bothered, no worries, and no offense taken.

Best,

Fred

**Comment by alienator88** [comment]
Well I can't be too sure since I've never dealt with those files myself, but testing it on my computer real quick, I'm seeing the image file names in the data table. It seems to have all the data in one table column called value though, so it's not separated in unique columns to where you can grab just the image file path:
```
> Dock sqlite3 desktoppicture.db
SQLite version 3.43.2 2023-10-10 13:08:14
Enter ".help" for usage hints.
sqlite> select * from data;
Black.png
1
0.0121805109083652
0.556764602661133
2
3
~/Pictures/MBP Wallpapers
3600.0
MBP14_M1Pro+2.png
~/Pictures/mojave.png
MBP14_MaxMatte.png
~/Pictures
sqlite>
```

**Comment by fpuhan** [comment]
Yes, that’s what worked for me under macOS 13.x (Ventura).  But now under 14.6 (Sonoma) it’s a zero-byte file.  I thought perhaps there was some corruption after I upgraded (?) to Sonoma, so I moved the file out to my Desktop and restarted my Mac.  The file was automatically created, but it’s stayed a zero-byte file since.  My desktop spaces are still being randomly updated, but I can’t find where macOS is storing the data. 

Fred

**Comment by alienator88** [comment]
Hmm, I see, you're probably right. I tried changing desktop wallpaper and the db file doesn't update. Wiped it and still nothing new in there.
Found that it is actually stored here now: `~/Library/Application Support/com.apple.wallpaper/Store/Index.plist`
This fork of pywal has a catch for the Sonoma changes here, you can explore this and see if you can make your workflow work with this:
https://github.com/robwaz/pywal/blob/dbfd6206be60f6030c5630ad8287deb6e60a8bb1/pywal/wallpaper.py#L177-L227

**Comment by fpuhan** [comment]
Thank you for your time and effort.  I am truly appreciative.  

Previously, I used Apple’s plutil command to view this plist, as it’s listed as a binary format.  Plutil allows for the viewing and converting into XML, JSON, binary, swift and Objective C.  The Index.plist file you mention won’t convert to JSON, but I output to an XML file and saw paths to the images, but not the image names.  There is a bunch of what I gather to be binary-encoded data still in the file, so if that’s Apple making a human-unreadable pointer to a file, I fear there’s nothing one can do.

I sent a note to the developer of TopNotch, a utility that “masks” the stupid “notch” that Apple has imposed on the M2 MacBook Pro because the program takes the original image and then processes it to another with the notch “removed.”  I figured that they should know where the image names are stored, but as yet I’ve heard no reply.  You’ve been very kind with your time, and I’m sorry to have caused you to waste it.  I’m not a developer (any more - many years ago I wrote code, but today’s programming is not in my wheelhouse any more), but simply a casual hacker trying to find an answer to a personal problem that I once had a solution for.  

(FYI: TopNotch also uses ~/Library/Application Support for its TopNotch folder, that contains two folders:  ‘originals' and ‘processed.’  I’m just trying to learn where and how they derive the ‘originals.”)

Fred

**Comment by alienator88** [comment]
So I opened the plist with Xcode and it shows me the file name as well. Unless I'm looking at the wrong thing 😂 
![image](https://github.com/user-attachments/assets/fcc6e084-1f24-4f8a-9f8e-62113b8d71bd)

**Comment by fpuhan** [comment]
This is too weird.  I also opened the file in Xcode and it just shows me the same thing I got with plutil.  A folder path but no file name.

￼

**Comment by fpuhan** [comment]
Hi Alin,

One more comment and then I won’t bother you anymore.  I have two MacBook I’m using, a 2020 M1 MacBook Pro and a 2022 M2 MacBook Air (both the 13” models).  The M2 is the one with the irritating “notch” Apple chose to impose on us, and which I have added the nice freeware TopNotch to remove it.  The M1 was running Ventura until I updated recently.  The M2 has been running Sonoma.  My hack was running on the M1, and which Ventura broke.

When I started digging into this, I found the TopNotch program took the original desktop images and made copies of them with the notch removed.  The original and processed images are stored in TopNotch’s location in ~/Library/Application Support.  Having been unable to discern why the M1 doesn’t seem to know the actual file names of the desktop images, I began poking around on the M2, which isn’t running my hack, and has never run it.  Checking the Index.plist on the M2 shows actual file names.  These file names all point to TopNotch’s “processed” files.  The names given are not my original names, but appear to be code-generated names.  Well, that makes sense, but it begs the question, why does my M1 not show the names?  I’m not running TopNotch on it.  

But that leaves what I think is the only other possibility:  Some other utility (menu bar, daemon) is also re-writing image names.  And this is colliding with Apple’s default storing and naming process.  Ah, what problems we impose when we start adding our own features and add-ons, eh?  This is the great benefit of Pearcleaner - it helps us get rid of old, useless stuff!  :)

Finally, I’m not sure Apple isn’t also culpable in this confusion.  On my M2, I added another space and set its desktop image like the others, just to see what might happen in the background.  This makes a total of five spaces on it, yet when I query the ~/Library/Application Support/com.apple.wallpaper/Store/Index.plist in terminal with `plutil -p Index.plist | grep relative` I get 64 items!  Some of those items I see don’t even exist on the file system any more.  Maybe Apple feels it’s necessary to keep an archive of items, but I suspect they just add entries to the plist without doing any housecleaning.  Still, I deleted the plist, killed the Dock (to clear any cache) and the plist was created anew.  Still with the 64 entries!  So, Apple is storing a history.  Where I don’t know, and after all this, I’m going to give up on my hack.  

Besides, Sequoia (macOS 15) is going to hit release status soon, and that will likely change the way Apple does things once again.  Sigh.

Again, thank you for taking the time to respond to my inane queries.  I’d like to thank you, so I’ve made a sponsorship donation on your GitHub site.  Enjoy a cup on me!

Best regards,

Fred

**Comment by alienator88** [comment]
Well shoot, that just leaves everything even more confusing, huh?
I'm out of ideas on this one..
Also, thank you so much for the sponsor donation Fred, it's very much appreciated!

**Comment by fpuhan** [comment]
Yeah, and Apple’s tech support is silent on this (and many other topics - a far cry from how they were when the Mac was introduced (yeah, I’m that old.  I used to have the original three-volume Inside Macintosh developer guides where Apple opened the kimono entirely).  I’ve long since stopped being a developer of any kind, although I still have a developer account.  Hmm.
