### ISSUE TITLE
[BUG] Hidden files after canceling password dialog

### ISSUE THREAD

**Issue by khipp** [alienator88/Pearcleaner#91]
**Describe the bug:** <br>
When using the leftover files removal tool, canceling the password insertion dialog will still hide the selected files even though they are not deleted.

**Steps to reproduce:**
1. Go to `Leftover Files`
2. Select any number of items of which at least one requires elevated permissions to delete
3. Press `cancel` when prompted to enter a password
4. All selected items are hidden

**Expected behavior** <br>
The list of files remains unchanged. Currently, a rescan has to be performed to refresh the list.

**Comment by alienator88** [comment]
Good catch, I'm not 100% sure but the regular file view list for an app's files might have the same bug. I'll need to add a catch there for cancelling.

**Comment by alienator88** [comment]
Resolved in next release.
