### ISSUE TITLE
[FR] Add hyperlinks to changelog entries

### ISSUE THREAD

**Issue by khipp** [alienator88/Pearcleaner#92]
When reading the changelog inside the app, entries are sometimes displayed with issue numbers. It would be convenient if these issue numbers were turned into hyperlinks that open the corresponding issues in the browser.

<img width="612" alt="image" src="https://github.com/user-attachments/assets/66bee26c-02b1-46d9-b08a-b42fefca1b76">

**Comment by alienator88** [comment]
So when I add those links in the change log, I'm only typing the number and GitHub seems to create that hyperlink on the site. When the updater pulls those, it only gets the text. I could work around that by using the actual URL in the change log probably.

**Comment by khipp** [comment]
That should do it. Since they all follow the same URL scheme you could just replace them with https://github.com/alienator88/Pearcleaner/issues/#number.

**Comment by alienator88** [comment]
That works, I'll do a string replace on that number or something similar

**Comment by alienator88** [comment]
Fixed in next release, closing issue.
