### ISSUE TITLE
[FR] Shortcut for leftover file exclusions

### ISSUE THREAD

**Issue by khipp** [alienator88/Pearcleaner#93]
Currently, exclusions for files and folders in the leftover files search have to be added manually in the app's folder settings. It would be convenient to have a shortcut in the right-click menu that automatically creates an exclusion. This menu item could be labeled `Ignore`, `Add to Exclusions`, or another fitting name.

<img width="575" alt="image" src="https://github.com/user-attachments/assets/15f0a01a-a43e-46bc-a244-4e9ddf05c77d">

**Comment by alienator88** [comment]
Dang, you have all the good ideas @khipp! That's way more intuitive, definitely adding this one.

**Comment by alienator88** [comment]
Added in next release, closing FR
