### ISSUE TITLE
[APP] Application Support file not detected when deleting Alfred 5

### ISSUE THREAD

**Issue by homjay** [alienator88/Pearcleaner#97]
>NOTE: If a specific app is finding unrelated files or not finding expected files, use the new condition builder to either include or exclude files from the search. Push CMD+B when you're on an app's page to show the condition builder.

**Describe the app**

A clear and concise description of what the affected app issue is.

Application Support dir is not detected when deleting Alfred 5

**App Details**
1. Alfred 5
2. 5.05
3. Website Download
4. Regular
5. /Users/user/Library/Application Support/Al

**Desktop (please complete the following information):**
 - OS: [e.g. 13.0]
 - Pearcleaner App Mode: [e.g. Regular / Mini Mode]
 - Pearcleaner Version: [e.g. 2.0]

Pearcleaner:
<img width="573" alt="image" src="https://github.com/user-attachments/assets/acd6b309-343c-460c-9bdf-232ec1dfb476">

App cleaner
<img width="750" alt="image" src="https://github.com/user-attachments/assets/7da08e3f-f9ac-4aa9-8b0a-d78e0d207547">

Raycast
<img width="626" alt="image" src="https://github.com/user-attachments/assets/d1c33d4c-a2d9-46b5-9188-a0da80c2fdc2">

**Additional context**

As we can see from the screenshot, the Application Support is not detected in PearCleaner, 3 MB size.

**Comment by alienator88** [comment]
Hi, thanks for letting me know!
It's happening because Pearcleaner searches for the app name, in this case "Alfred 5" and it doesn't match the folder named "Alfred".
Unfortunately this happens with certain apps since the devs give the local folders, names that differ from the app name sometimes, so I need to go in and add this exception.

**Comment by alienator88** [comment]
Fixed in next release when that comes out.
Thanks again!
