### ISSUE TITLE
[BUG] pbs.plist is not a leftover file

### ISSUE THREAD

**Issue by cat0x1f** [alienator88/Pearcleaner#99]
**Describe the bug:** <br>
This app incorrectly treating `~/Library/Preferences/pbs.plist` as a leftover file.

This file storaged settings about keyboard shortcuts.

**Steps to reproduce:**
Click the `Leftover Files` button.

**Expected behavior** <br>
pbs.plist should NOT appear in the table view.

**Info:**
 - OS: 14.6.1
 - Pearcleaner Version: 3.8.5

**Comment by alienator88** [comment]
Right click the file and Exclude. I can't add exceptions for every file in the OS as left over file search is fuzzy and not 100% accurate as per the warning icon on that page.
